/**
 * Clear English clues for shared crossword answers.
 * Each clue must name the Hangul meaning — never a false claim about the topic.
 */
const kpop = {
  debut: "Hangul spelling of “debut” — {name}’s first official release",
  comeback: "Hangul spelling of “comeback” — a new {name} release cycle",
  album: "Hangul spelling of “album”",
  title: "Hangul spelling of “title” — the promoted {name} track",
  mv: "Hangul short form of “music video” (MV)",
  concert: "Hangul spelling of “concert”",
  "world-tour": "Hangul spelling of “world tour”",
  choreo: "Korean word for choreography / group dance steps",
  stage: "Korean word for a performance stage",
  dance: "Hangul spelling of “dance”",
  vocal: "Hangul spelling of “vocal” — a singing part",
  rapper: "Hangul spelling of “rapper”",
  member: "Hangul spelling of “member”",
  leader: "Hangul spelling of “leader”",
  maknae: "Korean word for the youngest member — the role, not a person’s name",
  center: "Hangul spelling of “center” — the front spot in a formation",
  fandom: "Hangul spelling of “fandom”",
  lightstick: "Korean word for a fan light stick",
  variety: "Korean word for a TV variety / entertainment show",
  seoul: "Hangul for Seoul",
  korea: "Hangul for Korea",
  fanmeeting: "Hangul spelling of “fan meeting”",
  showcase: "Hangul spelling of “showcase”",
  fanclub: "Hangul spelling of “fan club” — the word itself, not a fandom name",
  visual: "Hangul spelling of “visual” — the looks position, not a member’s name",
  "main-vocal": "Hangul for “main vocal” — the position, not a person’s name",
  "main-dancer": "Hangul for “main dancer” — the position, not a person’s name",
  "main-rapper": "Hangul for “main rapper” — the position, not a person’s name",
  "lead-vocal": "Hangul for “lead vocal” — the position, not a person’s name",
  producer: "Hangul spelling of “producer”",
  lyrics: "Korean word for writing song lyrics",
  compose: "Korean word for composing a melody",
  single: "Hangul spelling of “single”",
  chart: "Hangul spelling of “chart”",
  billboard: "Hangul spelling of “Billboard”",
  melon: "Hangul for Melon, the Korean music chart",
  trainee: "Korean word for a pre-debut trainee",
  audition: "Hangul spelling of “audition”",
  agency: "Korean word for a management agency / label",
  idol: "Hangul spelling of “idol”",
  singer: "Korean word for singer",
  "music-show": "Korean word for a TV music show",
  "first-place": "Korean word for first place (a music-show win)",
  popular: "Korean word for popularity / being in demand",
  live: "Hangul spelling of “live”",
  fancam: "Korean word for a fan-cam close-up clip",
  goods: "Hangul spelling of “goods” (official merch)",
  cheer: "Korean word for an official fan chant",
  pictorial: "Korean word for a magazine pictorial / fashion shoot",
  interview: "Hangul spelling of “interview”",
  ad: "Korean word for an advertisement / commercial",
  model: "Hangul spelling of “model”",
  arena: "Korean word for a stadium / arena",
  fans: "Korean word for fans (plural)",
  chant: "Korean word for a crowd roar / cheer",
  chorus: "Korean word for fans singing the hook together",
  challenge: "Hangul spelling of “challenge” (dance trend)",
  youtube: "Hangul spelling of “YouTube”",
  mnet: "Hangul for Mnet",
  inkigayo: "Hangul for Inkigayo, the Sunday SBS music show",
  "music-core": "Hangul for Show! Music Core",
  "new-song": "Korean word for a newly released song",
  hit: "Korean word for a hit song",
  signature: "Korean word for a signature / representative song",
  "debut-song": "Korean word for a debut song",
  practice: "Korean word for a practice room",
  schedule: "Hangul spelling of “schedule”",
  manager: "Hangul spelling of “manager”",
  style: "Hangul spelling of “style”",
  fashion: "Hangul spelling of “fashion”",
  camera: "Hangul spelling of “camera”",
  crowd: "Korean word for the audience",
  harmony: "Hangul spelling of “harmony”",
  "high-note": "Korean word for a high note",
  rookie: "Korean word for a rookie / first-year act",
  global: "Hangul spelling of “global”",
  domestic: "Korean word for domestic (inside Korea)",
  overseas: "Korean word for overseas",
  activity: "Korean word for a promotion period / activities",
  "mini-album": "Hangul for “mini album” (EP)",
  "full-album": "Korean word for a full-length studio album",
  "follow-up": "Korean word for a follow-up / second promoted track",
  fansign: "Hangul spelling of “fansign”",
  "encore-stage": "Korean word for a music-show greeting / encore stage",
  "dance-film": "Korean word for a choreography video",
  tone: "Korean word for vocal tone / timbre",
  company: "Korean word for an entertainment company / label",
  streaming: "Hangul spelling of “streaming”",
  "album-sales": "Korean word for a physical music record",
  digital: "Korean word for a digital track / music file",
  "comeback-show": "Hangul for “comeback show”",
  teaser: "Hangul spelling of “teaser”",
  concept: "Hangul spelling of “concept”",
  styling: "Hangul spelling of “styling”",
  makeup: "Hangul spelling of “makeup”",
  rehearsal: "Hangul spelling of “rehearsal”",
  encore: "Hangul spelling of “encore”",
  soundcheck: "Hangul spelling of “soundcheck”",
  fanchant: "Korean word for a cheer / chant",
  photocard: "Hangul spelling of “photocard”",
  "album-pack": "Hangul for “album pack”",
  "stage-name": "Korean word for a stage name",
  unit: "Hangul spelling of “unit” (a smaller line)",
  "solo-run": "Hangul spelling of “solo”",
  duet: "Hangul spelling of “duet”",
  collab: "Hangul spelling of “collab”",
  featuring: "Hangul spelling of “featuring”",
  remix: "Hangul spelling of “remix”",
  repack: "Hangul short form of “repackage”",
  "pre-release": "Korean word for a pre-release track",
  "first-week": "Korean word for first-week album sales",
  million: "Hangul spelling of “million”",
  daesang: "Korean word for a grand prize (daesang)",
  bonsang: "Korean word for a main award (bonsang)",
  "rookie-award": "Korean word for a rookie award",
  "album-award": "Korean word for an album award",
  "digital-award": "Korean word for a digital-song award",
  "m-countdown": "Hangul short name for M Countdown",
  "the-show": "Hangul for The Show",
  "show-champion": "Hangul short name for Show Champion",
  "music-bank": "Hangul for Music Bank",
  "song-festival": "Korean word for a song festival",
  "year-end-fest": "Korean name for a year-end music festival",
  "red-carpet": "Hangul spelling of “red carpet”",
  "press-con": "Korean word for a press conference",
  "press-talk": "Korean word for a press showcase / media talk",
  "fan-con": "Hangul short form of “fan concert”",
  online: "Hangul spelling of “online”",
  offline: "Hangul spelling of “offline”",
  weverse: "Hangul for Weverse",
  bubble: "Hangul for Bubble, the paid idol-chat app",
  "fan-cafe": "Hangul for “fan cafe”",
  "official-fandom": "Korean word for an official fandom",
  membership: "Hangul spelling of “membership”",
  kit: "Hangul spelling of “kit”",
  poster: "Hangul spelling of “poster”",
  postcard: "Korean word for a postcard",
  sticker: "Hangul spelling of “sticker”",
  booklet: "Hangul spelling of “booklet”",
  digit: "Hangul spelling of “digit” (digital photocard code)",
  jacket: "Hangul for an album jacket / cover",
  performance: "Hangul spelling of “performance”",
  "point-dance": "Korean word for a point choreography / signature move",
  "group-dance": "Korean word for tight group dancing",
  "sharp-dance": "Korean word for razor-sharp formation dance",
  formation: "Hangul spelling of “formation”",
  "ending-pose": "Hangul for “ending pose”",
  intro: "Hangul spelling of “intro”",
  outro: "Hangul spelling of “outro”",
  bridge: "Hangul spelling of “bridge” (song section)",
  "chorus-part": "Korean word for a chorus / refrain",
  "hook-song": "Hangul for a hook song",
  ballad: "Hangul spelling of “ballad”",
  hiphop: "Hangul spelling of “hip-hop”",
  rnb: "Hangul for R&B",
  "dance-track": "Korean word for a dance song",
  "title-track": "Korean word for a title track / lead single",
  "b-side": "Korean word for a B-side / album track",
  "self-written": "Korean word for a self-written song",
  producing: "Hangul spelling of “producing”",
  arrange: "Korean word for arranging a song",
  mixing: "Hangul spelling of “mixing”",
  mastering: "Hangul spelling of “mastering”",
  record: "Korean word for recording a vocal",
  studio: "Korean word for a recording studio",
  "vocal-director": "Hangul short form of “vocal director”",
  choreographer: "Korean word for a choreographer",
  stylist: "Hangul spelling of “stylist”",
  hair: "Hangul spelling of “hair”",
  sound: "Korean word for live sound / audio",
  prop: "Korean word for a stage prop",
  costume: "Korean word for a costume / outfit",
  "stage-set": "Korean word for stage set / scenery",
  "concert-hall": "Korean word for a concert hall",
  stadium: "Hangul spelling of “stadium”",
  festival: "Hangul spelling of “festival”",
  lineup: "Hangul spelling of “lineup”",
  headliner: "Hangul spelling of “headliner”",
  "opening-act": "Hangul spelling of “opening”",
  guest: "Hangul spelling of “guest”",
  "special-stage": "Hangul for “special stage”",
  "encore-song": "Korean word for an encore song",
  medley: "Hangul spelling of “medley”",
  cover: "Hangul spelling of “cover”",
  remake: "Hangul spelling of “remake”",
  "original-song": "Korean word for the original song (before a cover)",
  "vocal-skill": "Korean word for singing ability",
  "rap-part": "Hangul for “rap part”",
  "high-note-en": "Hangul spelling of “high note”",
  adlib: "Hangul spelling of “ad-lib”",
  "chorus-stack": "Hangul spelling of “chorus” (backing vocals)",
  breath: "Korean word for breath / breath control",
  "voice-train": "Korean word for vocalization / voice training",
  diction: "Hangul spelling of “diction”",
  charisma: "Hangul spelling of “charisma”",
  aura: "Hangul spelling of “aura”",
  chemistry: "Hangul short form of “chemistry”",
  selfie: "Korean word for a selfie",
  "selca-pic": "Korean slang for a fan-taken still photo",
  vlog: "Hangul spelling of “vlog”",
  reality: "Hangul spelling of “reality” (reality show)",
  documentary: "Hangul short form of “documentary”",
  "variety-sense": "Korean word for variety-show talent / funniness",
  "bias-wreck": "Korean word for falling into a fandom for the first time",
  bias: "Korean fan word for a favorite member",
  "second-bias": "Korean fan word for a second-favorite member",
  "ot-fan": "Korean fan word for someone who loves the whole group",
  stan: "Korean word for the hobby of being a dedicated fan",
  "bias-song": "Korean fan word for a favorite song",
  "bias-mem": "Korean fan short word for a favorite member",
  poca: "Korean short word for a photocard",
  unboxing: "Hangul for “album unboxing”",
  "open-pack": "Korean word for opening a package",
  collect: "Korean word for keeping / collecting",
  limited: "Korean word for a limited edition",
  standard: "Korean word for the regular edition",
  "platform-album": "Hangul for “platform album”",
  digipack: "Hangul spelling of “digipack”",
  kino: "Hangul spelling of “Kino” (kit-style album)",
  lp: "Hangul for LP / vinyl",
  cd: "Hangul for CD",
  dvd: "Hangul for DVD",
  bluray: "Hangul spelling of “Blu-ray”",
  "video-call": "Korean word for a video call",
  "fan-call": "Hangul short form of “fan call”",
  yeongtong: "Korean slang for a video-call fansign",
  "in-person": "Korean word for meeting in person",
  remote: "Korean word for not meeting in person / remote",
  "sign-event": "Korean word for a signing event",
  "mini-fanmeet": "Hangul for “mini fan meeting”",
  busking: "Hangul spelling of “busking”",
  guerrilla: "Hangul spelling of “guerrilla” (surprise stage)",
  "surprise-show": "Korean word for a surprise performance",
  "pre-record": "Korean word for a pre-record taping",
  "live-tv": "Korean word for a live broadcast",
  taping: "Korean word for taping / recording a show",
  "waiting-room": "Korean word for a waiting room",
  "dressing-room": "Korean word for a dressing room",
  "dance-practice": "Korean word for dance practice",
  "vocal-lesson": "Hangul for “vocal lesson”",
  "foreign-lang": "Korean word for a foreign language",
  japanese: "Korean word for the Japanese language",
  english: "Korean word for the English language",
  chinese: "Korean word for the Chinese language",
  "japan-tour": "Hangul for “Japan tour”",
  "us-tour": "Hangul for “US tour”",
  "europe-tour": "Hangul for “Europe tour”",
  "asia-tour": "Hangul for “Asia tour”",
  "world-star": "Hangul for “world star”",
  "hallyu-star": "Hangul for “Hallyu star” / Korean Wave star",
  "icon-act": "Hangul spelling of “icon”",
  "legend-act": "Hangul spelling of “legend”",
  "legend-kr": "Korean native word for a legend",
  sunbae: "Korean word for a senior (older debut)",
  hoobae: "Korean word for a junior (newer debut)",
  "same-year": "Korean word for a same-year debut peer",
  "best-friend": "Korean word for a best friend",
  teamwork: "Hangul spelling of “teamwork”",
  leadership: "Hangul spelling of “leadership”",
  "all-rounder": "Hangul spelling of “all-rounder”",
  "all-talent": "Korean word for being good at everything",
  talent: "Korean word for talent",
  passion: "Korean word for passion",
  goal: "Korean word for a goal",
  success: "Korean word for success",
  glory: "Korean word for glory / honor",
  moved: "Korean word for being moved / touched",
  tears: "Korean word for tears",
  happy: "Korean word for happiness",
  love: "Korean word for love",
  "cheer-song": "Korean word for a cheer song",
  slogan: "Hangul spelling of “slogan”",
  "cheer-tool": "Korean word for a cheering tool / fan prop",
  "official-color": "Hangul for “official color”",
  "fan-color": "Hangul for “fan color”",
  "lyrics-text": "Korean word for song lyrics (the words)",
  "pronounce-guide": "Hangul for “pronunciation guide”",
  "hangul-script": "Korean word for the Hangul script",
  "korean-lang": "Korean word for the Korean language",
  romanization: "Korean word for romanization (English letters)",
  "sub-unit": "Hangul for “sub-unit”",
  "group-act": "Hangul spelling of “group”",
  "special-ver": "Hangul spelling of “special”",
  "double-title": "Hangul for “double title”",
  "pre-order": "Korean word for a pre-order",
  "golden-disc": "Hangul for the Golden Disc Awards",
  "live-broadcast": "Hangul for “live broadcast”",
  "universe-app": "Hangul for Universe, an older fan app",
  rock: "Korean word for rock music",
  dream: "Korean words for “dream and hope” (two words together)",
  dome: "Korean word for a dome stadium",
  "live-clip": "Hangul for “live clip”",
  "weverse-con": "Hangul short name for a Weverse concert",
  "fan-light": "Korean word for a wave of light sticks",
  "album-shop": "Korean word for a record store",
  "music-store": "Korean word for a music shop",
  "radio-show": "Hangul spelling of “radio”",
  "late-night": "Korean word for a late-night broadcast",
  "morning-show": "Korean word for a morning broadcast",
  endorsement: "Korean word for a model contract / endorsement deal",
  ambassador: "Korean word for a promotional ambassador",
  cf: "Hangul for CF (a Korean TV commercial)",
  "pictorial-set": "Korean word for a pictorial shoot",
  "cover-mag": "Korean word for a cover model",
  sns: "Hangul spelling of “SNS” (social media)",
  instagram: "Hangul short name for Instagram",
  tiktok: "Hangul spelling of “TikTok”",
  weibo: "Hangul spelling of “Weibo”",
  twitter: "Hangul for X, the app formerly called Twitter",
  "fancam-ver": "Korean word for a fancam video",
  "relay-dance": "Hangul for “relay dance”",
  "dance-challenge": "Hangul for “challenge video”",
  behind: "Hangul spelling of “behind” (behind-the-scenes)",
  making: "Hangul spelling of “making” (making-of)",
  "jacket-shoot": "Korean word for a jacket / cover shoot",
  "mv-set": "Hangul for “MV set”",
  "practice-wear": "Korean word for practice clothes",
  "in-ear": "Hangul for in-ear monitors",
  click: "Hangul spelling of “click” (click track)",
  "formation-change": "Korean word for a formation / place change",
  "center-part": "Hangul for “center part”",
  "ending-fairy": "Hangul for “ending fairy”",
  "first-win": "Korean word for a first win / first trophy",
  "triple-crown": "Hangul spelling of “triple crown”",
  "grand-slam": "Hangul spelling of “grand slam”",
  "rookie-year": "Korean word for debut year",
  anniversary: "Korean word for an anniversary",
  "debut-stage": "Korean word for a debut stage",
  "last-stage": "Korean word for a last stage / finale stage",
  hiatus: "Korean word for a hiatus / rest period",
  enlist: "Korean word for enlisting in the military",
  discharge: "Korean word for being discharged from the military",
  military: "Korean word for the military / army service",
  "comeback-date": "Korean word for a comeback date",
  "release-date": "Korean word for a release date",
  "pre-save": "Hangul spelling of “pre-save”",
  "streaming-party": "Hangul for “streaming party”",
  "chart-run": "Korean word for charting / entering the chart",
  realtime: "Hangul for “realtime chart”",
  "unique-listen": "Hangul spelling of “unique” (unique listeners)",
  "like-count": "Korean word for likes (the heart count)",
  "view-count": "Korean word for view count",
  subscribe: "Korean word for subscribe",
  "premiere-mv": "Korean word for a first public premiere",
  tracklist: "Hangul spelling of “tracklist”",
  credit: "Hangul spelling of “credit”",
  songwriter: "Korean word for a composer / songwriter",
  lyricist: "Korean word for a lyricist",
  beat: "Hangul spelling of “beat”",
  sample: "Hangul spelling of “sample”",
  hook: "Hangul for “hook line”",
  "key-change": "Korean word for a key change",
  tempo: "Hangul spelling of “tempo”",
  bpm: "Hangul for BPM",
  "live-band": "Hangul spelling of “band”",
  "mr-removed": "Hangul for MR (the backing track)",
  "in-ear-mix": "Hangul spelling of “monitor” (stage mix)",
  "sound-engineer": "Korean word for a sound director / engineer",
  "tour-md": "Hangul for “tour goods”",
  "light-ocean": "Korean words for a sea / wave of lights",
  "encore-ment": "Hangul spelling of “ment” (spoken talk on stage)",
  ment: "Hangul for “concert ment” (talk between songs)",
  setlist: "Hangul spelling of “setlist”",
  "d-1": "Hangul for D-day (the concert or deadline day)",
  ticket: "Hangul spelling of “ticket”",
  ticketing: "Hangul spelling of “ticketing”",
  "waiting-line": "Korean word for a waiting line",
  "soundcheck-tix": "Korean word for a soundcheck ticket",
  "vip-seat": "Hangul spelling of “VIP”",
  floor: "Hangul spelling of “standing” (standing floor)",
  seat: "Korean word for an assigned seat",
  "slogan-event": "Hangul for “slogan event”",
  "birthday-cafe": "Korean short word for a birthday cafe",
  birthday: "Korean word for birthday",
  "debut-day": "Korean word for a debut date",
  "group-name": "Korean word for a group name",
  "official-logo": "Hangul spelling of “logo”",
  "official-color-2": "Korean word for a representative color",
  "light-color": "Korean word for a light-stick color",
  "fandom-color": "Korean word for a fandom color",
};

const drama = {
  love: "Korean word for love",
  family: "Korean word for family",
  secret: "Korean word for a secret",
  fate: "Korean word for fate / destiny",
  goodbye: "Korean word for a breakup / farewell (between lovers)",
  reunion: "Korean word for a reunion",
  drama: "Hangul spelling of “drama”",
  actor: "Korean word for an actor (usually a man)",
  actress: "Korean word for an actress",
  director: "Korean word for a director",
  script: "Korean word for a script",
  scene: "Korean word for a scene",
  tears: "Korean word for tears",
  confession: "Korean word for a love confession",
  "first-love": "Korean word for first love",
  memory: "Korean word for a memory",
  promise: "Korean word for a promise",
  friendship: "Korean word for friendship",
  betrayal: "Korean word for betrayal",
  revenge: "Korean word for revenge",
  romance: "Hangul spelling of “romance”",
  melo: "Hangul short form of “melodrama”",
  school: "Korean word for school",
  hospital: "Korean word for hospital",
  company: "Korean word for a company / workplace",
  seoul: "Hangul for Seoul",
  korea: "Hangul for Korea",
  filming: "Korean word for filming / a shoot",
  set: "Hangul spelling of “set” (film set)",
  hero: "Korean word for the main character / protagonist",
  villain: "Korean word for a villain / antagonist role",
  support: "Korean word for a supporting role",
  cameo: "Hangul spelling of “cameo”",
  ending: "Korean word for an ending",
  twist: "Korean word for a plot twist",
  conflict: "Korean word for conflict",
  emotion: "Korean word for being moved / emotional impact",
  ost: "Hangul spelling of “OST” (soundtrack)",
  theme: "Korean word for a theme song",
  line: "Korean word for a famous line / memorable quote",
  shot: "Korean word for a famous scene / iconic shot",
  rating: "Korean word for TV ratings",
  broadcast: "Korean word for a broadcast",
  netflix: "Hangul spelling of “Netflix”",
  hallyu: "Korean word for the Korean Wave",
  syndrome: "Hangul spelling of “syndrome” (a craze)",
  fans: "Korean word for fans (plural)",
  award: "Korean word for an acting award",
  ceremony: "Korean word for an awards ceremony",
  cannes: "Hangul for the Cannes Film Festival",
  oscar: "Hangul spelling of “Oscar”",
  "hit-film": "Korean word for a box-office hit",
  "ten-million": "Korean word for ten million (a huge audience)",
  audience: "Korean word for the audience",
  festival: "Korean word for a film festival",
  screenplay: "Korean word for a screenplay",
  directing: "Korean word for directing",
  location: "Korean word for a filming location",
  costume: "Korean word for a costume",
  makeup: "Korean word for makeup / character makeup",
  light: "Korean word for lighting",
  camera: "Hangul spelling of “camera”",
  village: "Korean word for a village / town",
  city: "Korean word for a city",
  sea: "Korean word for the sea",
  mountain: "Korean word for a mountain area / in the mountains",
  winter: "Korean word for winter",
  summer: "Korean word for summer",
  coffee: "Hangul spelling of “coffee”",
  letter: "Korean word for a letter",
  ring: "Korean word for a ring",
  wedding: "Korean word for a wedding ceremony",
  police: "Korean word for the police",
  prosecutor: "Korean word for a prosecutor",
  doctor: "Korean word for a doctor",
  teacher: "Korean word for a teacher (polite form)",
  chaebol: "Korean word for a chaebol / wealthy conglomerate family",
  secretary: "Korean word for a secretary / assistant",
  soldier: "Korean word for a soldier",
  spy: "Hangul spelling of “spy”",
  hope: "Korean word for hope",
  despair: "Korean word for despair",
  courage: "Korean word for courage",
  wound: "Korean word for a wound / emotional scar",
  heal: "Korean word for healing",
  waiting: "Korean word for waiting / the wait",
  meeting: "Korean word for a meeting / first encounter",
  heart: "Korean word for the heart / one’s feelings",
  dream: "Korean word for a wish / a hope one asks for",
  lie: "Korean word for a lie",
  truth: "Korean word for the truth",
  justice: "Korean word for justice",
  crime: "Korean word for a crime",
  mystery: "Hangul spelling of “mystery”",
  thriller: "Hangul spelling of “thriller”",
  comedy: "Hangul spelling of “comedy”",
  tragedy: "Korean word for tragedy",
  episode: "Korean word for an episode number / weekly chapter",
  season: "Hangul spelling of “season”",
  premiere: "Korean word for a first broadcast",
  finale: "Korean word for the last episode",
  "ost-singer": "Korean word for singing / vocal performance (on an OST)",
  original: "Korean word for the original work (book, comic, etc.)",
  pilot: "Hangul spelling of “pilot”",
  special: "Hangul spelling of “special”",
  recap: "Korean word for a recap / summary",
  preview: "Korean word for a preview / next-week teaser",
  "teaser-cut": "Hangul spelling of “teaser”",
  poster: "Hangul spelling of “poster”",
  still: "Hangul for “still cut” (a still photo)",
  bcut: "Hangul spelling of “behind” (behind-the-scenes)",
  making: "Hangul spelling of “making” (making-of)",
  press: "Korean word for a production press conference",
  interview: "Hangul spelling of “interview”",
  magazine: "Korean word for a pictorial",
  "ost-album": "Hangul spelling of “soundtrack”",
  "part-one": "Hangul for “part one” (OST Part 1)",
  "ballad-ost": "Hangul spelling of “ballad”",
  "love-song": "Korean word for a love song / love ballad",
  "insert-song": "Korean word for an insert song (played inside a scene)",
  score: "Hangul spelling of “score” (instrumental music)",
  composer: "Korean word for a composer",
  writer: "Korean word for a writer",
  pd: "Hangul for PD (producer-director)",
  crew: "Hangul spelling of “staff”",
  cast: "Korean word for the cast",
  "lead-pair": "Korean word for the male and female leads",
  "second-couple": "Hangul for “sub couple” (the second couple)",
  chemistry: "Hangul short form of “chemistry”",
  "eye-contact": "Korean word for eye contact",
  "hand-hold": "Korean word for holding hands",
  hug: "Korean word for a hug",
  kiss: "Hangul spelling of “kiss”",
  date: "Hangul spelling of “date”",
  "rain-scene": "Korean word for “in the rain”",
  umbrella: "Korean word for an umbrella",
  "night-walk": "Korean word for a night walk",
  rooftop: "Korean word for a rooftop",
  "han-river": "Hangul for the Han River",
  cafe: "Hangul spelling of “cafe”",
  bookstore: "Korean word for a bookstore",
  alley: "Korean word for an alley",
  home: "Korean for “our home” / “our house”",
  apartment: "Hangul spelling of “apartment”",
  mansion: "Korean word for a mansion / large house",
  "office-desk": "Korean word for a desk",
  "meeting-room": "Korean word for a meeting room",
  court: "Korean word for a courtroom",
  prison: "Korean word for a prison",
  station: "Korean word for a police station",
  "crime-scene": "Korean word for a scene / site (often a crime scene)",
  evidence: "Korean word for evidence",
  suspect: "Korean word for a suspect",
  alibi: "Hangul spelling of “alibi”",
  witness: "Korean word for a witness",
  trial: "Korean word for a trial",
  verdict: "Korean word for a verdict / court ruling",
  investigation: "Korean word for an investigation",
  detective: "Korean word for a detective",
  profiler: "Hangul spelling of “profiler”",
  journalist: "Korean word for a reporter",
  lawyer: "Korean word for a lawyer",
  judge: "Korean word for a judge",
  nurse: "Korean word for a nurse",
  surgeon: "Korean word for a surgeon",
  patient: "Korean word for a patient",
  student: "Korean word for a student",
  "teacher-role": "Korean word for a teacher (job title)",
  principal: "Korean word for a school principal",
  classmate: "Korean word for a classmate / alumni peer",
  senior: "Korean word for a senior (older schoolmate)",
  junior: "Korean word for a junior (younger schoolmate)",
  uniform: "Korean word for a school uniform",
  exam: "Korean word for an exam",
  college: "Korean word for university / college",
  dorm: "Korean word for a dormitory",
  "part-time": "Korean slang for a part-time job",
  ceo: "Korean word for a CEO / company representative",
  chairman: "Korean word for a chairman",
  heir: "Korean word for an heir / successor",
  rival: "Hangul spelling of “rival”",
  enemy: "Korean word for an enemy / sworn foe",
  ally: "Korean word for a colleague / ally",
  mentor: "Hangul spelling of “mentor”",
  mother: "Korean word for mother",
  father: "Korean word for father",
  daughter: "Korean word for a little daughter / one’s girl",
  son: "Korean word for a son",
  sister: "Korean word for an older sister",
  brother: "Korean honorific for an older brother",
  grandmother: "Korean word for grandmother",
  grandfather: "Korean word for grandfather",
  "in-law": "Korean word for a husband’s family / in-laws",
  marriage: "Korean word for marriage",
  divorce: "Korean word for divorce",
  contract: "Korean word for a contract",
  "fake-dating": "Korean word for a fake romance / contract relationship",
  breakup: "Korean word for breaking up",
  jealousy: "Korean word for jealousy",
  misunderstanding: "Korean word for a misunderstanding",
  apology: "Korean word for an apology",
  forgiveness: "Korean word for forgiveness",
  trust: "Korean word for trust",
  loyalty: "Korean word for loyalty / honor among friends",
  sacrifice: "Korean word for a sacrifice",
  guilt: "Korean word for guilt",
  trauma: "Hangul spelling of “trauma”",
  therapy: "Korean word for counseling / therapy",
  diary: "Korean word for a diary",
  photo: "Korean word for a photo",
  phone: "Korean word for a phone call",
  message: "Korean word for a text message",
  email: "Hangul short form of “mail” / email",
  key: "Korean word for a key",
  box: "Korean word for a box",
  gift: "Korean word for a gift",
  flower: "Korean word for a bouquet",
  rose: "Korean word for a rose",
  necklace: "Korean word for a necklace",
  watch: "Korean word for a watch / clock",
  scarf: "Korean word for a scarf / muffler",
  book: "Korean for “one book” / a single book",
  "music-box": "Korean word for a music box",
  piano: "Hangul spelling of “piano”",
  guitar: "Hangul spelling of “guitar”",
  song: "Korean word for a song",
  dance: "Korean word for dance moves / a dance gesture",
  food: "Korean word for food",
  ramyeon: "Hangul for ramyeon / ramen",
  soju: "Hangul for soju",
  chicken: "Hangul spelling of “chicken”",
  gimbap: "Hangul for gimbap",
  tteokbokki: "Hangul for tteokbokki",
  hotpot: "Korean word for a hot-pot stew",
  "birthday-cake": "Hangul spelling of “cake”",
  "first-snow": "Korean word for the first snow",
  spring: "Korean word for a spring day",
  autumn: "Korean word for autumn",
  night: "Korean word for the night sky",
  dawn: "Korean word for dawn / early morning",
  sunset: "Korean word for a sunset glow",
  star: "Korean word for starlight",
  moon: "Korean word for moonlight",
  rain: "Korean word for rainwater / rain",
  snow: "Korean word for a snowflake",
  wind: "Korean word for wind",
  island: "Korean word for an island village",
  harbor: "Korean word for a harbor / port",
  market: "Korean word for a market",
  palace: "Korean word for a royal palace",
  hanbok: "Hangul for hanbok",
  sword: "Korean word for a blade / sword edge",
  king: "Korean word for a king (traditional word)",
  queen: "Korean word for a queen / king’s wife",
  prince: "Korean word for a prince",
  princess: "Korean word for a princess",
  servant: "Korean word for a palace maid",
  eunuch: "Korean word for a court eunuch",
  rebellion: "Korean word for a rebellion",
  throne: "Korean word for a throne",
  war: "Korean word for war",
  peace: "Korean word for peace",
  escape: "Korean word for an escape",
  chase: "Korean word for a chase / pursuit",
  fight: "Korean word for a fight",
  gun: "Korean word for a pistol / handgun",
  car: "Korean word for a car",
  train: "Korean word for a train",
  plane: "Korean word for an airplane",
  ship: "Korean word for a ship",
  border: "Korean word for a national border",
  north: "Hangul for North Korea",
  south: "Hangul for South Korea",
  abroad: "Korean word for overseas / abroad",
  hometown: "Korean word for a hometown",
  busan: "Hangul for Busan",
  incheon: "Hangul for Incheon",
  jeju: "Hangul for Jeju",
  gangnam: "Hangul for Gangnam",
  itaewon: "Hangul for Itaewon",
  hongdae: "Hangul for Hongdae",
  myeongdong: "Hangul for Myeongdong",
  tvn: "Hangul for TVING, the Korean streaming service",
  sbs: "Hangul spelling of “SBS”",
  kbs: "Hangul spelling of “KBS”",
  mbc: "Hangul spelling of “MBC”",
  jtbc: "Hangul spelling of “JTBC”",
  "tvn-ch": "Hangul spelling of “tvN”",
  disney: "Hangul for Disney",
  amazon: "Hangul spelling of “Amazon”",
  "box-office": "Hangul spelling of “box office”",
  "opening-week": "Korean word for opening week (in theaters)",
  "premiere-film": "Korean word for a premiere screening",
  critic: "Korean word for criticism / a review essay",
  review: "Hangul spelling of “review”",
  "rating-star": "Korean word for a star rating",
  subtitle: "Korean word for subtitles",
  dubbing: "Korean word for dubbing",
  "remake-of": "Hangul spelling of “remake”",
  "webtoon-src": "Hangul spelling of “webtoon”",
  "novel-src": "Korean word for a novel",
  "true-story": "Korean word for a true story",
  period: "Korean word for a period drama",
  sageuk: "Korean word for a historical drama (sageuk)",
  modern: "Korean word for a modern-day drama",
  fantasy: "Hangul spelling of “fantasy”",
  horror: "Korean word for horror",
  action: "Hangul spelling of “action”",
  sf: "Korean word for science fiction",
  zombie: "Hangul spelling of “zombie”",
  ghost: "Korean word for a ghost",
  monster: "Korean word for a monster",
  magic: "Korean word for magic",
  "time-slip": "Hangul spelling of “time slip”",
  reincarnation: "Korean word for reincarnation",
  "dream-seq": "Korean word for “inside a dream”",
  flashback: "Korean word for a flashback / recollection",
  montage: "Hangul spelling of “montage”",
  cliffhanger: "Hangul spelling of “cliffhanger”",
  "open-ending": "Korean word for an open ending",
  "happy-end": "Hangul spelling of “happy ending”",
  "sad-end": "Hangul spelling of “sad ending”",
  "mid-point": "Korean word for the midpoint / middle",
  climax: "Hangul spelling of “climax”",
  epilogue: "Hangul spelling of “epilogue”",
  prologue: "Hangul spelling of “prologue”",
  "title-card": "Hangul spelling of “title”",
  "opening-title": "Hangul spelling of “opening”",
  "ending-credit": "Hangul spelling of “ending credits”",
  "cameo-star": "Korean word for a special appearance / cameo",
  "extra-role": "Hangul spelling of “extra”",
  "stand-in": "Korean word for a body double / stand-in",
  stunt: "Hangul spelling of “stunt”",
  cgi: "Hangul spelling of “CGI”",
  vfx: "Korean word for special / visual effects",
  "sound-fx": "Korean word for sound / sound design",
  "color-grade": "Korean word for color grading",
  edit: "Korean word for editing",
  cut: "Korean word for cut editing",
  take: "Hangul spelling of “take”",
  ng: "Hangul for NG (a blooper / failed take)",
  "ad-lib": "Hangul spelling of “ad-lib”",
  "line-read": "Korean word for dialogue / spoken lines",
  voice: "Korean word for a voice",
  look: "Korean word for a look in someone’s eyes",
  smile: "Korean word for a smile",
  "cry-act": "Korean word for crying / a crying scene",
  laugh: "Korean word for laughter",
  silence: "Korean word for silence",
  "theme-color": "Korean word for color tone / palette",
  symbol: "Korean word for a symbol",
  motif: "Hangul spelling of “motif”",
  foreshadow: "Korean word for foreshadowing",
  payoff: "Korean word for a payoff / paying off a setup",
  macguffin: "Hangul spelling of “MacGuffin”",
  "macguffin-kr": "Korean word for an object / a thing",
  map: "Korean word for a map",
  "letter-seal": "Korean word for a seal / something sealed",
  password: "Korean word for a password / cipher",
  code: "Hangul spelling of “code”",
  clock: "Korean word for a clockwork / clock spring",
  deadline: "Korean word for a time limit / deadline",
  countdown: "Hangul spelling of “countdown”",
  "last-chance": "Korean word for a last chance",
  "second-chance": "Korean word for a second chance",
  "new-life": "Korean word for a fresh start",
  homecoming: "Korean word for returning to one’s hometown",
  farewell: "Korean word for farewell",
  "see-you": "Korean for “see you again”",
  "credits-ost": "Korean word for an ending song",
  "hit-line": "Korean word for a catchphrase / trendy line",
  meme: "Hangul for an internet meme",
  fandom: "Hangul spelling of “fandom”",
  binge: "Korean word for binge-watching from the start",
  rewatch: "Korean word for a rewatch",
  spoiler: "Hangul spelling of “spoiler”",
  theory: "Korean word for deduction / a theory",
  forum: "Korean word for a forum / message board",
  clip: "Hangul spelling of “clip”",
  gif: "Korean word for a looping gif / short moving image",
  "ost-chart": "Korean word for a digital music chart",
  "award-best": "Korean word for a grand prize (daesang)",
  popularity: "Korean word for popularity",
  "global-hit": "Korean word for worldwide / global",
  export: "Korean word for export",
  wave: "Korean word for a craze / boom",
  craze: "Korean word for heat / excitement around a hit",
  "record-rating": "Korean word for a record-high rating",
  timeslot: "Korean word for a timeslot",
  weekend: "Korean word for a weekend drama",
  weeknight: "Korean word for a weekday",
  miniseries: "Hangul spelling of “miniseries”",
  feature: "Korean word for a feature-length work",
  "short-film": "Korean word for a short film / short story",
  sequel: "Korean word for a sequel",
  prequel: "Hangul spelling of “prequel”",
  spinoff: "Hangul spelling of “spin-off”",
  universe: "Korean word for a story universe / world-building",
  franchise: "Hangul spelling of “franchise”",
  reboot: "Hangul spelling of “reboot”",
  "original-ip": "Korean word for intellectual property (IP)",
  rights: "Korean word for copyright / adaptation rights",
  budget: "Korean word for a production budget",
  investor: "Korean word for investment",
  "studio-co": "Korean word for a production company",
  distributor: "Korean word for a distributor",
  screen: "Hangul spelling of “screen”",
  imax: "Hangul spelling of “IMAX”",
  "ticket-sold": "Korean word for an admission ticket",
  "sold-out": "Korean word for sold out",
  "encore-run": "Korean word for a rerelease in theaters",
  "director-cut": "Korean word for a director’s cut",
  unrated: "Korean word for an uncut / unrated version",
  "age-rate": "Korean word for an age rating",
  "all-ages": "Korean rating words for “all ages admitted”",
  fifteen: "Korean rating words for age 15",
  nineteen: "Korean short rating for 19+ / restricted",
  warning: "Korean word for a warning",
  violence: "Korean word for violence",
  "romance-plot": "Korean word for dating / a romance",
  bromance: "Hangul spelling of “bromance”",
  "found-family": "Korean word for a found family / family-by-bond",
  team: "Korean for “one team”",
  leader: "Hangul spelling of “leader”",
  rookie: "Korean word for a rookie",
  veteran: "Hangul spelling of “veteran”",
  genius: "Korean word for a genius",
  underdog: "Korean word for the weaker side / underdog",
  heroine: "Korean short word for the female lead",
  "hero-male": "Korean short word for the male lead",
  antihero: "Hangul spelling of “antihero”",
  mastermind: "Korean word for a hidden mastermind",
  "twist-id": "Korean word for someone’s true identity",
  mask: "Korean word for a mask",
  disguise: "Korean word for a disguise",
  undercover: "Korean word for going undercover / infiltration",
  "double-life": "Korean word for a double life",
  amnesia: "Korean word for amnesia / memory loss",
  coma: "Korean word for a coma",
  illness: "Korean word for illness / disease",
  "hospital-room": "Korean word for a hospital room",
  operation: "Korean word for surgery",
  medicine: "Korean word for a medicine packet / bag of pills",
  life: "Korean word for a life (as in a life on the line)",
  death: "Korean word for death",
  funeral: "Korean word for a funeral",
  grave: "Korean word for a grave / cemetery",
  afterlife: "Korean word for the afterlife",
  soul: "Korean word for a soul / spirit",
  "fate-red": "Korean words for the red thread of fate",
  "destiny-meet": "Korean word for destined fate",
  coincidence: "Korean word for a coincidence",
  miracle: "Korean word for a miracle",
  luck: "Korean word for good luck",
  curse: "Korean word for a curse",
  blessing: "Korean word for a blessing",
  prayer: "Korean word for a prayer",
  temple: "Korean word for a mountain temple",
  church: "Korean word for a church",
  "school-gate": "Korean word for a school gate",
  classroom: "Korean word for a classroom",
  "rooftop-school": "Korean word for a rooftop classroom",
  "bus-stop": "Korean word for a bus stop",
  crosswalk: "Korean word for a crosswalk",
  convenience: "Korean word for a convenience store",
  pocha: "Hangul for a pocha / street food tent",
  nopo: "Korean word for a street stall",
  "high-rise": "Korean word for a high-rise / upper floors",
  basement: "Korean word for underground / a basement",
  "rooftop-bar": "Hangul spelling of “rooftop”",
  hotel: "Hangul spelling of “hotel”",
  airport: "Korean word for an airport",
  platform: "Korean word for a station platform",
  "ticket-gate": "Korean word for a ticket gate",
};

const SHOW_EN = {
  아는형님: "Knowing Bros",
  놀라운토요일: "Amazing Saturday",
  주간아이돌: "Weekly Idol",
  런닝맨: "Running Man",
  라디오스타: "Radio Star",
  라스타: "Radio Star",
  복면가왕: "King of Mask Singer",
  뮤직뱅크: "Music Bank",
  인기가요: "Inkigayo",
  음악중심: "Show! Music Core",
  엠카운트다운: "M Countdown",
  쇼챔피언: "Show Champion",
  쇼챔: "Show Champion",
  더쇼: "The Show",
  나혼자산다: "I Live Alone",
  무한도전: "Infinite Challenge",
  효리네민박: "Hyori's Homestay",
  퀸덤: "Queendom",
  로드투킹덤: "Road to Kingdom",
  킹덤: "Kingdom",
  쇼미더머니: "Show Me the Money",
  트와이스티비: "TWICE TV",
  방탄티비: "Bangtan TV",
  블랙핑크하우스: "BLACKPINK House",
  고잉세븐틴: "Going Seventeen",
  원더케이: "1theK",
  유퀴즈: "You Quiz on the Block",
  놀면뭐하니: "How Do You Play?",
  나가수: "I Am a Singer",
  불후의명곡: "Immortal Songs",
  히든싱어: "Hidden Singer",
  비긴어게인: "Begin Again",
  우리결혼했어요: "We Got Married",
  집사부일체: "Master in the House",
  무릎팍도사: "Knee-Drop Guru",
  유희열스케치북: "You Hee-yeol's Sketchbook",
  스케치북: "You Hee-yeol's Sketchbook",
  더시즌즈: "The Seasons",
  오늘의석진: "Jin’s “Today’s Seokjin”",
  슈취타: "Suchwita",
  아이유팔레트: "IU’s Palette",
  웬디영스트리트: "Wendy’s Young Street",
  푸른밤: "Blue Night",
  친한친구: "Close Friend Radio",
  화사쇼: "The Hwasa Show",
  우기네: "Yuqi’s show",
  인더숲: "In the Soop",
  본보야지: "Bon Voyage",
  어느멋진날: "One Fine Day",
  댄싱나인: "Dancing 9",
  드림하이: "Dream High",
  딩고: "Dingo",
  언프리티: "Unpretty Rapstar",
  아이돌학교: "Idol School",
  믹스앤매치: "Mix & Match",
  헬로베이비: "Hello Baby",
  신랑수업: "Newlywed School",
  영웅호걸: "Heroes",
  스타킹: "Star King",
  홍백: "Kohaku / Red and White",
  엑소의쇼타임: "EXO's Showtime",
  쇼타임: "Showtime",
  엑소래더: "EXO Ladder",
  엔시티라이프: "NCT Life",
  갓세븐의하드캐리: "GOT7’s Hard Carry",
  아이즈원츄: "IZ*ONE Chu",
  원더걸스쇼: "Wonder Girls Show",
  워너원고: "Wanna One Go",
  펜타곤메이커: "Pentagon Maker",
  뉴진스티비: "NewJeans TV",
  르세라핌티비: "LE SSERAFIM TV",
  에스파티비: "aespa TV",
  엔믹스티비: "NMIXX TV",
  있지로그: "ITZY LOG",
  에이티즈로그: "ATEEZ LOG",
  투바투티비: "TO DO / TXT TV",
  엔하이픈티비: "ENHYPEN TV",
  라이즈로그: "RIIZE LOG",
  아일릿로그: "ILLIT LOG",
  베이비몬스터티비: "BABYMONSTER TV",
  스테이씨로그: "STAYC LOG",
  케플러뷰: "Kep1er View",
  캠프제로베이스원: "Camp ZEROBASEONE",
  키오프레로그: "KIOF LOG",
  비엔디로그: "BND LOG",
  더보이즈로그: "THE BOYZ LOG",
  드림로그: "NCT DREAM LOG",
  스키즈코드: "SKZ CODE",
  트레저맵: "TREASURE MAP",
  몬채널: "Mon-Channel",
  빅뱅티비: "BIGBANG TV",
  투애니원티비: "2NE1 TV",
  레드벨벳티비: "Red Velvet TV",
  에프엑스티비: "f(x) TV",
  동방신기티비: "TVXQ TV",
  슈퍼티비: "Super Junior TV",
  빅스티비: "BTOB TV",
  위너티비: "WINNER TV",
  아이콘티비: "iKON TV",
  에이핑크뉴스: "Apink News",
  오마이걸로그: "OH MY GIRL LOG",
  포미닛티비: "4Minute TV",
  루나라디오: "LUNA Radio",
  쟈니라디오: "Johnny’s Radio",
  엔오클락: "N’O'Clock",
  플라이브: "FLIVE",
  멜로디데이: "Melody Day",
  랭킹킹: "Ranking King",
  더비기닝: "The Beginning",
  준비완료: "Ready",
  쪼꼬미: "JJOKOMI",
  탐구: "Inquiry / Explore",
  시그널: "Signal",
  넷플릭스: "Netflix",
  유튜브: "YouTube",
};

const PLACE_EN = {
  한강: "the Han River",
  한강공원: "Han River Park",
  한강교: "a Han River bridge",
  쌍문동: "Ssangmun-dong",
  남이섬: "Nami Island",
  이태원: "Itaewon",
  강남: "Gangnam",
  홍대: "Hongdae",
  홍대앞: "the area in front of Hongdae",
  명동: "Myeongdong",
  부산: "Busan",
  부산역: "Busan Station",
  인천: "Incheon",
  인천항: "Incheon Port",
  제주: "Jeju",
  제주도: "Jeju Island",
  서울: "Seoul",
  서울역: "Seoul Station",
  북한: "North Korea",
  남한: "South Korea",
  스위스: "Switzerland",
  캐나다: "Canada",
  이탈리아: "Italy",
  일본: "Japan",
  미국: "the United States",
  그리스: "Greece",
  베트남: "Vietnam",
  베를린: "Berlin",
  로마: "Rome",
  홍콩거리: "a Hong Kong street",
  무인도: "an uninhabited island",
  숙소: "the dorm / lodging",
  로비: "the lobby",
  계단: "the stairs",
  해변: "the beach",
  춘천: "Chuncheon",
  압구정: "Apgujeong",
  청담: "Cheongdam",
  한남동: "Hannam-dong",
  용산: "Yongsan",
  종로: "Jongno",
  신촌: "Sinchon",
  일산: "Ilsan",
  판교: "Pangyo",
  잠실: "Jamsil",
  목포: "Mokpo",
  포항: "Pohang",
  광주: "Gwangju",
  강원도: "Gangwon-do",
  양평: "Yangpyeong",
  창덕궁: "Changdeok Palace",
  한옥: "a hanok",
  한옥마을: "a hanok village",
  한양: "Hanyang (old Seoul)",
  한성: "Hanseong (old Seoul)",
  판문점: "Panmunjom",
  백두산: "Baekdu Mountain",
  공항: "an airport",
  병원: "a hospital",
  경찰서: "a police station",
  법정: "a courtroom",
  기숙사: "a dormitory",
  학교앞: "in front of the school",
  교실: "a classroom",
  교문: "a school gate",
  카페: "a cafe",
  아파트: "an apartment",
  시장: "a market",
  항구: "a harbor",
  옥상: "a rooftop",
  지하: "underground / a basement",
  회의실: "a meeting room",
};

const WORD_EN = {
  밀리언: "“million”",
  도쿄돔: "Tokyo Dome",
  월드투어: "“world tour”",
  빌보드: "Billboard",
  골든디스크: "the Golden Disc Awards",
  멜론어워드: "the Melon Music Awards",
  솔드아웃: "“sold out”",
  본상: "a bonsang (main award)",
  첫우승: "a first win / first trophy",
  신인상: "a rookie award",
  케이콘: "KCON",
  대상: "a daesang (grand prize)",
  코첼라: "Coachella",
  자작곡: "a self-written song",
  팬콘: "a fan concert",
  유닛: "a unit",
  멜론: "Melon",
  챌린지: "a challenge",
  월드: "“world”",
  틱톡: "TikTok",
  멜론대상: "a Melon daesang",
  기네스: "Guinness",
  한류스타: "a Hallyu star",
  발라드: "a ballad",
  안무: "choreography",
  바이럴: "“viral”",
  데뷔: "debut",
  올킬: "an all-kill (sweeping the charts)",
  그래미: "the Grammys",
  웸블리: "Wembley",
  타임지: "TIME magazine",
  유니세프: "UNICEF",
  스타디움: "a stadium",
  스포티파이: "Spotify",
  글로벌: "“global”",
  서울가요대상: "the Seoul Music Awards",
  깐부: "“kkambboo” (marble partners)",
  까꿍: "peekaboo (“kkakkung”)",
  우산: "umbrella",
  놀이: "a game / play",
  샤샤샤: "“sha sha sha” (the Cheer Up hook)",
};

const NAME_CLUE = {
  "bts:RM": "RM (Kim Namjoon) of BTS — Hangul given name",
  "bts:Jin": "Jin (Kim Seokjin) of BTS — Hangul given name",
  "bts:J-Hope": "J-Hope (Jung Hoseok) of BTS — Hangul given name",
  "bts:V": "V (Kim Taehyung) of BTS — Hangul given name",
  "stray-kids:HAN": "HAN (Han Jisung) of Stray Kids — Hangul full name",
  "got7:JB": "JB (Im Jaebeom) of GOT7 — Hangul given name",
  "the-boyz:New": "New (Choi Chanhee) of THE BOYZ — Hangul full name",
  "the-boyz:Q": "Q (Ji Changmin) of THE BOYZ — Hangul full name",
  "boynextdoor:Jaehyun": "Jaehyun (Myung Jaehyun) of BOYNEXTDOOR — Hangul full name",
};

module.exports = { kpop, drama, SHOW_EN, PLACE_EN, WORD_EN, NAME_CLUE };
