module.exports = [
  {
    key: "squid-game", name: "Squid Game", hangul: "오징어게임",
    blurb: "Deadly playground games, and a series that went global.",
    kind: "drama",
    people: [["Seong Gi-hun","기훈"],["Cho Sang-woo","상우"],["Kang Sae-byeok","새벽"],["Hwang Jun-ho","준호"],["Young-hee","영희"],["Oh Il-nam","일남"],["Jang Deok-su","덕수"],["Ali","알리"],["Front Man","프론트맨"]],
    actors: [["Lee Jung-jae","이정재"],["Park Hae-soo","박해수"],["Jung Ho-yeon","정호연"],["Wi Ha-jun","위하준"],["Oh Young-soo","오영수"]],
    extra: [["dalgona","The honeycomb candy contest","달고나"],["mugunghwa","Red Light, Green Light’s Korean flower","무궁화",2],["marble","The partner round with glass beads","구슬"],["tug","The team contest on a high platform","줄다리기",2],["bridge","The glass stepping-stone round","징검다리",3],["prize","The cash pile under glass","상금"],["player","Someone who entered the games","참가자",2],["out","Eliminated — a losing player’s fate","탈락"],["netflix","The platform that made it global","넷플릭스",2],["number","Gi-hun’s famous player number","사오육",2]],
  },
  {
    key: "winter-sonata", name: "Winter Sonata", hangul: "겨울연가",
    blurb: "The drama that sparked the first Korean Wave in Japan.",
    kind: "drama",
    people: [["Kang Jun-sang","준상"],["Jung Yu-jin","유진"],["Lee Min-hyung","민형"]],
    actors: [["Bae Yong-joon","배용준"],["Choi Ji-woo","최지우"]],
    extra: [["yonsama","Japan’s nickname for Bae Yong-joon","욘사마",2],["namisum","Island of the famous winter scenes","남이섬",2],["chuncheon","Gangwon city tied to the setting","춘천"],["snowman","A famous winter prop in the story","눈사람"],["piano","The instrument tied to lost memory","피아노",2],["first-snow","The snow that starts their story","첫눈"],["japan","Country where the drama exploded","일본"],["hallyu-start","The Korean Wave this helped start","한류"],["kbs","Broadcaster that aired it","케이비에스",3],["scarf","A winter accessory in the snow","목도리",2]],
  },
  {
    key: "parasite", name: "Parasite", hangul: "기생충",
    blurb: "One house, two families, and an Oscar-winning plan.",
    kind: "movie",
    people: [["Kim Ki-taek","기택"],["Kim Ki-woo","기우"],["Kim Ki-jung","기정"],["Chung-sook","충숙"],["Mr. Park","박사장"],["Yeon-kyo","연교"],["Geun-sae","근세"],["Moon-gwang","문광"]],
    actors: [["Song Kang-ho","송강호"],["Choi Woo-shik","최우식"],["Park So-dam","박소담"],["Lee Sun-kyun","이선균"],["Cho Yeo-jeong","조여정"],["Bong Joon-ho","봉준호"]],
    extra: [["basement","The Kims’ semi-underground home","반지하",2],["stairs","The house’s class metaphor","계단"],["stone","The scholar’s rock gifted to Ki-woo","수석"],["ramdon","The noodle dish, jjapaguri","짜파구리",3],["oscar","The award that made history","오스카",2],["peach","Fruit used to trigger an allergy","복숭아",2],["smell","What Mr. Park cannot stand","냄새"],["bunker","The secret room under the house","벙커"],["plan","The Kims’ elaborate scheme","계획"],["flood","What the rain does to the basement","침수"]],
  },
  {
    key: "cloy", name: "Crash Landing on You", hangul: "사랑의불시착",
    blurb: "A chaebol heir, a North Korean captain, and a crash into love.",
    kind: "drama",
    people: [["Ri Jeong-hyeok","리정혁"],["Yoon Se-ri","윤세리"],["Seo Dan","서단"],["Gu Seung-jun","구승준"],["Pyo Chi-su","표치수"]],
    actors: [["Hyun Bin","현빈"],["Son Ye-jin","손예진"],["Seo Ji-hye","서지혜"],["Kim Jung-hyun","김정현"]],
    extra: [["north","Where Se-ri crash-lands","북한"],["south","Where Se-ri’s company is based","남한"],["captain","Ri Jeong-hyeok’s rank","대위"],["paraglide","How Se-ri crosses the border by accident","패러글라이딩",3],["village","The North Korean town that hides her","마을"],["swiss","Country of a later reunion","스위스",2],["tvn","Channel that aired the drama","티빙"],["ost-love","The romance that defined 2019","로맨스",2],["seri-co","Se-ri’s Seoul company world","재벌"],["border","The line she was never meant to cross","분계선",2]],
  },
  {
    key: "goblin", name: "Goblin", hangul: "도깨비",
    blurb: "An immortal goblin, a grim reaper, and a house of shared fate.",
    kind: "drama",
    people: [["Kim Shin","김신"],["Ji Eun-tak","은탁"],["Wang Yeo","왕여"],["Kim Sun","김선"],["Sunny","써니"]],
    actors: [["Gong Yoo","공유"],["Kim Go-eun","김고은"],["Lee Dong-wook","이동욱"],["Yoo In-na","유인나"]],
    extra: [["sword","The blade stuck in the goblin’s chest","칼날"],["reaper","Wang Yeo’s job between life and death","저승사자",3],["chicken","The restaurant Sunny runs","치킨"],["canada","Where Eun-tak later studies","캐나다",2],["goblin-bride","Eun-tak’s fated role","신부"],["immortal","What Kim Shin has been for centuries","불멸"],["tvn","Channel that aired Goblin","티빙"],["ost-stay","A famous Goblin soundtrack mood","잔잔한",2],["house","The shared home of goblin and reaper","공유주택",3],["fate-string","The red thread between them","인연"]],
  },
  {
    key: "dots", name: "Descendants of the Sun", hangul: "태양의후예",
    blurb: "A soldier, a doctor, and a love story in a war zone.",
    kind: "drama",
    people: [["Yoo Shi-jin","유진"],["Kang Mo-yeon","모연"],["Seo Dae-young","대영"],["Yoon Myung-ju","명주"]],
    actors: [["Song Joong-ki","송중기"],["Song Hye-kyo","송혜교"],["Jin Goo","진구"],["Kim Ji-won","김지원"]],
    extra: [["soldier","Yoo Shi-jin’s job","군인"],["doctor","Kang Mo-yeon’s job","의사"],["uruk","The fictional country they serve in","우륵"],["peace","What the unit is sent to keep","평화"],["helmet","Part of Shi-jin’s uniform","헬멧"],["hospital-camp","Mo-yeon’s field clinic","야전병원",3],["kbs","Broadcaster of the drama","케이비에스",3],["couple","The Song-Song pairing","송송커플",3],["captain-yu","Shi-jin’s rank","대위"],["ring-promise","A promise across deployments","반지"]],
  },
  {
    key: "itaewon-class", name: "Itaewon Class", hangul: "이태원클라쓰",
    blurb: "A kicked-out student, a pub in Itaewon, and a long revenge.",
    kind: "drama",
    people: [["Park Sae-ro-yi","새로이"],["Jo Yi-seo","이서"],["Ma Hyun-yi","현이"],["Oh Soo-ah","수아"],["Jang Dae-hee","대희"]],
    actors: [["Park Seo-joon","박서준"],["Kim Da-mi","김다미"],["Kwon Nara","권나라"],["Yoo Jae-myung","유재명"]],
    extra: [["pub","The bar Sae-ro-yi builds","단밤",2],["itaewon","The Seoul neighborhood of the pub","이태원",2],["janga","The conglomerate he fights","장가"],["expel","Why Sae-ro-yi left school","퇴학"],["revenge","What he cooks for years","복수"],["manager","Yi-seo’s role in the pub","매니저",2],["netflix","Where the world watched it","넷플릭스",2],["soju","Drinks poured in the pub","소주"],["friendship","The staff who become family","의리"],["night","When Itaewon really wakes up","밤거리",2]],
  },
  {
    key: "vincenzo", name: "Vincenzo", hangul: "빈센조",
    blurb: "A Korean-Italian mafia lawyer, a gold-stuffed Geumga Plaza.",
    kind: "drama",
    people: [["Vincenzo Cassano","빈센조"],["Hong Cha-young","차영"],["Jang Jun-woo","준우"],["Cho Young-woon","영운"]],
    actors: [["Song Joong-ki","송중기"],["Jeon Yeo-been","전여빈"],["Ok Taecyeon","옥택연"],["Kwak Dong-yeon","곽동연"]],
    extra: [["mafia","Vincenzo’s Italian family business","마피아",2],["lawyer","Cha-young’s job","변호사",2],["plaza","The building he protects","금가플라자",3],["gold","What is hidden in the plaza","금괴"],["babel","The conglomerate he fights","바벨"],["italy","Country that shaped Vincenzo","이탈리아",3],["tvn","Channel that aired it","티빙"],["pigeon","A bird motif around Vincenzo","비둘기",2],["cassano","His Italian family name, in Hangul","카사노",2],["soot","The messy office Cha-young runs","법률사무소",3]],
  },
  {
    key: "cha-cha-cha", name: "Hometown Cha-Cha-Cha", hangul: "갯마을차차차",
    blurb: "A dentist in a seaside town, and the handyman who knows everyone.",
    kind: "drama",
    people: [["Yoon Hye-jin","혜진"],["Hong Du-sik","두식"],["Ji Seong-hyun","성현"],["Pyo Mi-seon","미선"]],
    actors: [["Shin Min-a","신민아"],["Kim Seon-ho","김선호"],["Lee Sang-yi","이상이"]],
    extra: [["gongjin","The seaside village of the story","공진"],["dentist","Hye-jin’s job","치과의사",3],["handyman","Du-sik’s unofficial job","만능해결사",3],["sea","What surrounds Gongjin","바다"],["clinic","Hye-jin’s new office","치과"],["chief","Du-sik’s nickname in town","이장"],["tvn","Channel that aired it","티빙"],["young-guk","A younger villager’s crush era","청춘"],["market","Where town gossip starts","시장"],["boat","How some villagers make a living","배편"]],
  },
  {
    key: "attorney-woo", name: "Extraordinary Attorney Woo", hangul: "이상한변호사우영우",
    blurb: "A brilliant rookie lawyer, whales, and a different way of seeing.",
    kind: "drama",
    people: [["Woo Young-woo","영우"],["Lee Jun-ho","준호"],["Jung Myung-seok","명석"],["Dong Geu-ra-mi","그라미"]],
    actors: [["Park Eun-bin","박은빈"],["Kang Tae-oh","강태오"],["Kang Ki-young","강기영"]],
    extra: [["whale","The animal Young-woo loves","고래"],["lawyer","Young-woo’s job","변호사",2],["autism","The way Young-woo’s mind works, in Korean news talk","자폐"],["hanbada","The law firm she joins","한바다"],["ramyeon","A snack often seen with her","라면"],["court","Where she argues cases","법정"],["ena","Channel that aired it","이엔에이",3],["gimbap","A lunch she might pack","김밥"],["genius","How colleagues first see her grades","천재"],["father","The man who raised her with kimbap shops","아버지",2]],
  },
  {
    key: "business-proposal", name: "Business Proposal", hangul: "사내맞선",
    blurb: "A fake blind date at work that turns into a real contract of hearts.",
    kind: "drama",
    people: [["Shin Ha-ri","하리"],["Kang Tae-mu","태무"],["Jin Young-seo","영서"],["Cha Sung-hoon","성훈"]],
    actors: [["Kim Se-jeong","김세정"],["Ahn Hyo-seop","안효섭"],["Seol In-ah","설인아"],["Kim Min-kyu","김민규"]],
    extra: [["date","The fake meeting that starts it","맞선"],["ceo","Tae-mu’s job at the company","대표"],["secretary","Sung-hoon’s role beside the CEO","비서"],["office","Where the romance hides","회사"],["friend","Young-seo, who asked for a stand-in","친구"],["sbs","Broadcaster of the drama","에스비에스",3],["webtoon","The original comic the drama adapts","웹툰"],["contract","A fake relationship on paper","계약"],["go-food","Ha-ri’s comfort after overtime","치킨"],["id-card","What lets her into the building","사원증",2]],
  },
  {
    key: "secretary-kim", name: "What's Wrong with Secretary Kim", hangul: "김비서가왜그럴까",
    blurb: "A narcissistic vice chairman and the secretary who plans to quit.",
    kind: "drama",
    people: [["Lee Young-joon","영준"],["Kim Mi-so","미소"],["Yang Shi-on","시온"],["Kim Sung-yeon","성연"]],
    actors: [["Park Seo-joon","박서준"],["Park Min-young","박민영"],["Lee Tae-hwan","이태환"]],
    extra: [["secretary","Mi-so’s job for years","비서"],["vice","Young-joon’s company rank","부회장",2],["quit","What Mi-so announces","퇴사"],["narcissist","Young-joon’s personality joke","나르시시스트",3],["brother","A family secret between men","형제"],["tvn","Channel that aired it","티빙"],["coffee","What a secretary is always pouring","커피"],["schedule","Mi-so’s weapon of choice","일정"],["rose","A flower Young-joon keeps sending","장미"],["smile","Mi-so’s given name means this","미소"]],
  },
  {
    key: "sky-castle", name: "Sky Castle", hangul: "스카이캐슬",
    blurb: "Elite parents, a mysterious coordinator, and exam-war Seoul.",
    kind: "drama",
    people: [["Han Seo-jin","서진"],["Lee Kang-joon","강준"],["Kim Joo-young","주영"],["Cha Min-hyuk","민혁"]],
    actors: [["Yeom Jung-ah","염정아"],["Lee Tae-ran","이태란"],["Kim Seo-hyung","김서형"],["Yoon Se-ah","윤세아"]],
    extra: [["exam","The war these families fight","입시"],["tutor","The coordinator who promises SKY schools","코디네이터",3],["sky","Seoul’s top three universities nickname","스카이"],["mansion","The hillside houses they live in","저택"],["parent","Who will do anything for a score","부모"],["jtbc","Channel that aired it","제이티비씨",3],["pressure","What the children carry","압박"],["secret-tutor","Joo-young’s underground service","과외"],["suicide","The tragedy that opens the story","비극"],["english","A subject the kids are drilled in","영어"]],
  },
  {
    key: "reply-1988", name: "Reply 1988", hangul: "응답하라1988",
    blurb: "Five families in a Ssangmun-dong alley, and a love revealed last.",
    kind: "drama",
    people: [["Sung Deok-sun","덕선"],["Choi Taek","택"],["Kim Jung-hwan","정환"],["Sung Dong-il","동일"],["Sun-woo","선우"]],
    actors: [["Lee Hye-ri","이혜리"],["Park Bo-gum","박보검"],["Ryu Jun-yeol","류준열"],["Sung Dong-il","성동일"],["Lee Il-hwa","이일화"]],
    extra: [["ssangmun","The neighborhood alley of the story","쌍문동",2],["baduk","Taek’s genius game","바둑"],["alley","Where the five houses sit","골목"],["family-house","Crowded rooms of 1988","안방"],["baseball","Jung-hwan’s other obsession","야구"],["tvn","Channel that aired it","티빙"],["ramyeon","A late-night kitchen snack","라면"],["tape","Mixtapes passed between kids","카세트",2],["mother","The women who run the alley","어머니",2],["first-snow","Winter in Ssangmun-dong","첫눈"]],
  },
  {
    key: "hospital-playlist", name: "Hospital Playlist", hangul: "슬기로운의사생활",
    blurb: "Five doctors, one band, and the long friendship of ‘99.",
    kind: "drama",
    people: [["Lee Ik-jun","익준"],["Ahn Jeong-won","정원"],["Kim Jun-wan","준완"],["Yang Seok-hyeong","석형"],["Chae Song-hwa","송화"]],
    actors: [["Jo Jung-suk","조정석"],["Yoo Yeon-seok","유연석"],["Jung Kyung-ho","정경호"],["Kim Dae-myung","김대명"],["Jeon Mi-do","전미도"]],
    extra: [["band","The five still play music together","밴드"],["hospital","Yulje Medical Center","병원"],["professor","Their rank at the hospital","교수"],["songhwa","The neurosurgeon of the five","송화"],["cd","The music they grew up on","씨디"],["tvn","Channel that aired it","티빙"],["friend99","The year they entered school together","구구년",2],["surgery","What they do between songs","수술"],["night-shift","When the hospital is quietest","당직"],["chicken","Ik-jun’s favorite order","치킨"]],
  },
  {
    key: "kingdom", name: "Kingdom", hangul: "킹덤",
    blurb: "A Joseon prince, a mysterious plague, and the undead at the gates.",
    kind: "drama",
    people: [["Crown Prince","세자"],["Seo-bi","서비"],["Yeong-shin","영신"],["Queen","중전"]],
    actors: [["Ju Ji-hoon","주지훈"],["Bae Doona","배두나"],["Kim Sung-kyu","김성규"],["Ryu Seung-ryong","류승룡"]],
    extra: [["zombie","The plague’s hungry dead","좀비"],["joseon","The dynasty of the story","조선"],["netflix","The platform that made Kingdom","넷플릭스",2],["palace","Where the conspiracy starts","왕궁"],["resurrection-plant","The plant tied to the plague","생사초",2],["prince","The heir hunting the truth","왕세자",2],["winter-hunt","A cold campaign against the dead","겨울"],["blood","What the infected crave","핏빛"],["armor","What soldiers wear on the wall","갑옷"],["throne","What the queen’s clan wants","왕좌"]],
  },
  {
    key: "the-glory", name: "The Glory", hangul: "더글로리",
    blurb: "A bullied student, a long plan, and a teacher’s revenge.",
    kind: "drama",
    people: [["Moon Dong-eun","동은"],["Park Yeon-jin","연진"],["Joo Yeo-jeong","여정"],["Jeon Jae-jun","재준"]],
    actors: [["Song Hye-kyo","송혜교"],["Lim Ji-yeon","임지연"],["Lee Do-hyun","이도현"],["Park Sung-hoon","박성훈"]],
    extra: [["bully","What Yeon-jin was in school","일진"],["revenge","Dong-eun’s life’s work","복수"],["teacher","The job Dong-eun uses as cover","선생님",2],["iron","A scar burned into a child’s skin","다리미",2],["netflix","The platform that carried it","넷플릭스",2],["makeup","Yeon-jin’s later public face","화장"],["chess","How Dong-eun thinks several moves ahead","체스"],["school","Where the violence started","학교"],["friend","Allies who help the plan","동료"],["truth","What Dong-eun wants on record","진실"]],
  },
  {
    key: "my-love-star", name: "My Love from the Star", hangul: "별에서온그대",
    blurb: "An alien who landed in Joseon, and a top actress in Seoul.",
    kind: "drama",
    people: [["Do Min-joon","민준"],["Cheon Song-yi","송이"],["Lee Hwi-kyung","휘경"],["Yoo Seol","유설"]],
    actors: [["Kim Soo-hyun","김수현"],["Jun Ji-hyun","전지현"],["Park Hae-jin","박해진"]],
    extra: [["alien","What Min-joon really is","외계인",2],["actress","Song-yi’s job","배우"],["chicken","The late-night food craze it sparked","치맥"],["joseon","When he first arrived","조선"],["star","Where he came from","별"],["sbs","Broadcaster of the drama","에스비에스",3],["freeze","His power when he is angry","순간이동",3],["manager","Song-yi’s busy career team","매니저",2],["roof","Where he watches the city","옥상"],["four-hundred","How long he has waited","사백년",2]],
  },
  {
    key: "boys-over-flowers", name: "Boys Over Flowers", hangul: "꽃보다남자",
    blurb: "A poor girl, the F4, and a high school of wild wealth.",
    kind: "drama",
    people: [["Geum Jan-di","잔디"],["Gu Jun-pyo","준표"],["Yoon Ji-hoo","지후"],["So Yi-jung","이정"],["Song Woo-bin","우빈"]],
    actors: [["Ku Hye-sun","구혜선"],["Lee Min-ho","이민호"],["Kim Hyun-joong","김현중"],["Kim Bum","김범"],["Kim Joon","김준"]],
    extra: [["f4","The four rich boys who rule school","에프포"],["shinhwa","The elite high school","신화고"],["greenhouse","Jun-pyo’s glass world","온실"],["red-card","A punishment the F4 issue","레드카드",3],["poor","Jan-di’s family situation","가난"],["kbs","Broadcaster of the drama","케이비에스",3],["manga","The Japanese comic it adapts","만화"],["rose","A flower in Jun-pyo’s world","장미"],["roof-kiss","A famous high-place scene","옥상"],["guardian","Ji-hoo’s quiet way of caring","보호"]],
  },
  {
    key: "signal", name: "Signal", hangul: "시그널",
    blurb: "A walkie-talkie across time, and detectives catching old crimes.",
    kind: "drama",
    people: [["Park Hae-young","해영"],["Cha Soo-hyun","수현"],["Lee Jae-han","재한"]],
    actors: [["Lee Je-hoon","이제훈"],["Kim Hye-soo","김혜수"],["Cho Jin-woong","조진웅"]],
    extra: [["radio","The device that talks to the past","무전기",2],["detective","All three leads’ job","형사"],["cold-case","Crimes that were never solved","미제사건",3],["profile","Hae-young’s analysis work","프로파일러",3],["tvn","Channel that aired it","티빙"],["past","Where Jae-han still lives","과거"],["future","Where Hae-young answers","미래"],["badge","What the cops carry","배지"],["night-rain","The mood of many Signal scenes","밤비"],["justice","What they still want for victims","정의"]],
  },
  {
    key: "its-okay", name: "It's Okay to Not Be Okay", hangul: "사이코지만괜찮아",
    blurb: "A children’s-book writer, a caregiver, and a hospital for minds.",
    kind: "drama",
    people: [["Moon Gang-tae","강태"],["Ko Moon-young","문영"],["Moon Sang-tae","상태"],["Lee Sang-in","상인"]],
    actors: [["Kim Soo-hyun","김수현"],["Seo Yea-ji","서예지"],["Oh Jung-se","오정세"]],
    extra: [["book","Moon-young writes children’s stories","동화"],["caregiver","Gang-tae’s job","보호사",2],["hospital-mind","OK Psychiatric Hospital","정신병원",3],["brother","Sang-tae, who Gang-tae protects","형"],["fairy","The dark tales Moon-young tells","동화작가",3],["tvn","Channel that aired it","티빙"],["castle","A house that looks like a storybook","성"],["trauma","What every patient carries","상처"],["ok","The hospital’s short name","오케이",2],["paint","Sang-tae’s way of speaking","그림"]],
  },
  {
    key: "twenty-five", name: "Twenty-Five Twenty-One", hangul: "스물다섯스물하나",
    blurb: "A fencer, a young reporter, and a coming-of-age in the IMF years.",
    kind: "drama",
    people: [["Na Hee-do","희도"],["Baek Yi-jin","이진"],["Go Yu-rim","유림"],["Ji Seung-wan","승완"]],
    actors: [["Kim Tae-ri","김태리"],["Nam Joo-hyuk","남주혁"],["Bona","김보라"]],
    extra: [["fencing","Hee-do’s sport","펜싱"],["reporter","Yi-jin’s later job","기자"],["imf","The crisis years of the story","아이엠에프",3],["coach","Who trains the fencing team","코치"],["tvn","Channel that aired it","티빙"],["diary","How the adult Hee-do looks back","일기"],["gold","What a fencer wants at nationals","금메달",2],["youth","The age in the title","청춘"],["friend-seungwan","Hee-do’s loud best friend","친구"],["radio","Yi-jin’s other job era","라디오",2]],
  },
  {
    key: "hotel-del-luna", name: "Hotel Del Luna", hangul: "호텔델루나",
    blurb: "A hotel for ghosts, a cursed CEO, and a moon that never sets.",
    kind: "drama",
    people: [["Jang Man-wol","만월"],["Gu Chan-sung","찬성"],["Gildal","길달"],["Seol-ji","설지"]],
    actors: [["IU","아이유"],["Yeo Jin-goo","여진구"],["P.O","피오"]],
    extra: [["hotel","A inn for the dead","호텔"],["ghost","The usual guests","귀신"],["moon","Man-wol’s name means full moon","만월"],["ceo","Chan-sung’s new job","사장"],["tvn","Channel that aired it","티빙"],["blue","The hotel’s night color","푸른밤",2],["curse","What binds Man-wol to the inn","저주"],["check-in","What every spirit must do","체크인",2],["key","What opens a guest’s room","열쇠"],["afterlife","Where unfinished souls stay","저승"]],
  },
  {
    key: "alchemy", name: "Alchemy of Souls", hangul: "환혼",
    blurb: "Soul-shifting mages, a fallen noble, and a maid who is more.",
    kind: "drama",
    people: [["Jang Uk","장욱"],["Mu-deok","무덕"],["Naksu","낙수"],["Park Dang-gu","당구"],["Seo Yul","서율"]],
    actors: [["Lee Jae-wook","이재욱"],["Jung So-min","정소민"],["Go Youn-jung","고윤정"],["Hwang Min-hyun","황민현"]],
    extra: [["mage","A fighter who uses energy","술사"],["soul","What can be switched between bodies","환혼"],["sword","Uk’s other weapon","검"],["maid","Mu-deok’s cover in the house","하녀"],["tvn","Channel that aired it","티빙"],["ice-stone","A power source in the lore","얼음정",2],["songrim","A great mage house","송림"],["assassin","What Naksu was trained as","암살자",2],["noble","Uk’s fallen family rank","귀족"],["season-two","A later chapter of the tale","파트투",2]],
  },
  {
    key: "queen-of-tears", name: "Queen of Tears", hangul: "눈물의여왕",
    blurb: "A chaebol queen, a lawyer husband, and a marriage on the brink.",
    kind: "drama",
    people: [["Hong Hae-in","해인"],["Baek Hyun-woo","현우"],["Yoon Eun-sung","은성"],["Hong Beom-jun","범준"]],
    actors: [["Kim Soo-hyun","김수현"],["Kim Ji-won","김지원"],["Park Sung-hoon","박성훈"]],
    extra: [["queen","Hae-in’s place in the department store family","여왕"],["lawyer","Hyun-woo’s job","변호사",2],["store","The Queens Group empire","백화점",2],["marriage","What they are trying to save","결혼"],["tvn","Channel that aired it","티빙"],["illness","A diagnosis that changes everything","병"],["village","Hyun-woo’s hometown Yongdu-ri","용두리",2],["tears","The word in the title","눈물"],["chair","The family seat everyone wants","회장"],["germany","Where Hyun-woo once studied","독일"]],
  },
  {
    key: "lovely-runner", name: "Lovely Runner", hangul: "선재업고튀어",
    blurb: "A fan, a star, a time slip, and a chance to save him.",
    kind: "drama",
    people: [["Im Sol","솔"],["Ryu Sun-jae","선재"],["Kim Tae-sung","태성"],["Lee Hyung-tae","형태"]],
    actors: [["Byeon Woo-seok","변우석"],["Kim Hye-yoon","김혜윤"],["Song Geon-hee","송건희"]],
    extra: [["timeslip","How Sol goes back to high school","타임슬립",3],["idol-star","Sun-jae’s job in the present","아이돌"],["fan","What Sol was first","팬클럽",2],["tvn","Channel that aired it","티빙"],["highschool","Where they meet again in the past","고등학교",3],["song-ost","A ballad every fan streamed","선재노래",2],["death","The future Sol wants to stop","죽음"],["diary","Clues from another timeline","일기"],["run","The second half of the Korean title","튀어"],["sunny","Sun-jae’s given-name feel","선재"]],
  },
  {
    key: "dae-jang-geum", name: "Jewel in the Palace", hangul: "대장금",
    blurb: "A Joseon kitchen girl who becomes the king’s physician.",
    kind: "drama",
    people: [["Jang-geum","장금"],["Min Jeong-ho","정호"],["Lady Han","한씨"],["King","임금"]],
    actors: [["Lee Young-ae","이영애"],["Ji Jin-hee","지진희"],["Yang Mi-kyung","양미경"]],
    extra: [["kitchen","The royal kitchen, sooraggan","수라간",2],["cook","Jang-geum’s first craft","요리"],["doctor","The craft she later wins","의녀"],["joseon","The dynasty of the story","조선"],["palace","Where she serves","궁궐"],["mbc","Broadcaster of the drama","엠비씨"],["taste","How she reads a dish","미각"],["herb","What a palace doctor studies","약초"],["king-meal","A royal table she prepares","수라"],["hallyu-old","An early global Korean Wave hit","한류"]],
  },
  {
    key: "mr-sunshine", name: "Mr. Sunshine", hangul: "미스터션샤인",
    blurb: "A Korean-born US marine, a noblewoman, and the fall of an era.",
    kind: "drama",
    people: [["Choi Yu-jin","유진"],["Go Ae-shin","애신"],["Kim Hui-seong","희성"],["Kudo","구도"]],
    actors: [["Lee Byung-hun","이병헌"],["Kim Tae-ri","김태리"],["Yoo Yeon-seok","유연석"],["Kim Min-jung","김민정"]],
    extra: [["marine","Yu-jin’s American rank","해병"],["noble","Ae-shin’s class","양반"],["joseon-end","The dying years of the dynasty","조선"],["tvn","Channel that aired it","티빙"],["gun","What the righteous army takes up","총기"],["hanok","Ae-shin’s family house","한옥"],["english-name","The title the city gives him","션샤인",2],["independence","What the fighters want","독립"],["photograph","A modern hobby of the era","사진"],["foreign","The powers circling Joseon","열강"]],
  },
  {
    key: "moving", name: "Moving", hangul: "무빙",
    blurb: "Parents with superpowers, children in hiding, and a school roof.",
    kind: "drama",
    people: [["Kim Bong-seok","봉석"],["Jang Hui-soo","희수"],["Lee Jae-man","재만"],["Lee Mi-hyun","미현"]],
    actors: [["Ryu Seung-ryong","류승룡"],["Han Hyo-joo","한효주"],["Zo In-sung","조인성"],["Lee Jung-ha","이정하"],["Go Yoon-jung","고윤정"]],
    extra: [["power","What the parents secretly have","능력"],["fly","Bong-seok’s gift","비행"],["school","Where the kids try to be normal","학교"],["disney","A platform that carried Moving","디즈니",2],["agent","The people hunting them","요원"],["roof","A famous fight above the gym","옥상"],["webtoon","The comic the series adapts","웹툰"],["hide","What the families have done for years","은신"],["strength","Hui-soo’s gift","힘"],["north","A past across the border","북한"]],
  },
  {
    key: "all-of-us", name: "All of Us Are Dead", hangul: "지금우리학교는",
    blurb: "A high school on lockdown, and a virus in the halls.",
    kind: "drama",
    people: [["Lee Cheong-san","청산"],["Nam On-jo","온조"],["Lee Su-hyeok","수혁"],["Choi Nam-ra","남라"]],
    actors: [["Park Ji-hu","박지후"],["Yoon Chan-young","윤찬영"],["Cho Yi-hyun","조이현"],["Lomon","로몬"]],
    extra: [["zombie","The infected students","좀비"],["school","Where they are trapped","학교"],["netflix","The platform that carried it","넷플릭스",2],["rooftop","A last open place to breathe","옥상"],["broadcast-club","Where they try to call for help","방송실",2],["science","The lab that started the virus","과학실",2],["uniform","What every student still wears","교복"],["window","How they watch the ground below","창문"],["group","The classmates who stick together","친구"],["alarm","The bell that no longer means class","벨"]],
  },
  {
    key: "weak-hero", name: "Weak Hero Class 1", hangul: "약한영웅",
    blurb: "A quiet transfer student, a notebook, and schoolyard wars.",
    kind: "drama",
    people: [["Yeon Si-eun","시은"],["Ahn Su-ho","수호"],["Oh Beom-seok","범석"],["Jeon Young-bin","영빈"]],
    actors: [["Park Ji-hoon","박지훈"],["Choi Hyun-wook","최현욱"],["Hong Kyung","홍경"]],
    extra: [["bully","The kids who run the school","일진"],["genius","Si-eun’s weapon is his brain","천재"],["notebook","Where he plans every fight","공책"],["wavve","A platform that carried it","웨이브",2],["fist","What Su-ho uses to protect him","주먹"],["transfer","Si-eun’s new-school status","전학생",2],["webtoon","The comic the series adapts","웹툰"],["class","The classroom they try to survive","교실"],["friend-suho","The athlete who stands beside him","친구"],["exam-score","Si-eun’s other battlefield","성적"]],
  },
  {
    key: "train-to-busan", name: "Train to Busan", hangul: "부산행",
    blurb: "A father, a daughter, and a KTX full of the infected.",
    kind: "movie",
    people: [["Seok-woo","석우"],["Soo-an","수안"],["Sang-hwa","상화"],["Seong-kyeong","성경"]],
    actors: [["Gong Yoo","공유"],["Ma Dong-seok","마동석"],["Jung Yu-mi","정유미"],["Kim Su-an","김수안"],["Yeon Sang-ho","연상호"]],
    extra: [["train","The KTX they cannot leave","기차"],["busan","The city they are racing toward","부산"],["zombie","The infected in the cars","좀비"],["daughter","Who Seok-woo is trying to reach","딸아이",2],["baseball","Sang-hwa’s loud fandom","야구"],["door","What they barricade between cars","문"],["conductor","Crew still trying to drive","기관사",2],["seoul","Where the outbreak is worse","서울"],["mask","An early symptom people miss","마스크",2],["end-car","The last safe carriage","칸막이",2]],
  },
  {
    key: "oldboy", name: "Oldboy", hangul: "올드보이",
    blurb: "Fifteen years in a room, a purple hammer, and a terrible truth.",
    kind: "movie",
    people: [["Oh Dae-su","대수"],["Lee Woo-jin","우진"],["Mi-do","미도"]],
    actors: [["Choi Min-sik","최민식"],["Yoo Ji-tae","유지태"],["Kang Hye-jung","강혜정"],["Park Chan-wook","박찬욱"]],
    extra: [["prison","The private room of 15 years","감금"],["hammer","Dae-su’s hallway weapon","해머"],["tooth","What he pulled in the dark","이빨"],["live-octopus","A famous restaurant scene","산낙지",2],["corridor","The one-take fight","복도"],["hypnosis","How memories were bent","최면"],["vengeance","The trilogy this belongs to","복수"],["school","The old sin that started it","학교"],["diary","Years marked on a wall","달력"],["secret-love","The truth he was not meant to know","비밀"]],
  },
  {
    key: "handmaiden", name: "The Handmaiden", hangul: "아가씨",
    blurb: "A pickpocket maid, a Japanese heiress, and a house of tricks.",
    kind: "movie",
    people: [["Sook-hee","숙희"],["Hideko","히데코"],["Count Fujiwara","후지와라"],["Uncle Kouzuki","코즈키"]],
    actors: [["Kim Tae-ri","김태리"],["Kim Min-hee","김민희"],["Ha Jung-woo","하정우"],["Cho Jin-woong","조진웅"],["Park Chan-wook","박찬욱"]],
    extra: [["maid","Sook-hee’s cover job","하녀"],["heiress","Hideko’s cage","아가씨",2],["library","The uncle’s forbidden rooms","서재"],["con","The fake count’s plan","사기"],["japan-era","The colonial setting","일제"],["love-two","What the two women choose","사랑"],["book","What the uncle collects","책"],["ink","Hideko’s forced readings","잉크"],["stairs","The mansion’s many levels","계단"],["plot-twist","The story told three times","반전"]],
  },
  {
    key: "memories-murder", name: "Memories of Murder", hangul: "살인의추억",
    blurb: "A 1980s serial case, two detectives, and a rain that never ends.",
    kind: "movie",
    people: [["Park Doo-man","두만"],["Seo Tae-yoon","태윤"],["Baek Kwang-ho","광호"]],
    actors: [["Song Kang-ho","송강호"],["Kim Sang-kyung","김상경"],["Bong Joon-ho","봉준호"]],
    extra: [["detective","Both leads’ job","형사"],["serial","The killer they cannot catch","연쇄살인",3],["rain","Weather tied to the murders","비오는날",2],["radio","A request song that becomes a clue","라디오",2],["field","The rural ditches of the case","논"],["document","Tae-yoon’s big-city methods","과학수사",3],["local","Doo-man’s small-town instinct","직감"],["hwaseong","The real city behind the story","화성"],["boots","A famous look into the camera","장화"],["unsolved","How the case felt for years","미제"]],
  },
  {
    key: "the-host", name: "The Host", hangul: "괴물",
    blurb: "A monster in the Han River, and a family that will not stop.",
    kind: "movie",
    people: [["Park Gang-du","강두"],["Hyun-seo","현서"],["Nam-il","남일"],["Nam-joo","남주"],["Hee-bong","희봉"]],
    actors: [["Song Kang-ho","송강호"],["Byun Hee-bong","변희봉"],["Park Hae-il","박해일"],["Bae Doona","배두나"],["Go Ah-sung","고아성"],["Bong Joon-ho","봉준호"]],
    extra: [["monster","The creature from the river","괴물"],["han-river","Where it first appears","한강"],["snack","The family’s riverside stall","매점"],["daughter","Who Gang-du has to find","딸아이",2],["chemical","What was dumped into the river","독극물",2],["tent","The quarantine camp","텐트"],["bow","Nam-joo’s sport","양궁"],["beer","Nam-il’s other talent","맥주"],["sewer","Where Hyun-seo hides","하수구",2],["family-park","The Parks against a creature","가족"]],
  },
  {
    key: "along-gods", name: "Along with the Gods", hangul: "신과함께",
    blurb: "After death, seven trials, and a firefighter’s last case.",
    kind: "movie",
    people: [["Kim Ja-hong","자홍"],["Gang-lim","강림"],["Hae-won-mak","해원맥"],["Lee Deok-choon","덕춘"]],
    actors: [["Ha Jung-woo","하정우"],["Cha Tae-hyun","차태현"],["Ju Ji-hoon","주지훈"],["Kim Hyang-gi","김향기"]],
    extra: [["afterlife","Where the trials take place","저승"],["trial","Seven tests after death","시련"],["firefighter","Ja-hong’s job in life","소방관",2],["god","The word in the title","신"],["reincarnation","The prize for passing","환생"],["hell","A realm they travel","지옥"],["webtoon","The comic the films adapt","웹툰"],["brother","A living sibling left behind","동생"],["judge","Who decides each trial","판관"],["part-two","The story continues in another film","속편"]],
  },
  {
    key: "miracle-cell", name: "Miracle in Cell No. 7", hangul: "7번방의선물",
    blurb: "A wrongfully jailed father, a little daughter, and cellmates with a plan.",
    kind: "movie",
    people: [["Lee Yong-gu","용구"],["Ye-sung","예승"],["So Yang-ho","양호"]],
    actors: [["Ryu Seung-ryong","류승룡"],["Park Shin-hye","박신혜"],["Kal So-won","갈소원"]],
    extra: [["prison","Where Yong-gu is sent","감옥"],["cell","The room in the title","일곱번방",3],["daughter","Ye-sung, who he adores","딸아이",2],["gift","The Korean word in the title","선물"],["wrong","The verdict that ruined him","억울"],["court","Where the truth is argued","법정"],["friend-inmates","The men who help smuggle her in","동료"],["letter","Messages between father and child","편지"],["tears-hit","A film famous for making Korea cry","감동"],["box","A present from cell number seven","상자"]],
  },
  {
    key: "my-sassy-girl", name: "My Sassy Girl", hangul: "엽기적인그녀",
    blurb: "A kind student, a fierce woman on a subway, and 2001’s rom-com.",
    kind: "movie",
    people: [["Gyeon-woo","견우"],["The Girl","그녀"]],
    actors: [["Cha Tae-hyun","차태현"],["Jun Ji-hyun","전지현"],["Kwak Jae-yong","곽재용"]],
    extra: [["subway","Where they first collide","지하철",2],["diary","Gyeon-woo’s narration","일기"],["sword","Her historical-drama daydreams","칼싸움",2],["sports","A field where he waits years later","운동장",2],["letter","What she leaves before disappearing","편지"],["drunk","How she first appears","만취"],["time","The years he keeps waiting","시간"],["romcom","The genre it defined","로맨스",2],["nickname","The Korean title’s “bizarre girl”","엽기",2],["train-meet","A later reunion on the tracks","기차"]],
  },
  {
    key: "decision-leave", name: "Decision to Leave", hangul: "헤어질결심",
    blurb: "A detective, a widow, and a mountain where the truth slips.",
    kind: "movie",
    people: [["Hae-joon","해준"],["Seo-rae","서래"]],
    actors: [["Park Hae-il","박해일"],["Tang Wei","탕웨이"],["Park Chan-wook","박찬욱"]],
    extra: [["detective","Hae-joon’s job","형사"],["widow","Seo-rae after the mountain death","미망인",2],["mountain","Where the husband fell","산"],["fog","Weather that hides the peak","안개"],["china","Seo-rae’s first language home","중국"],["watch","A detail that gives her away","시계"],["sea","A later posting by the water","바다"],["sleep","What the insomniac cop cannot do","불면"],["kiss","A choice that changes the case","입맞춤",2],["cannes-best","Park’s directing prize for this film","감독상",2]],
  },
  {
    key: "man-from-nowhere", name: "The Man from Nowhere", hangul: "아저씨",
    blurb: "A quiet pawnshop man, a neighbor girl, and a savage rescue.",
    kind: "movie",
    people: [["Cha Tae-sik","태식"],["So-mi","소미"],["Oh Myung-gyu","명규"]],
    actors: [["Won Bin","원빈"],["Kim Sae-ron","김새론"],["Kim Tae-hoon","김태훈"],["Lee Jeong-beom","이정범"]],
    extra: [["pawnshop","Tae-sik’s small business","전당포",2],["neighbor","So-mi from next door","이웃"],["chopstick","A famous kitchen-weapon scene","젓가락",2],["drug","The crime ring that takes her","마약"],["rescue","What Tae-sik will not stop doing","구출"],["past-agent","What Tae-sik used to be","요원"],["girl","The child he must bring home","아이"],["knife-fight","His quiet, brutal style","칼싸움",2],["busan-port","A shipment they chase","항구"],["silence","How Tae-sik usually speaks","침묵"]],
  },
  {
    key: "veteran", name: "Veteran", hangul: "베테랑",
    blurb: "A detective who hates chaebol brats, and a chase across Seoul.",
    kind: "movie",
    people: [["Seo Do-cheol","도철"],["Jo Tae-oh","태오"]],
    actors: [["Hwang Jung-min","황정민"],["Yoo Ah-in","유아인"],["Yoo Hae-jin","유해진"],["Ryoo Seung-wan","류승완"]],
    extra: [["detective","Do-cheol’s job","형사"],["chaebol-kid","Tae-oh’s spoiled world","재벌3세",3],["truck","A vehicle in a wild chase","트럭"],["police-unit","Do-cheol’s scrappy team","수사팀",2],["punch","How Do-cheol ends an argument","주먹"],["seoul-night","The city they tear through","서울"],["victim","The truck driver Tae-oh ruined","피해자",2],["badge","What Do-cheol still believes in","배지"],["laugh","A crime film that still grins","유머"],["roundup","Later films in the same spirit","범죄도시",3]],
  },
  {
    key: "extreme-job", name: "Extreme Job", hangul: "극한직업",
    blurb: "Undercover cops, a fried-chicken shop, and a sauce that goes viral.",
    kind: "movie",
    people: [["Go","고마반장"],["Young-ho","영호"],["Young-soo","영수"],["Jae-hoon","재훈"],["Dae-woong","대웅"]],
    actors: [["Lee Byung-hun","이병헌"],["Lee Hae-young","이하영"],["YunA","진선규"],["Song Ji-hyo","송지효"],["Lee Dong-hwi","이동휘"]],
    extra: [["chicken","The undercover shop’s product","치킨"],["sauce","The recipe that makes them famous","양념"],["drug","The case they were supposed to crack","마약"],["undercover","Their police tactic","잠입"],["shop","The chicken place they run","가게"],["hit-comedy","One of Korea’s biggest laugh hits","코미디",2],["chief","Go’s rank on the squad","반장"],["delivery","How the chicken leaves the shop","배달"],["raid","The bust they keep delaying","단속"],["franchise","What the sauce accidentally builds","프랜차이즈",3]],
  },
  {
    key: "jsa", name: "Joint Security Area", hangul: "공동경비구역",
    blurb: "A shooting in the DMZ, and a friendship that should not exist.",
    kind: "movie",
    people: [["Sophie Jean","소피"],["Lee Soo-hyuk","수혁"],["Oh Kyeong-pil","경필"],["Nam Sung-shik","성식"]],
    actors: [["Lee Young-ae","이영애"],["Lee Byung-hun","이병헌"],["Song Kang-ho","송강호"],["Park Chan-wook","박찬욱"]],
    extra: [["dmz","The border zone of the story","비무장지대",3],["soldier","Men on both sides of the line","군인"],["bridge","A crossing in the night","다리"],["swiss","Sophie’s other nationality","스위스",2],["north","Kyeong-pil’s side","북한"],["south","Soo-hyuk’s side","남한"],["gunshot","What starts the investigation","총성"],["neutral","Sophie’s job on the case","중립"],["letter","A hidden communication","편지"],["panmunjom","The village of the armistice","판문점",2]],
  },
  {
    key: "silenced", name: "Silenced", hangul: "도가니",
    blurb: "A new teacher, a school for the deaf, and a crime that must be heard.",
    kind: "movie",
    people: [["Kang In-ho","인호"],["Seo Yoo-jin","유진"],["Ja-young","자영"],["Min-soo","민수"]],
    actors: [["Gong Yoo","공유"],["Jung Yu-mi","정유미"],["Kim Hyun-soo","김현수"],["Hwang Dong-hyuk","황동혁"]],
    extra: [["school-deaf","Where In-ho comes to teach","농학교",2],["teacher","In-ho’s job","선생"],["sign","How the children speak","수화"],["abuse","The crime inside the school","학대"],["court","Where they try to be heard","법정"],["human-rights","What the film demanded","인권"],["gwangju","A city tied to the real case","광주"],["law","What fails the children first","법"],["voice","What the title says was taken","목소리",2],["protest","What the film helped start","고발"]],
  },
  {
    key: "burning", name: "Burning", hangul: "버닝",
    blurb: "A delivery driver, a vanished woman, and a greenhouse he may imagine.",
    kind: "movie",
    people: [["Lee Jong-su","종수"],["Shin Hae-mi","해미"],["Ben","벤"]],
    actors: [["Yoo Ah-in","유아인"],["Jeon Jong-seo","전종서"],["Steven Yeun","스티븐연",2],["Lee Chang-dong","이창동"]],
    extra: [["greenhouse","What Ben says he likes to burn","비닐하우스",3],["dance","Hae-mi at sunset near Paju","춤"],["well","A childhood story Hae-mi tells","우물"],["paju","Jong-su’s border-side home","파주"],["truck","How Jong-su makes a living","트럭"],["cat","Hae-mi’s pet that may not exist","고양이",2],["cannes","Where the film competed","칸영화제",3],["jealous","What Jong-su feels toward Ben","질투"],["fire","The act in the English title","불"],["vanish","What happens to Hae-mi","실종"]],
  },
  {
    key: "ode-father", name: "Ode to My Father", hangul: "국제시장",
    blurb: "A Busan market, a life of farewells, and Korea’s modern decades.",
    kind: "movie",
    people: [["Deok-soo","덕수"],["Young-ja","영자"],["Mak-soon","막순"]],
    actors: [["Hwang Jung-min","황정민"],["Kim Yun-jin","김윤진"],["Oh Dal-su","오달수"],["Yoon Je-kyoon","윤제균"]],
    extra: [["market","Busan’s Gukje Market","국제시장",3],["busan","The city of the family shop","부산"],["war","The childhood escape from Hungnam","전쟁"],["germany","Where Deok-soo goes to the mines","독일"],["vietnam","Another overseas chapter","베트남",2],["shop","The imported-goods stall","가게"],["father","The man lost at the docks","아버지",2],["sister","Who he promised to find","여동생",2],["hungnam","The evacuation of his childhood","흥남",2],["family-life","What he keeps sacrificing for","가족"]],
  },
  {
    key: "200-pounds", name: "200 Pounds Beauty", hangul: "미녀는괴로워",
    blurb: "A voice in the booth, a new face, and a love that has to hear her.",
    kind: "movie",
    people: [["Kang Han-na","한나"],["Ammy","에이미"],["Han Sang-jun","상준"]],
    actors: [["Kim Ah-jung","김아중"],["Joo Jin-mo","주진모"],["Kim Hyun-soo","성동일"]],
    extra: [["ghost-singer","Hanna’s first job in the booth","대본가수",3],["surgery","The change that makes Ammy","성형",2],["stage-name","Ammy’s public name","예명"],["song","A ballad she can finally own","노래"],["love","What she wants without the mask","사랑"],["weight","The English title’s first word","몸무게",2],["friend","Who knows the old Hanna","친구"],["concert","Where the truth may come out","콘서트",2],["radio","Another place her voice plays","라디오",2],["mirror","Where she meets the new face","거울"]],
  },
  {
    key: "peninsula", name: "Peninsula", hangul: "반도",
    blurb: "Years after the outbreak, a peninsula of warlords and a last job.",
    kind: "movie",
    people: [["Jung-seok","정석"],["Min-jung","민정"],["Chul-min","철민"],["Sergeant Hwang","황중사"]],
    actors: [["Gang Dong-won","강동원"],["Lee Jung-hyun","이정현"],["Lee Re","이레"],["Yeon Sang-ho","연상호"]],
    extra: [["zombie","The infected still hunting","좀비"],["truck","A vehicle built for the wasteland","트럭"],["incheon","A ruined city they re-enter","인천"],["unit-216","A survivor militia","부대"],["daughter","Min-jung’s children in the fight","아이"],["hongkong","Where Jung-seok has been hiding","홍콩"],["sequel","A follow-up to Train to Busan","속편"],["night-drive","How they cross dead highways","질주"],["captain","A warlord in the ruins","두목"],["busan-line","The first film they follow","부산행",2]],
  },
  {
    key: "new-world", name: "New World", hangul: "신세계",
    blurb: "An undercover cop in a crime syndicate, and a boss’s empty chair.",
    kind: "movie",
    people: [["Lee Ja-sung","자성"],["Jung Chung","정청"],["Lee Joong-gu","중구"]],
    actors: [["Lee Jung-jae","이정재"],["Choi Min-shin","최민식"],["Hwang Jung-min","황정민"],["Park Sung-woong","박성웅"]],
    extra: [["undercover","Ja-sung’s double life","잠입"],["mob","The Goldmoon syndicate","조직"],["boss","The empty chair everyone wants","보스"],["police","The handlers who own Ja-sung","경찰"],["blood-brother","Chung’s loyalty","의리"],["car","A famous tunnel-rage scene","자동차",2],["promotion","What the mob election decides","후계",2],["goldmoon","The company’s public face","골드문",2],["handler","Joong-gu’s police role","상관"],["smile","A final expression that hurts","미소"]],
  },
];
