module.exports = [
  {
    key: "twice", name: "TWICE", hangul: "트와이스",
    blurb: "Nine members, ONCE, and the hits that took them worldwide.",
    kind: "girl-group", fandom: ["원스", "Official TWICE fandom name"],
    agency: ["제이와이피", "The agency that debuted TWICE", 3],
    count: ["아홉", "How many members TWICE has"],
    members: [["Nayeon","나연"],["Jeongyeon","정연"],["Momo","모모"],["Sana","사나"],["Jihyo","지효"],["Mina","미나"],["Dahyun","다현"],["Chaeyoung","채영"],["Tzuyu","쯔위"]],
    songs: [["CHEER UP","치어업"],["TT","티티"],["Likey","라이키"],["FANCY","팬시"],["Feel Special","필스페셜"],["What is Love?","왓이즈러브"],["YES or YES","예스오어예스"],["The Feels","더피츠"],["SET ME FREE","셋미프리"],["STRATEGY","스트래티지"],["ONE SPARK","원스파크"],["Candy Pop","캔디팝"]],
    extra: [["candy-bong","TWICE’s candy-shaped light stick","캔디봉"],["sixteen","Mnet survival show that formed TWICE","식스틴",2]],
  },
  {
    key: "bts", name: "BTS", hangul: "방탄소년단",
    blurb: "Seven members, ARMY, and a name that means “bulletproof.”",
    kind: "boy-group", fandom: ["아미", "Official BTS fandom name"],
    agency: ["하이브", "The company that now houses BTS"],
    count: ["일곱", "How many members BTS has"],
    members: [["RM","남준"],["Jin","석진"],["Suga","슈가"],["J-Hope","호석"],["Jimin","지민"],["V","태형"],["Jungkook","정국"]],
    songs: [["Spring Day","봄날"],["DNA","디엔에이"],["IDOL","아이돌"],["Butter","버터"],["Dynamite","다이너마이트"],["FAKE LOVE","페이크러브"],["Blood Sweat & Tears","피땀눈물"],["MIC Drop","마이크드롭"],["Boy With Luv","작은것들을위한시"],["Yet To Come","옛투컴"],["Dope","쩔어"],["Boy In Luv","상남자"]],
    extra: [["bangtan","Short Korean nickname for BTS","방탄"],["army-bomb","Name of the BTS light stick","아미밤"],["bighit","The original BTS agency","빅히트",2]],
  },
  {
    key: "blackpink", name: "BLACKPINK", hangul: "블랙핑크",
    blurb: "Four members, BLINKs, and in-your-face title tracks.",
    kind: "girl-group", fandom: ["블링크", "Official BLACKPINK fandom name"],
    agency: ["와이지", "The agency that debuted BLACKPINK"],
    count: ["네명", "How many members BLACKPINK has"],
    members: [["Jisoo","지수"],["Jennie","제니"],["Rosé","로제"],["Lisa","리사"]],
    songs: [["Whistle","휘파람"],["Boombayah","붐바야"],["DDU-DU DDU-DU","뚜두뚜두"],["Kill This Love","킬디스러브"],["How You Like That","하우유라이크댓"],["Pink Venom","핑크베놈"],["Shut Down","셧다운"],["As If It’s Your Last","마지막처럼"],["Playing With Fire","불장난"],["Lovesick Girls","럽식걸스"],["Solo","솔로"],["APT.","아파트"]],
    extra: [["born-pink","2022 BLACKPINK album title","본핑크"],["the-album","2020 first full album title","더앨범"]],
  },
  {
    key: "newjeans", name: "NewJeans", hangul: "뉴진스",
    blurb: "Five members, Bunnies, and Y2K hooks from ADOR.",
    kind: "girl-group", fandom: ["버니즈", "Official NewJeans fandom name"],
    agency: ["어도어", "The ADOR label that debuted NewJeans", 2],
    count: ["다섯", "How many members NewJeans has"],
    members: [["Minji","민지"],["Hanni","하니"],["Danielle","다니엘"],["Haerin","해린"],["Hyein","혜인"]],
    songs: [["Attention","어텐션"],["Hype Boy","하입보이"],["Cookie","쿠키"],["Ditto","디토"],["OMG","오엠지"],["Super Shy","슈퍼샤이"],["ETA","이티에이"],["How Sweet","하우스위트"],["Right Now","라이트나우"],["GODS","갓즈"],["Cool With You","쿨위드유"],["ASAP","아삽"]],
    extra: [["bunny","The animal in the NewJeans fandom name","토끼"],["min-heejin","Producer who shaped the NewJeans image","민희진",2]],
  },
  {
    key: "stray-kids", name: "Stray Kids", hangul: "스트레이키즈",
    blurb: "Eight self-producing members, STAY, and 3RACHA.",
    kind: "boy-group", fandom: ["스테이", "Official Stray Kids fandom name"],
    agency: ["제이와이피", "The agency that debuted Stray Kids", 3],
    count: ["여덟", "How many members Stray Kids has"],
    members: [["Bang Chan","방찬"],["Lee Know","리노"],["Changbin","창빈"],["Hyunjin","현진"],["HAN","한지성"],["Felix","필릭스"],["Seungmin","승민"],["I.N","아이엔"]],
    songs: [["God's Menu","신메뉴"],["Back Door","백도어"],["Thunderous","소리꾼"],["Maniac","마니악"],["S-Class","특"],["LALALALA","라라라라"],["Chk Chk Boom","칙칙붐"],["MIROH","미로"],["Hellevator","헬리베이터"],["Case 143","케이스"],["JJAM","쨈"],["Giant","자이언트"]],
    extra: [["skz","Short nickname for Stray Kids","스키즈"],["three-racha","The in-house producing unit","쓰리라차",3],["skzoo","Stray Kids’ animal mascot line","스키주"]],
  },
  {
    key: "seventeen", name: "SEVENTEEN", hangul: "세븐틴",
    blurb: "Thirteen members, CARATs, and self-produced stages.",
    kind: "boy-group", fandom: ["캐럿", "Official SEVENTEEN fandom name"],
    agency: ["플레디스", "The Pledis label that debuted SEVENTEEN", 3],
    count: ["열셋", "How many members SEVENTEEN has"],
    members: [["S.Coups","에스쿱스"],["Jeonghan","정한"],["Joshua","조슈아"],["Jun","준휘"],["Hoshi","호시"],["Wonwoo","원우"],["Woozi","우지"],["DK","도겸"],["Mingyu","민규"],["The8","디에잇"],["Seungkwan","승관"],["Vernon","버논"],["Dino","디노"]],
    songs: [["Adore U","아낀다"],["Pretty U","예쁘다"],["Don't Wanna Cry","울고싶지않아"],["Clap","박수"],["Thanks","고맙다"],["Oh My!","어쩌나"],["Home","홈런"],["Left & Right","레프트앤라이트"],["Hot","핫"],["Super","슈퍼"],["God of Music","음악의신"],["Maestro","마에스트로"]],
    extra: [["svt","Short nickname for SEVENTEEN","세븐틴"],["caratbong","SEVENTEEN light stick nickname","캐럿봉",2]],
  },
  {
    key: "exo", name: "EXO", hangul: "엑소",
    blurb: "SM’s supernova boy group, EXO-L, and “Growl.”",
    kind: "boy-group", fandom: ["엑소엘", "Official EXO fandom name"],
    agency: ["에스엠", "The SM label that debuted EXO"],
    count: ["아홉", "EXO’s classic nine-member lineup"],
    members: [["Suho","수호"],["Xiumin","시우민"],["Baekhyun","백현"],["Chen","종대"],["Chanyeol","찬열"],["D.O.","디오"],["Kai","카이"],["Sehun","세훈"],["Lay","레이"]],
    songs: [["Growl","으르렁"],["Call Me Baby","콜미베이비"],["Love Me Right","러브미라이트"],["Monster","몬스터"],["Ko Ko Bop","코코밥"],["Tempo","템포"],["Love Shot","럽샷"],["Obsession","옵세션"],["Cream Soda","크림소다"],["The Eve","전야"]],
    extra: [["planet","EXO lore: they are from another","행성"],["exodus","2015 EXO album Exodus","엑소더스",3]],
  },
  {
    key: "aespa", name: "aespa", hangul: "에스파",
    blurb: "Four members, æ, and SM’s metaverse girl group.",
    kind: "girl-group", fandom: ["마이", "Official aespa fandom name, MY"],
    agency: ["에스엠", "The SM label that debuted aespa"],
    count: ["네명", "How many members aespa has"],
    members: [["Karina","카리나"],["Giselle","지젤"],["Winter","윈터"],["Ningning","닝닝"]],
    songs: [["Black Mamba","블랙맘바"],["Next Level","넥스트레벨"],["Savage","새비지"],["Girls","걸스"],["Spicy","스파이시"],["Drama","드라마"],["Supernova","슈퍼노바"],["Armageddon","아마겟돈"],["Whiplash","휘플래시"],["Illusion","도깨비불"]],
    extra: [["kwangya","The virtual world in aespa lore","광야"],["ae","The avatar half of an aespa member","애"]],
  },
  {
    key: "ive", name: "IVE", hangul: "아이브",
    blurb: "Six members, DIVE, and “ELEVEN” to “HEYA.”",
    kind: "girl-group", fandom: ["다이브", "Official IVE fandom name"],
    agency: ["스타쉽", "The Starship label that debuted IVE", 2],
    count: ["여섯", "How many members IVE has"],
    members: [["Yujin","유진"],["Gaeul","가을"],["Rei","레이"],["Wonyoung","원영"],["Liz","리즈"],["Leeseo","이서"]],
    songs: [["ELEVEN","일레븐"],["LOVE DIVE","러브다이브"],["After LIKE","애프터라이크"],["Kitsch","키치"],["I AM","아이엠"],["Baddie","배디"],["HEYA","해야"],["Accendio","아첸디오"],["Hype","하이프"],["REBEL HEART","레벨하트"]],
    extra: [["starship","IVE’s agency, said in English letters","스타쉽",2],["ive-name","The group name means “I have”","아이브"]],
  },
  {
    key: "le-sserafim", name: "LE SSERAFIM", hangul: "르세라핌",
    blurb: "Five members, FEARNNOT, and fearless title tracks.",
    kind: "girl-group", fandom: ["피어나", "Official LE SSERAFIM fandom name"],
    agency: ["쏘스뮤직", "The HYBE label that debuted LE SSERAFIM", 2],
    count: ["다섯", "How many members LE SSERAFIM has"],
    members: [["Sakura","사쿠라"],["Chaewon","채원"],["Yunjin","윤진"],["Kazuha","카즈하"],["Eunchae","은채"]],
    songs: [["FEARLESS","피어리스"],["ANTIFRAGILE","안티프래자일"],["UNFORGIVEN","언포기븐"],["EASY","이지"],["Smart","스마트"],["CRAZY","크레이지"],["Perfect Night","퍼펙트나잇"],["1-800-hot-n-fun","핫앤펀"],["FEARNOT","피어낫"],["Swan Song","스완송"]],
    extra: [["source","LE SSERAFIM’s HYBE label","쏘스뮤직",2],["fearless-word","The English word hidden in the group name","피어리스",2]],
  },
  {
    key: "gidle", name: "(G)I-DLE", hangul: "여자아이들",
    blurb: "Self-producing girl group, Neverland, and Soyeon’s pens.",
    kind: "girl-group", fandom: ["네버랜드", "Official (G)I-DLE fandom name", 3],
    agency: ["큐브", "The Cube label that debuted (G)I-DLE"],
    count: ["다섯", "How many members (G)I-DLE has now"],
    members: [["Miyeon","미연"],["Minnie","민니"],["Soyeon","소연"],["Yuqi","우기"],["Shuhua","슈화"]],
    songs: [["LATATA","라타타"],["HANN","한"],["Señorita","세뇨리타"],["Oh my god","오마이갓"],["TOMBOY","톰보이"],["Nxde","누드"],["Queencard","퀸카"],["Super Lady","슈퍼레이디"],["Klaxon","클락션"],["Wife","와이프"]],
    extra: [["cube","(G)I-DLE’s agency","큐브"],["soyeon-pd","Soyeon as in-house producer","프로듀서",3]],
  },
  {
    key: "red-velvet", name: "Red Velvet", hangul: "레드벨벳",
    blurb: "Five members, ReVeluv, and red-versus-velvet concepts.",
    kind: "girl-group", fandom: ["레베럽", "Official Red Velvet fandom name"],
    agency: ["에스엠", "The SM label that debuted Red Velvet"],
    count: ["다섯", "How many members Red Velvet has"],
    members: [["Irene","아이린"],["Seulgi","슬기"],["Wendy","웬디"],["Joy","조이"],["Yeri","예리"]],
    songs: [["Happiness","행복"],["Ice Cream Cake","아이스크림케이크"],["Dumb Dumb","덤덤"],["Russian Roulette","러시안룰렛"],["Red Flavor","빨간맛"],["Peek-A-Boo","피카부"],["Bad Boy","배드보이"],["Psycho","싸이코"],["Feel My Rhythm","필마이리듬"],["Cosmic","코스믹"]],
    extra: [["red-flavor","2017 summer title, Korean “red taste”","빨간맛"],["reveluv","Fan-name pronunciation in Hangul","레베럽"]],
  },
  {
    key: "itzy", name: "ITZY", hangul: "있지",
    blurb: "Five members, MIDZY, and “DALLA DALLA” confidence.",
    kind: "girl-group", fandom: ["미드지", "Official ITZY fandom name"],
    agency: ["제이와이피", "The agency that debuted ITZY", 3],
    count: ["다섯", "How many members ITZY has"],
    members: [["Yeji","예지"],["Lia","리아"],["Ryujin","류진"],["Chaeryeong","채령"],["Yuna","유나"]],
    songs: [["DALLA DALLA","달라달라"],["ICY","아이씨"],["WANNABE","워너비"],["Not Shy","낫샤이"],["LOCO","로코"],["SNEAKERS","스니커즈"],["CAKE","케이크"],["BORN TO BE","본투비"],["GOLD","골드"],["UNTOUCHABLE","언터처블"]],
    extra: [["midzy","ITZY fans, in Hangul","미드지"],["itzy-name","The group name means “you have it”","있지"]],
  },
  {
    key: "txt", name: "TXT", hangul: "투바투",
    blurb: "Five members, MOA, and HYBE’s next chapter after BTS.",
    kind: "boy-group", fandom: ["모아", "Official TXT fandom name"],
    agency: ["하이브", "The company that houses TXT"],
    count: ["다섯", "How many members TXT has"],
    members: [["Yeonjun","연준"],["Soobin","수빈"],["Beomgyu","범규"],["Taehyun","태현"],["Huening Kai","휴닝카이"]],
    songs: [["Crown","어느날머리에서뿔이"],["9 and Three Quarters","9와4분의3승강장"],["Can't You See Me?","세계가불타는밤"],["Blue Hour","블루아워"],["0X1=LOVESONG","엑스원"],["LO$ER=LO♡ER","루저러버"],["Good Boy Gone Bad","굿보이곤배드"],["Sugar Rush Ride","슈거러시라이드"],["Deja Vu","데자부"],["Overtime","오버타임"]],
    extra: [["moa","TXT fans: Moments of Alwaysness","모아"],["tomorrow","First word of TXT’s full English name","투모로우",2]],
  },
  {
    key: "enhypen", name: "ENHYPEN", hangul: "엔하이픈",
    blurb: "Seven members, ENGENE, born on I-LAND.",
    kind: "boy-group", fandom: ["엔진", "Official ENHYPEN fandom name"],
    agency: ["빌리프랩", "The Belift Lab label that debuted ENHYPEN", 3],
    count: ["일곱", "How many members ENHYPEN has"],
    members: [["Heeseung","희승"],["Jay","제이"],["Jake","제이크"],["Sunghoon","성훈"],["Sunoo","선우"],["Jungwon","정원"],["Ni-ki","니키"]],
    songs: [["Given-Taken","기븐테이큰"],["Drunk-Dazed","드렁크데이즈드"],["Tamed-Dashed","테임드대시드"],["Future Perfect","퓨처퍼펙트"],["Bite Me","바이트미"],["Sweet Venom","스위트베놈"],["XO","엑소"],["Brought The Heat Back","브롯더힛백"],["No Doubt","노다웃"],["Daydream","데이드림"]],
    extra: [["iland","Survival show that formed ENHYPEN","아일랜드",3],["engene","Fan-name pronunciation in Hangul","엔진"]],
  },
  {
    key: "ateez", name: "ATEEZ", hangul: "에이티즈",
    blurb: "Eight pirate-concept members, ATINY, from KQ.",
    kind: "boy-group", fandom: ["에이티니", "Official ATEEZ fandom name", 3],
    agency: ["케이큐", "The KQ label that debuted ATEEZ"],
    count: ["여덟", "How many members ATEEZ has"],
    members: [["Hongjoong","홍중"],["Seonghwa","성화"],["Yunho","윤호"],["Yeosang","여상"],["San","최산"],["Mingi","민기"],["Wooyoung","우영"],["Jongho","종호"]],
    songs: [["Pirate King","해적왕"],["Say My Name","세이마이네임"],["WAVE","웨이브"],["WONDERLAND","원더랜드"],["INCEPTION","인셉션"],["Fireworks","불놀이야"],["Guerrilla","게릴라"],["Bouncy","바운시"],["Crazy Form","크레이지폼"],["Work","워크"]],
    extra: [["atiny","ATEEZ fans, in Hangul","에이티니",3],["kq","ATEEZ’s agency","케이큐"]],
  },
  {
    key: "nct-127", name: "NCT 127", hangul: "엔시티",
    blurb: "NCT’s Seoul 127 team, NCTzens, and “Cherry Bomb.”",
    kind: "boy-group", fandom: ["엔시티즌", "Official NCT fandom name", 3],
    agency: ["에스엠", "The SM label that debuted NCT 127"],
    count: ["아홉", "A classic NCT 127 member count"],
    members: [["Taeil","태일"],["Johnny","쟈니"],["Taeyong","태용"],["Yuta","유타"],["Doyoung","도영"],["Jaehyun","재현"],["Jungwoo","정우"],["Mark","마크"],["Haechan","해찬"]],
    songs: [["Fire Truck","소방차"],["Cherry Bomb","체리밤"],["Regular","레귤러"],["Simon Says","사이먼세이즈"],["Kick It","영웅"],["Sticker","스티커"],["2 Baddies","질주"],["Fact Check","팩트체크"],["Walk","워크"],["Touch","터치"]],
    extra: [["nctzen","NCT fans, in Hangul","엔시티즌",3],["seoul-127","The 127 in the name is a Seoul code","서울"]],
  },
  {
    key: "nct-dream", name: "NCT Dream", hangul: "엔시티드림",
    blurb: "Seven Dreamies, youth concepts, and “Hot Sauce.”",
    kind: "boy-group", fandom: ["엔시티즌", "Official NCT fandom name", 3],
    agency: ["에스엠", "The SM label that debuted NCT Dream"],
    count: ["일곱", "How many members NCT Dream has"],
    members: [["Mark","마크"],["Renjun","런쥔"],["Jeno","제노"],["Haechan","해찬"],["Jaemin","재민"],["Chenle","천러"],["Jisung","지성"]],
    songs: [["Chewing Gum","츄잉검"],["My First and Last","마지막첫사랑"],["We Young","위영"],["GO","고"],["Hot Sauce","맛"],["Hello Future","헬로퓨처"],["Glitch Mode","버퍼링"],["Beatbox","비트박스"],["ISTJ","아이에스티제이"],["Smoothie","스무디"]],
    extra: [["dreamies","Nickname for NCT Dream members","드리미즈",3],["hotsauce","2021 title, Korean “flavor”","맛"]],
  },
  {
    key: "iu", name: "IU", hangul: "아이유",
    blurb: "Nation’s little sister, UAENA, and diary-like title tracks.",
    kind: "solo", fandom: ["유애나", "Official IU fandom name"],
    agency: ["이담", "IU’s EDAM Entertainment", 2],
    members: [["IU","아이유"],["Jieun","지은"]],
    songs: [["Good Day","좋은날"],["You & I","너랑나"],["Friday","금요일에만나요"],["Palette","팔레트"],["Twenty-Three","스물셋"],["BBIBBI","삐삐"],["eight","에잇"],["Blueming","블루밍"],["Lilac","라일락"],["Love Wins All","홀씨"],["Through the Night","밤편지"],["Celebrity","셀러브리티"]],
    extra: [["uaena","IU fans, in Hangul","유애나"],["jieun","IU’s real given name","이지은",2],["hotel-deluna","Drama where IU played Jang Man-wol","호텔델루나",3]],
  },
  {
    key: "psy", name: "PSY", hangul: "싸이",
    blurb: "Gangnam Style, viral horses, and a showman’s grin.",
    kind: "solo", fandom: ["싸이퍼", "A nickname PSY fans use"],
    agency: ["피네이션", "PSY’s P Nation label", 3],
    members: [["PSY","싸이"],["Jaesang","재상"]],
    songs: [["Gangnam Style","강남스타일"],["Gentleman","젠틀맨"],["Daddy","대디"],["Hangover","행오버"],["New Face","뉴페이스"],["That That","댓댓"],["Champion","챔피언"],["Right Now","라이트나우"],["Celeb","연예인"],["Naparima","나팔바지"]],
    extra: [["horse","The dance everyone copied in 2012","말춤"],["gangnam","Seoul district in PSY’s biggest hit","강남"],["pnation","PSY’s current label","피네이션",3]],
  },
  {
    key: "snsd", name: "Girls' Generation", hangul: "소녀시대",
    blurb: "The nine-member nation, SONE, and “Gee.”",
    kind: "girl-group", fandom: ["소원", "Official Girls’ Generation fandom name"],
    agency: ["에스엠", "The SM label that debuted Girls’ Generation"],
    count: ["아홉", "Classic Girls’ Generation member count"],
    members: [["Taeyeon","태연"],["Sunny","써니"],["Tiffany","티파니"],["Hyoyeon","효연"],["Yuri","유리"],["Sooyoung","수영"],["Yoona","윤아"],["Yuri2","유리"],["Seohyun","서현"],["Jessica","제시카"]],
    songs: [["Gee","지"],["Genie","소원을말해봐"],["Oh!","오"],["Run Devil Run","런데빌런"],["The Boys","더보이즈"],["I Got A Boy","아이가타보이"],["Lion Heart","라이온하트"],["Forever 1","포에버원"],["Into the New World","다시만난세계"],["Mr. Taxi","미스터택시"]],
    extra: [["sone","SNSD fans, in Hangul","소원"],["snsd","Short English nickname, in Hangul letters","소녀시대",3]],
  },
  {
    key: "bigbang", name: "BIGBANG", hangul: "빅뱅",
    blurb: "YG’s kings of the 2000s, VIPs, and “Fantastic Baby.”",
    kind: "boy-group", fandom: ["빕", "Official BIGBANG fandom name, VIP"],
    agency: ["와이지", "The YG label that debuted BIGBANG"],
    count: ["다섯", "Classic BIGBANG member count"],
    members: [["G-Dragon","지드래곤"],["T.O.P","탑"],["Taeyang","태양"],["Daesung","대성"],["Seungri","승리"]],
    songs: [["Lies","거짓말"],["Last Farewell","마지막인사"],["Day by Day","하루하루"],["Fantastic Baby","판타스틱베이비"],["Fantastic","판타스틱"],["Bang Bang Bang","뱅뱅뱅"],["Bae Bae","배배"],["FXXK IT","에라모르겠다"],["Haru Haru","하루하루"],["Sunset Glow","붉은노을"]],
    extra: [["vip","BIGBANG fans, in Hangul","빕"],["yg-family","The YG family BIGBANG led","와이지패밀리",3]],
  },
  {
    key: "shinee", name: "SHINee", hangul: "샤이니",
    blurb: "Five, then four, Shawols, and “Replay” to “Don't Call Me.”",
    kind: "boy-group", fandom: ["샤월", "Official SHINee fandom name"],
    agency: ["에스엠", "The SM label that debuted SHINee"],
    count: ["다섯", "Classic SHINee member count"],
    members: [["Onew","온유"],["Jonghyun","종현"],["Key","키"],["Minho","민호"],["Taemin","태민"]],
    songs: [["Replay","누난너무예뻐"],["Love Like Oxygen","산소같은너"],["Lucifer","루시퍼"],["Sherlock","셜록"],["View","뷰"],["Married to the Music","매리드투더뮤직"],["Everybody","에브리바디"],["Don't Call Me","돈콜미"],["Hard","하드"],["Ring Ding Dong","링딩동"]],
    extra: [["shawol","SHINee fans, in Hangul","샤월"],["shinee-world","Concert tour name SHINee World","샤이니월드",3]],
  },
  {
    key: "super-junior", name: "Super Junior", hangul: "슈퍼주니어",
    blurb: "SM’s large family, ELF, and “Sorry, Sorry.”",
    kind: "boy-group", fandom: ["엘프", "Official Super Junior fandom name"],
    agency: ["에스엠", "The SM label that debuted Super Junior"],
    count: ["열셋", "Super Junior’s famous large lineup"],
    members: [["Leeteuk","이특"],["Heechul","희철"],["Yesung","예성"],["Shindong","신동"],["Sungmin","성민"],["Eunhyuk","은혁"],["Donghae","동해"],["Siwon","시원"],["Ryeowook","려욱"],["Kyuhyun","규현"]],
    songs: [["U","유"],["Sorry Sorry","쏘리쏘리"],["Bonamana","미인아"],["Mr. Simple","미스터심플"],["Sexy, Free & Single","섹시프리앤싱글"],["Mamacita","마마시타"],["Black Suit","블랙수트"],["House Party","하우스파티"],["Show Time","쇼타임"],["Miracle","미라클"]],
    extra: [["elf","Super Junior fans, in Hangul","엘프"],["elf-name","ELF means Ever Lasting Friends","엘프"]],
  },
  {
    key: "two-ne1", name: "2NE1", hangul: "투애니원",
    blurb: "Four YG queens, Blackjacks, and “I Am the Best.”",
    kind: "girl-group", fandom: ["블랙잭", "Official 2NE1 fandom name"],
    agency: ["와이지", "The YG label that debuted 2NE1"],
    count: ["네명", "How many members 2NE1 has"],
    members: [["CL","씨엘"],["Park Bom","박봄"],["Park Sandara","산다라박"],["Minzy","공민지"]],
    songs: [["Fire","파이어"],["I Don't Care","아이돈케어"],["Go Away","고어웨이"],["Can't Nobody","캔노바디"],["I Am the Best","내가제일잘나가"],["Ugly","어글리"],["Come Back Home","컴백홈"],["Missing You","그리워해요"],["Try to Follow Me","날따라해봐요"],["In the Club","인더클럽"]],
    extra: [["blackjack","2NE1 fans, in Hangul","블랙잭"],["cl-leader","CL’s role in 2NE1","리더"]],
  },
  {
    key: "mamamoo", name: "MAMAMOO", hangul: "마마무",
    blurb: "Four vocalists, Moomoos, and “You’re the Best.”",
    kind: "girl-group", fandom: ["무무", "Official MAMAMOO fandom name"],
    agency: ["알비더블유", "The RBW label that debuted MAMAMOO", 3],
    count: ["네명", "How many members MAMAMOO has"],
    members: [["Solar","솔라"],["Moonbyul","문별"],["Wheein","휘인"],["Hwasa","화사"]],
    songs: [["Mr. Ambiguous","미스터모호함"],["Um Oh Ah Yeh","음오아예"],["You're the Best","넌is뭔들"],["Decalcomanie","데칼코마니"],["Yes I Am","나로말할것같으면"],["Starry Night","별이빛나는밤"],["Egotistic","너나해"],["HIP","힙"],["Where Are We Now","우린어디서"],["ILY","아이엘와이"]],
    extra: [["moomoo","MAMAMOO fans, in Hangul","무무"],["rbw","MAMAMOO’s agency","알비더블유",3]],
  },
  {
    key: "got7", name: "GOT7", hangul: "갓세븐",
    blurb: "Seven members, Ahgases, and “Hard Carry.”",
    kind: "boy-group", fandom: ["아가새", "Official GOT7 fandom name"],
    agency: ["제이와이피", "The agency that debuted GOT7", 3],
    count: ["일곱", "How many members GOT7 has"],
    members: [["JB","재범"],["Mark","마크"],["Jackson","잭슨"],["Jinyoung","진영"],["Youngjae","영재"],["BamBam","뱀뱀"],["Yugyeom","유겸"]],
    songs: [["Girls Girls Girls","걸스걸스걸스"],["A","에이"],["Just Right","딱좋아"],["If You Do","니가하면"],["Hard Carry","하드캐리"],["Never Ever","네버에버"],["You Are","유이얼"],["Look","룩"],["Lullaby","자장가"],["Nanana","나나나"]],
    extra: [["ahgase","GOT7 fans, in Hangul","아가새"],["igot7","Another way fans say the fandom","아이갓세븐",3]],
  },
  {
    key: "treasure", name: "TREASURE", hangul: "트레저",
    blurb: "YG’s next boy group, TEUME, and “BOY.”",
    kind: "boy-group", fandom: ["트레저메이커", "Official TREASURE fandom name", 3],
    agency: ["와이지", "The YG label that debuted TREASURE"],
    count: ["열명", "TREASURE’s ten-member lineup"],
    members: [["Choi Hyunsuk","최현석"],["Jihoon","지훈"],["Yoshi","요시"],["Junkyu","준규"],["Yoon Jaehyuk","재혁"],["Asahi","아사히"],["Doyoung","도영"],["Haruto","하루토"],["Park Jeongwoo","정우"],["So Junghwan","정환"]],
    songs: [["BOY","보이"],["I LOVE YOU","사랑해"],["MY TREASURE","마이트레저"],["JIKJIN","직진"],["DARARI","다라리"],["HELLO","헬로"],["BONA BONA","보나보나"],["B.O.M.B","밤"],["KING KONG","킹콩"],["LAST NIGHT","라스트나잇"]],
    extra: [["teume","Short nickname for TREASURE makers","티메"],["tmap","TREASURE Maker as a long fandom name","트레저메이커",3]],
  },
  {
    key: "zb1", name: "ZEROBASEONE", hangul: "제로베이스원",
    blurb: "Boys Planet winners, ZEROSE, and “In Bloom.”",
    kind: "boy-group", fandom: ["제로즈", "Official ZEROBASEONE fandom name"],
    agency: ["웨이크원", "The WakeOne label that debuted ZB1", 3],
    count: ["아홉", "How many members ZEROBASEONE has"],
    members: [["Sung Hanbin","성한빈"],["Kim Jiwoong","김지웅"],["Zhang Hao","장하오"],["Seok Matthew","석매튜"],["Kim Tae-rae","김태래"],["Ricky","리키"],["Kim Gyuvin","김규빈"],["Park Gunwook","박건욱"],["Han Yujin","한유진"]],
    songs: [["In Bloom","꽃피움"],["CRUSH","크러시"],["SWEAT","스웻"],["Feel the POP","필더팝"],["GOOD SO BAD","굿소배드"],["SOLAR","솔라"],["BLUE","블루"],["And I","앤아이"],["New Kidz on the Block","뉴키즈"],["Kill the Romeo","킬더로미오"]],
    extra: [["boys-planet","Survival show that formed ZB1","보이즈플래닛",3],["zerose","ZB1 fans, in Hangul","제로즈"]],
  },
  {
    key: "riize", name: "RIIZE", hangul: "라이즈",
    blurb: "SM’s new boy group, BRIIZE, and “Get A Guitar.”",
    kind: "boy-group", fandom: ["브리즈", "Official RIIZE fandom name"],
    agency: ["에스엠", "The SM label that debuted RIIZE"],
    count: ["여섯", "RIIZE’s six-member lineup"],
    members: [["Shotaro","쇼타로"],["Eunseok","은석"],["Sungchan","성찬"],["Wonbin","원빈"],["Sohee","소희"],["Anton","앤톤"]],
    songs: [["Get A Guitar","겟어기타"],["Talk Saxy","톡색시"],["Love 119","러브119"],["Impossible","임파서블"],["Boom Boom Bass","붐붐베이스"],["Combo","콤보"],["Hug","허그"],["Siren","사이렌"],["9 Days","나인데이즈"],["Lucky","럭키"]],
    extra: [["briize","RIIZE fans, in Hangul","브리즈"],["guitar","Object in the debut title","기타"]],
  },
  {
    key: "babymonster", name: "BABYMONSTER", hangul: "베이비몬스터",
    blurb: "YG’s next girl group, MONSTIEZ, and “Batter Up.”",
    kind: "girl-group", fandom: ["몬스티즈", "Official BABYMONSTER fandom name", 2],
    agency: ["와이지", "The YG label that debuted BABYMONSTER"],
    count: ["일곱", "How many members BABYMONSTER has"],
    members: [["Ruka","루카"],["Pharita","파리타"],["Asa","아사"],["Ahyeon","아현"],["Rami","라미"],["Rora","로라"],["Chiquita","치키타"]],
    songs: [["Batter Up","배터업"],["Stuck In The Middle","스턱인더미들"],["SHEESH","쉬쉬"],["FOREVER","포에버"],["CLIK CLAK","클릭클락"],["Like That","라이크댓"],["DRIP","드립"],["Woke Up In Tokyo","워크업인도쿄"],["BILLIONAIRE","빌리어네어"],["PSYCHO","싸이코"]],
    extra: [["monstiez","BABYMONSTER fans, in Hangul","몬스티즈",2],["baemon","Short nickname for BABYMONSTER","베몬"]],
  },
  {
    key: "illit", name: "ILLIT", hangul: "아일릿",
    blurb: "R U Next? winners, GLLIT, and “Magnetic.”",
    kind: "girl-group", fandom: ["글릿", "Official ILLIT fandom name"],
    agency: ["빌리프랩", "The Belift Lab label that debuted ILLIT", 3],
    count: ["다섯", "How many members ILLIT has"],
    members: [["Yunah","윤아"],["Minju","민주"],["Moka","모카"],["Wonhee","원희"],["Iroha","이로하"]],
    songs: [["Magnetic","마그네틱"],["Lucky Girl Syndrome","럭키걸신드롬"],["Cherish","체리쉬"],["I'll Like You","아일라이크유"],["Tick-Tack","틱택"],["Almond Chocolate","아몬드초콜릿"],["Do the Dance","두더댄스"],["Jellyous","젤리어스"],["Baby It's Okay","베이비잇오케이"],["IYKYK","아이야케이야케"]],
    extra: [["gllit","ILLIT fans, in Hangul","글릿"],["ru-next","Survival show that formed ILLIT","알유넥스트",3]],
  },
  {
    key: "nmixx", name: "NMIXX", hangul: "엔믹스",
    blurb: "JYP’s mixx pop girl group, NSWERS, and “O.O.”",
    kind: "girl-group", fandom: ["엔쓰워즈", "Official NMIXX fandom name", 3],
    agency: ["제이와이피", "The agency that debuted NMIXX", 3],
    count: ["여섯", "How many members NMIXX has now"],
    members: [["Lily","릴리"],["Haewon","해원"],["Sullyoon","설윤"],["Bae","배이"],["Jiwoo","지우"],["Kyujin","규진"]],
    songs: [["O.O","오오"],["DICE","다이스"],["Love Me Like This","러브미라이크디스"],["Party O'Clock","파티오클락"],["Dash","대쉬"],["See that?","별별별"],["Know About Me","노우어바웃미"],["High Horse","하이호스"],["SICKUHH","시크"],["Run for Roses","런포로지스"]],
    extra: [["nswers","NMIXX fans, in Hangul","엔쓰워즈",3],["mixxpop","NMIXX’s stated genre nickname","믹스팝",2]],
  },
  {
    key: "stayc", name: "STAYC", hangul: "스테이씨",
    blurb: "Six High Up girls, SWITH, and “ASAP.”",
    kind: "girl-group", fandom: ["스윗", "Official STAYC fandom name"],
    agency: ["하이업", "The High Up label that debuted STAYC"],
    count: ["여섯", "How many members STAYC has"],
    members: [["Sumin","수민"],["Sieun","시은"],["Isa","아이사"],["Seeun","세은"],["Yoon","윤"],["J","재이"]],
    songs: [["SO BAD","쏘배드"],["ASAP","아삽"],["Stereotype","색안경"],["RUN2U","런투유"],["BEAUTIFUL MONSTER","뷰티풀몬스터"],["Teddy Bear","테디베어"],["Bubble","버블"],["Cheeky Icy Thang","치키아이시탱"],["GPT","지피티"],["BEBE","베베"]],
    extra: [["swith","STAYC fans, in Hangul","스윗"],["highup","STAYC’s agency","하이업"]],
  },
  {
    key: "the-boyz", name: "THE BOYZ", hangul: "더보이즈",
    blurb: "Eleven members, THE B, and “The Stealer.”",
    kind: "boy-group", fandom: ["더비", "Official THE BOYZ fandom name"],
    agency: ["아이에스티", "IST Entertainment, home of THE BOYZ", 3],
    count: ["열한", "THE BOYZ’s eleven-member lineup"],
    members: [["Sangyeon","상연"],["Jacob","제이콥"],["Younghoon","영훈"],["Hyunjae","현재"],["Juyeon","주연"],["Kevin","케빈"],["New","최찬희"],["Q","지창민"],["Haknyeon","학년"],["Sunwoo","선우"],["Eric","에릭"]],
    songs: [["Boy","소년"],["No Air","노에어"],["The Stealer","더스틸러"],["Reveal","리빌"],["Christmassy","크리스마시"],["Maverick","매버릭"],["Roar","로어"],["WATCH IT","와칫"],["Nectar","넥타"],["Lip Gloss","립글로스"]],
    extra: [["theb","THE BOYZ fans, in Hangul","더비"],["ist","THE BOYZ’s agency","아이에스티",3]],
  },
  {
    key: "monsta-x", name: "MONSTA X", hangul: "몬스타엑스",
    blurb: "Starship’s powerful boy group, Monbebe, and “Hero.”",
    kind: "boy-group", fandom: ["몬베베", "Official MONSTA X fandom name"],
    agency: ["스타쉽", "The Starship label that debuted MONSTA X", 2],
    count: ["여섯", "MONSTA X’s later six-member lineup"],
    members: [["Shownu","셔누"],["Minhyuk","민혁"],["Kihyun","기현"],["Hyungwon","형원"],["Joohoney","주헌"],["I.M","아이엠"]],
    songs: [["Trespass","무단침입"],["Hero","히어로"],["Beautiful","뷰티풀"],["Shine Forever","샤인포에버"],["Dramarama","드라마라마"],["Shoot Out","슛아웃"],["Alligator","앨리게이터"],["Follow","팔로우"],["Love Killa","러브킬라"],["Beautiful Liar","뷰티풀라이어"]],
    extra: [["monbebe","MONSTA X fans, in Hangul","몬베베"],["noman","Survival show that formed MONSTA X","노머시",2]],
  },
  {
    key: "winner", name: "WINNER", hangul: "위너",
    blurb: "YG’s WIN:Who Is Next victors, Inner Circle, and “Really Really.”",
    kind: "boy-group", fandom: ["이너서클", "Official WINNER fandom name", 3],
    agency: ["와이지", "The YG label that debuted WINNER"],
    count: ["네명", "WINNER’s later four-member lineup"],
    members: [["Yoon","강승윤"],["Jinwoo","김진우"],["Seunghoon","이승훈"],["Mino","송민호"]],
    songs: [["Empty","공허해"],["Color Ring","컬러링"],["Sentimental","센치해"],["Really Really","릴리릴리"],["Love Me Love Me","러브미러브미"],["Everyday","에브리데이"],["Millions","밀리언즈"],["AH YEAH","아예"],["Soso","소소"],["HOLD","홀드"]],
    extra: [["inner-circle","WINNER fans, in Hangul","이너서클",3],["win-show","Survival show in the group’s name","후이즈넥스트",3]],
  },
  {
    key: "ikon", name: "iKON", hangul: "아이콘",
    blurb: "YG’s MIX & MATCH team, iKONICs, and “Love Scenario.”",
    kind: "boy-group", fandom: ["아이코닉", "Official iKON fandom name", 2],
    agency: ["와이지", "The YG label that debuted iKON"],
    count: ["여섯", "iKON’s later six-member lineup"],
    members: [["Jay","김진환"],["Bobby","바비"],["DK","김동혁"],["Ju-ne","구준회"],["Chan","송윤형"],["Yunhyeong","김동욱"]],
    songs: [["My Type","취향저격"],["Rhythm Ta","리듬타"],["Love Scenario","사랑을했다"],["Killing Me","죽겠다"],["Goodbye Road","이별길"],["I'm OK","아임오케이"],["Dive","다이브"],["But You","하지만니가"],["Tantara","탄타라"],["Bling Bling","블링블링"]],
    extra: [["ikonic","iKON fans, in Hangul","아이코닉",2],["love-scenario","2018 hit, Korean “I loved”","사랑을했다",3]],
  },
  {
    key: "two-pm", name: "2PM", hangul: "투피엠",
    blurb: "JYP’s beast-dol six, Hottest, and “Heartbeat.”",
    kind: "boy-group", fandom: ["핫티스트", "Official 2PM fandom name", 3],
    agency: ["제이와이피", "The agency that debuted 2PM", 3],
    count: ["여섯", "2PM’s six-member lineup"],
    members: [["Jun. K","준케이"],["Nichkhun","닉쿤"],["Taecyeon","택연"],["Wooyoung","우영"],["Junho","준호"],["Chansung","찬성"]],
    songs: [["10 Out of 10","10점만점에10점"],["Again & Again","어게인앤어게인"],["Heartbeat","하트비트"],["I'll Be Back","아윌비백"],["Hands Up","핸즈업"],["Thank You","고맙습니다"],["GO CRAZY!","미친거아니야"],["My House","우리집"],["Promise","약속"],["Make It","메이킷"]],
    extra: [["hottest","2PM fans, in Hangul","핫티스트",3],["beastdol","2PM’s tough-concept nickname","비스트돌",3]],
  },
  {
    key: "tvxq", name: "TVXQ", hangul: "동방신기",
    blurb: "SM’s rising gods, Cassiopeia, and “Mirotic.”",
    kind: "boy-group", fandom: ["카시오페아", "Official TVXQ fandom name", 3],
    agency: ["에스엠", "The SM label that debuted TVXQ"],
    count: ["다섯", "TVXQ’s original five-member lineup"],
    members: [["U-Know","유노윤호"],["Max","최강창민"],["Hero","영웅재중"],["Micky","믹키유천"],["Xiah","시아준수"]],
    songs: [["Hug"," Hug"],["Hug2","허그"],["Rising Sun","라이징선"],["Mirotic","주문"],["Keep Your Head Down","왜"],["Android","안드로이드"],["Something","썸씽"],["Spellbound","최면"],["The Chance of Love","운명"],["Truth","진실"]],
    extra: [["cassiopeia","TVXQ fans, in Hangul","카시오페아",3],["dbsk","Korean name meaning rising gods of the east","동방신기",3]],
  },
  {
    key: "boa", name: "BoA", hangul: "보아",
    blurb: "SM’s queen of K-pop, a bilingual star since her teens.",
    kind: "solo", fandom: ["소울", "A name BoA fans often use"],
    agency: ["에스엠", "The SM label that debuted BoA"],
    members: [["BoA","보아"],["KwonBoa","권보아"]],
    songs: [["ID; Peace B","아이디피스비"],["No.1","넘버원"],["Atlantis Princess","아틀란티스소녀"],["My Name","마이네임"],["Girls On Top","걸스온탑"],["Eat You Up","이트유업"],["Only One","온리원"],["Hurricane Venus","허리케인비너스"],["Copy & Paste","카피앤페이스트"],["Negpyeo","Negpyeo"]],
    extra: [["kwon","BoA’s family name","권보아",2],["japan-promo","Country where BoA also became a huge star","일본"],["no1","2002 title track","넘버원"]],
  },
  {
    key: "taeyeon", name: "Taeyeon", hangul: "태연",
    blurb: "SNSD’s main vocal, a soloist of “I” and “INVU.”",
    kind: "solo", fandom: ["소원", "Girls’ Generation — and Taeyeon — fans"],
    agency: ["에스엠", "The SM label that houses Taeyeon"],
    members: [["Taeyeon","태연"],["KimTaeyeon","김태연"]],
    songs: [["I","아이"],["Rain","레인"],["11:11","열한시십일분"],["Fine","파인"],["Make Me Love You","메이크미러브유"],["Four Seasons","사계"],["Spark","불티"],["INVU","인뷰"],["Weekend","위켄드"],["To. X","투엑스"]],
    extra: [["invu","2022 title track","인뷰"],["snsd-leader","Taeyeon’s role in Girls’ Generation","리더"],["sone","The fandom she still shares","소원"]],
  },
  {
    key: "g-dragon", name: "G-Dragon", hangul: "지드래곤",
    blurb: "BIGBANG’s leader, a designer-idol who wrote the era.",
    kind: "solo", fandom: ["지디팬", "A nickname for G-Dragon fans"],
    agency: ["갤럭시코퍼레이션", "G-Dragon’s later label home", 3],
    members: [["G-Dragon","지드래곤"],["Jiyong","지용"]],
    songs: [["Heartbreaker","하트브레이커"],["Crooked","삐딱하게"],["Who You?","니생각"],["Untitled, 2014","무제"],["That XX","그XX"],["Palette","팔레트"],["POWER","파워"],["HOME SWEET HOME","홈스위트홈"],["TOO BAD","투배드"],["Coup D'etat","쿠데타"]],
    extra: [["jiyong","G-Dragon’s real given name","권지용",2],["peaceminusone","G-Dragon’s fashion label","피스마이너스원",3],["bigbang-gd","The group G-Dragon led","빅뱅"]],
  },
  {
    key: "hyuna", name: "HyunA", hangul: "현아",
    blurb: "4Minute’s firecracker, “Bubble Pop,” and solo stages.",
    kind: "solo", fandom: ["현아피아", "A nickname HyunA fans use", 3],
    agency: ["피네이션", "HyunA’s P Nation chapter", 3],
    members: [["HyunA","현아"],["YooHyunA","유현아"]],
    songs: [["Change","체인지"],["Bubble Pop","버블팝"],["Ice Cream","아이스크림"],["Red","빨개요"],["How's This?","어때"],["Babe","베베"],["Lip & Hip","립앤힙"],["Flower Shower","플라워샤워"],["I'm Not Cool","아임낫쿨"],["Nabillera","나빌레라"]],
    extra: [["fourminute","The girl group HyunA debuted in","포미닛",2],["bubble-pop","2011 signature solo title","버블팝"],["pnation","Label she later joined with PSY","피네이션",3]],
  },
  {
    key: "oh-my-girl", name: "OH MY GIRL", hangul: "오마이걸",
    blurb: "Fairytale stages, Miracle, and “Dolphin” / “Dun Dun Dance.”",
    kind: "girl-group", fandom: ["미라클", "Official OH MY GIRL fandom name", 2],
    agency: ["더블유엠", "The WM label that debuted OH MY GIRL", 2],
    count: ["일곱", "A classic OH MY GIRL member count"],
    members: [["Hyojung","효정"],["Mimi","미미"],["YooA","유아"],["Seunghee","승희"],["Jiho","지호"],["Binnie","비니"],["Arin","아린"]],
    songs: [["Cupid","큐피드"],["Liar Liar","라이어라이어"],["Closer","클로저"],["Secret Garden","비밀정원"],["The Fifth Season","다섯번째계절"],["Nonstop","살짝설렜어"],["Dolphin","돌핀"],["Dun Dun Dance","던던댄스"],["Dear you","디어유"],["Classified","클래시파이드"]],
    extra: [["miracle","OH MY GIRL fans, in Hangul","미라클",2],["dolphin","2020 viral B-side","돌핀"]],
  },
  {
    key: "apink", name: "Apink", hangul: "에이핑크",
    blurb: "Pink innocence, Pandas, and “NoNoNo” to “Dumhdurum.”",
    kind: "girl-group", fandom: ["팬다", "Official Apink fandom name"],
    agency: ["아이에스티", "IST, later home of Apink", 3],
    count: ["여섯", "A classic Apink member count"],
    members: [["Chorong","초롱"],["Bomi","보미"],["Eunji","은지"],["Naeun","나은"],["Namjoo","남주"],["Hayoung","하영"]],
    songs: [["NoNoNo","노노노"],["Mr. Chu","미스터츄"],["Luv","러브"],["NoNoNo2","노노노"],["I'm So Sick","1도없어"],["%%","응응"],["Dumhdurum","덤더럼"],["Everybody Ready?","에브리바디레디"],["Dilemma","딜레마"],["I Want You To Be Happy","행복했으면좋겠어"]],
    extra: [["panda","Apink fans, in Hangul","팬다"],["chorong-leader","Chorong’s role in Apink","리더"]],
  },
  {
    key: "fx", name: "f(x)", hangul: "에프엑스",
    blurb: "SM’s experimental five, MeU, and “Electric Shock.”",
    kind: "girl-group", fandom: ["미유", "Official f(x) fandom name"],
    agency: ["에스엠", "The SM label that debuted f(x)"],
    count: ["다섯", "Classic f(x) member count"],
    members: [["Victoria","빅토리아"],["Amber","엠버"],["Luna","루나"],["Krystal","크리스탈"],["Sulli","설리"]],
    songs: [["LA chA TA","라차타"],["Chu","츄"],["Electric Shock","일렉트릭쇼크"],["Hot Summer","핫썸머"],["Red Light","레드라이트"],["4 Walls","포월스"],["Rum Pum Pum Pum","첫사랑니"],["Airplane","에어플레인"],["Nu ABO","누에이비오"],["Pinocchio","피노키오"]],
    extra: [["meu","f(x) fans, in Hangul","미유"],["electric","2012 title track","일렉트릭쇼크",3]],
  },
  {
    key: "wonder-girls", name: "Wonder Girls", hangul: "원더걸스",
    blurb: "JYP’s “Tell Me” rewind, Wonderfuls, and a US crossover.",
    kind: "girl-group", fandom: ["원더풀", "Official Wonder Girls fandom name", 2],
    agency: ["제이와이피", "The agency that debuted Wonder Girls", 3],
    count: ["다섯", "A classic Wonder Girls member count"],
    members: [["Yeeun","예은"],["Sohee","소희"],["Sunmi","선미"],["Yubin","유빈"],["Hyelim","혜림"],["Sunye","선예"]],
    songs: [["Irony","아이러니"],["Tell Me","텔미"],["So Hot","쏘핫"],["Nobody","노바디"],["2 Different Tears","두다른눈물"],["Be My Baby","비마이베이비"],["Like Money","라이크머니"],["I Feel You","아이필유"],["Why So Lonely","와이소리니"],["Rewind","리와인드"]],
    extra: [["tellme","The 2007 dance everyone copied","텔미"],["nobody","US crossover title","노바디"]],
  },
  {
    key: "kiss-of-life", name: "KISS OF LIFE", hangul: "키스오브라이프",
    blurb: "Four members, Kissy, and “Shhh” to “Midas Touch.”",
    kind: "girl-group", fandom: ["키씨", "Official KISS OF LIFE fandom name"],
    agency: ["에스케이온", "S2 Entertainment, home of KISS OF LIFE", 3],
    count: ["네명", "How many members KISS OF LIFE has"],
    members: [["Julie","쥴리"],["Natty","나띠"],["Belle","벨"],["Haneul","하늘"]],
    songs: [["Shhh","쉿"],["Bad News","배드뉴스"],["Nobody Knows","노바디노우즈"],["Midas Touch","마이다스터치"],["Sticky","스티키"],["Igloo","이글루"],["Get Loud","겟라우드"],["R.E.M","렘"],["Te Quiero","테키에로"],["kbye","케이바이"]],
    extra: [["kissy","KISS OF LIFE fans, in Hangul","키씨"],["natty","Member who also appeared on Sixteen","나띠"]],
  },
  {
    key: "boynextdoor", name: "BOYNEXTDOOR", hangul: "보이넥스트도어",
    blurb: "KOZ’s neighborhood boys, ONEDOOR, and “One and Only.”",
    kind: "boy-group", fandom: ["원도어", "Official BOYNEXTDOOR fandom name"],
    agency: ["코즈", "Zico’s KOZ label, home of BOYNEXTDOOR"],
    count: ["여섯", "How many members BOYNEXTDOOR has"],
    members: [["Sungho","성호"],["Riwoo","리우"],["Jaehyun","명재현"],["Taesan","태산"],["Leehan","이한"],["Woonhak","운학"]],
    songs: [["One and Only","원앤온리"],["Serenade","세레나데"],["But Sometimes","뭣같은노래"],["Earth, Wind & Fire","어스윈드앤파이어"],["Dangerous","위험한"],["IF I SAY, I LOVE YOU","사랑한다고말할까"],["Nice Guy","나이스가이"],["123-78","일이삼"],["Tonight","투나잇"],["Step By Step","스텝바이스텝"]],
    extra: [["onedoor","BOYNEXTDOOR fans, in Hangul","원도어"],["koz","Zico’s label that debuted the group","코즈"],["zico","The producer behind KOZ","지코"]],
  },
];
