function kpopShared() {
  const row = (id, clue, hangul, tier) =>
    tier ? [id, clue, hangul, tier] : [id, clue, hangul];
  return [
    row("debut", "{name}’s first official release moment", "데뷔"),
    row("comeback", "A new {name} release cycle", "컴백"),
    row("album", "A {name} record, mini or full", "앨범"),
    row("title", "The promoted track on a {name} album", "타이틀"),
    row("mv", "Short for a {name} music video, in Hangul", "뮤비"),
    row("concert", "A {name} live show", "콘서트", 2),
    row("world-tour", "{name} on stages around the globe", "월드투어", 2),
    row("choreo", "The group dance {name} is known for", "안무"),
    row("stage", "Where {name} performs", "무대"),
    row("dance", "A {name} specialty on stage", "댄스"),
    row("vocal", "A {name} singing part", "보컬"),
    row("rapper", "A {name} rap part", "래퍼"),
    row("member", "Someone in {name}", "멤버"),
    row("leader", "The person who leads {name}", "리더"),
    row("maknae", "The youngest person in {name}", "막내"),
    row("center", "The front-and-center spot in a {name} formation", "센터"),
    row("fandom", "The official {name} fan community", "팬덤"),
    row("lightstick", "The glowing stick {name} fans wave", "응원봉"),
    row("variety", "{name} on a Korean entertainment show", "예능"),
    row("seoul", "City where {name} is based", "서울"),
    row("korea", "Country where {name} debuted", "한국"),
    row("fanmeeting", "A {name} event just for fans", "팬미팅", 2),
    row("showcase", "A {name} debut or comeback preview stage", "쇼케이스", 2),
    row("fanclub", "Official {name} fan club, in Hangul", "팬클럽", 2),
    row("visual", "The {name} member known for looks", "비주얼", 2),
    row("main-vocal", "The main singing role in {name}", "메인보컬", 2),
    row("main-dancer", "The main dance role in {name}", "메인댄서", 2),
    row("main-rapper", "The main rap role in {name}", "메인래퍼", 2),
    row("lead-vocal", "The lead singing role in {name}", "리드보컬", 2),
    row("producer", "Someone who makes a {name} track", "프로듀서", 3),
    row("lyrics", "Writing the words of a {name} song", "작사"),
    row("compose", "Writing the melody of a {name} song", "작곡"),
    row("single", "A standalone {name} release", "싱글"),
    row("chart", "Where {name} songs climb each week", "차트"),
    row("billboard", "The US chart {name} aims for", "빌보드", 2),
    row("melon", "A major Korean music chart {name} appears on", "멜론"),
    row("trainee", "What {name} members were before debut", "연습생", 2),
    row("audition", "How some {name} members were chosen", "오디션", 2),
    row("agency", "The company that manages {name}", "소속사", 2),
    row("idol", "{name} as a Korean pop star act", "아이돌"),
    row("singer", "What {name} members are", "가수"),
    row("music-show", "A Korean TV chart show {name} wins on", "음악방송", 2),
    row("first-place", "A music-show win for {name}", "일위"),
    row("popular", "How {name} feels on a comeback week", "인기"),
    row("live", "A {name} performance sung live", "라이브", 2),
    row("fancam", "A close-up {name} performance clip", "직캠"),
    row("goods", "Official {name} merch", "굿즈"),
    row("cheer", "The official {name} fan chant", "응원법", 2),
    row("pictorial", "A {name} magazine shoot", "화보"),
    row("interview", "A {name} press talk", "인터뷰", 2),
    row("ad", "A brand campaign starring {name}", "광고"),
    row("model", "A {name} member off-stage job", "모델"),
    row("arena", "A huge venue for a {name} concert", "경기장", 2),
    row("fans", "{name} supporters in the crowd", "팬들"),
    row("chant", "The roar when {name} appears", "함성"),
    row("chorus", "Fans singing a {name} hook together", "떼창"),
    row("challenge", "A {name} dance trend online", "챌린지", 2),
    row("youtube", "Where {name} MVs premiere", "유튜브", 2),
    row("mnet", "A music channel {name} often appears on", "엠넷"),
    row("inkigayo", "Sunday music show {name} might win", "인기가요", 2),
    row("music-core", "SBS music show {name} might win", "음악중심", 2),
    row("new-song", "A freshly released {name} track", "신곡"),
    row("hit", "A {name} song everyone knows", "히트곡", 2),
    row("signature", "{name}’s most representative song", "대표곡", 2),
    row("debut-song", "The first promoted {name} title", "데뷔곡", 2),
    row("practice", "The room where {name} learns choreography", "연습실", 2),
    row("schedule", "A packed {name} comeback calendar", "스케줄", 2),
    row("manager", "The staff guiding {name} day to day", "매니저", 2),
    row("style", "{name}’s fashion on a comeback", "스타일", 2),
    row("fashion", "What {name} wears on the red carpet", "패션"),
    row("camera", "What films a {name} music video", "카메라", 2),
    row("crowd", "The people watching {name} live", "관객"),
    row("harmony", "Voices blending in a {name} track", "하모니", 2),
    row("high-note", "A soaring {name} vocal moment", "고음"),
    row("rookie", "{name} in the first year after debut", "신인"),
    row("global", "{name} fans around the world", "글로벌", 2),
    row("domestic", "{name} promotions inside Korea", "국내"),
    row("overseas", "{name} promotions outside Korea", "해외"),
    row("activity", "A {name} promotion period", "활동"),
    row("mini-album", "A short {name} EP", "미니앨범", 2),
    row("full-album", "A full-length {name} LP", "정규앨범", 2),
    row("follow-up", "The second promoted {name} track", "후속곡", 2),
    row("fansign", "A {name} signing event", "팬사인회", 3),
    row("encore-stage", "An extra {name} music-show stage", "무대인사", 2),
    row("dance-film", "A {name} choreography video", "안무영상", 2),
    row("tone", "The color of a {name} singing voice", "음색"),
    row("company", "Another word for {name}’s label", "기획사", 2),
    row("streaming", "How fans play a {name} song online", "스트리밍", 3),
    row("album-sales", "Physical copies of a {name} record", "음반"),
    row("digital", "Online {name} track releases", "음원"),
    row("comeback-show", "A special {name} release broadcast", "컴백쇼", 2),
    row("teaser", "A short preview before a {name} MV", "티저"),
    row("concept", "The visual idea of a {name} era", "콘셉트", 2),
    row("styling", "Hair and clothes for a {name} era", "스타일링", 3),
    row("makeup", "Stage {name} beauty looks", "메이크업", 2),
    row("rehearsal", "A {name} practice before the show", "리허설", 2),
    row("encore", "An extra song at a {name} concert", "앙코르", 2),
    row("soundcheck", "The pre-show {name} audio test", "사운드체크", 3),
    row("fanchant", "The shouted {name} lyrics fans learn", "응원", 2),
    row("photocard", "A collectible {name} album card", "포토카드", 3),
    row("album-pack", "The boxed {name} physical release", "앨범팩", 2),
    row("stage-name", "The performing name a {name} member uses", "예명"),
  ];
}

function dramaShared() {
  const row = (id, clue, hangul, tier) =>
    tier ? [id, clue, hangul, tier] : [id, clue, hangul];
  return [
    row("love", "The feeling at the heart of {name}", "사랑"),
    row("family", "Relatives who shape the story of {name}", "가족"),
    row("secret", "A hidden truth in {name}", "비밀"),
    row("fate", "What seems to pull {name} characters together", "운명"),
    row("goodbye", "A painful parting in {name}", "이별"),
    row("reunion", "Meeting again later in {name}", "재회"),
    row("drama", "{name} as a Korean series", "드라마", 2),
    row("actor", "A man who stars in {name}", "배우"),
    row("actress", "A woman who stars in {name}", "여배우", 2),
    row("director", "The person who shaped {name}", "감독"),
    row("script", "The written story of {name}", "대본"),
    row("scene", "A memorable moment in {name}", "장면"),
    row("tears", "What fans shed watching {name}", "눈물"),
    row("confession", "Telling someone you love them in {name}", "고백"),
    row("first-love", "An early romance in {name}", "첫사랑", 2),
    row("memory", "What {name} characters cannot forget", "기억"),
    row("promise", "A vow made in {name}", "약속"),
    row("friendship", "The bond beside romance in {name}", "우정"),
    row("betrayal", "A broken trust in {name}", "배신"),
    row("revenge", "Payback that drives {name}", "복수"),
    row("romance", "The love-story genre of {name}", "로맨스", 2),
    row("melo", "A tearful love story like {name}", "멜로"),
    row("school", "A campus setting in {name}", "학교"),
    row("hospital", "A medical setting in {name}", "병원"),
    row("company", "An office setting in {name}", "회사"),
    row("seoul", "The city often seen in {name}", "서울"),
    row("korea", "The country that made {name}", "한국"),
    row("filming", "Shooting a scene of {name}", "촬영"),
    row("set", "Where {name} is filmed", "세트"),
    row("hero", "The lead of {name}", "주인공", 2),
    row("villain", "The antagonist in {name}", "악역"),
    row("support", "A supporting role in {name}", "조연"),
    row("cameo", "A surprise star popping into {name}", "카메오", 2),
    row("ending", "How {name} closes", "결말"),
    row("twist", "A shock turn in {name}", "반전"),
    row("conflict", "The clash that moves {name}", "갈등"),
    row("emotion", "What {name} wants you to feel", "감동"),
    row("ost", "The soundtrack of {name}", "오에스티", 2),
    row("theme", "The main song of {name}", "주제곡", 2),
    row("line", "A famous line from {name}", "명대사", 2),
    row("shot", "A famous image from {name}", "명장면", 2),
    row("rating", "How many people watched {name}", "시청률", 2),
    row("broadcast", "How {name} first aired", "방송"),
    row("netflix", "A platform that carried {name} worldwide", "넷플릭스", 2),
    row("hallyu", "The Korean Wave {name} rides", "한류"),
    row("syndrome", "A {name} craze among fans", "신드롬", 2),
    row("fans", "People who love {name}", "팬들"),
    row("award", "A prize {name} might win", "배우상", 2),
    row("ceremony", "Where {name} is honored", "시상식", 2),
    row("cannes", "A world film festival {name} might reach", "칸영화제", 3),
    row("oscar", "The Hollywood prize {name} fans talk about", "오스카", 2),
    row("hit-film", "A box-office smash like {name}", "흥행"),
    row("ten-million", "A huge Korean audience for {name}", "천만", 2),
    row("audience", "People watching {name} in theaters", "관객"),
    row("festival", "A film event showing {name}", "영화제", 2),
    row("screenplay", "The written {name} film script", "각본"),
    row("directing", "The visual craft of {name}", "연출"),
    row("location", "A real place used in {name}", "촬영지", 2),
    row("costume", "Clothes worn in {name}", "의상"),
    row("makeup", "Looks created for {name}", "분장"),
    row("light", "How {name} is lit on set", "조명"),
    row("camera", "What films {name}", "카메라", 2),
    row("village", "A small-town setting in {name}", "마을"),
    row("city", "An urban setting in {name}", "도시"),
    row("sea", "Water on the edge of a {name} scene", "바다"),
    row("mountain", "A highland setting in {name}", "산속"),
    row("winter", "A cold season in {name}", "겨울"),
    row("summer", "A hot season in {name}", "여름"),
    row("coffee", "A cafe drink in a {name} date", "커피"),
    row("letter", "A written message in {name}", "편지"),
    row("ring", "A token of a promise in {name}", "반지"),
    row("wedding", "A ceremony that may arrive in {name}", "결혼식", 2),
    row("police", "Investigators in {name}", "경찰"),
    row("prosecutor", "A courtroom fighter in {name}", "검사"),
    row("doctor", "A medical lead in {name}", "의사"),
    row("teacher", "A classroom figure in {name}", "선생님", 2),
    row("chaebol", "A wealthy heir in {name}", "재벌"),
    row("secretary", "An assistant role in {name}", "비서"),
    row("soldier", "A military role in {name}", "군인"),
    row("spy", "A secret-agent role in {name}", "스파이", 2),
    row("hope", "What {name} characters hold onto", "희망"),
    row("despair", "A low point in {name}", "절망"),
    row("courage", "What {name} heroes need", "용기"),
    row("wound", "An emotional injury in {name}", "상처"),
    row("heal", "Recovery after pain in {name}", "치유"),
    row("waiting", "What {name} lovers do across years", "기다림", 2),
    row("meeting", "The first encounter in {name}", "만남"),
    row("heart", "What {name} always aims at", "마음"),
    row("dream", "A wish a {name} character chases", "소원"),
    row("lie", "An untruth told in {name}", "거짓말", 2),
    row("truth", "What {name} finally reveals", "진실"),
    row("justice", "What {name} heroes fight for", "정의"),
    row("crime", "A wrongdoing in {name}", "범죄"),
    row("mystery", "A puzzle the {name} plot hides", "미스터리", 3),
    row("thriller", "A tense genre {name} can touch", "스릴러", 2),
    row("comedy", "Laughs inside {name}", "코미디", 2),
    row("tragedy", "Heartbreak inside {name}", "비극"),
    row("episode", "A weekly chapter of {name}", "회차"),
    row("season", "A later run of {name}", "시즌"),
    row("premiere", "The first airing of {name}", "첫방송", 2),
    row("finale", "The last episode of {name}", "마지막회", 3),
    row("ost-singer", "The voice on a {name} soundtrack", "가창"),
    row("original", "The first version of {name}", "원작"),
  ];
}

module.exports = { kpopShared, dramaShared };
