const { kpop: kpopGloss, drama: dramaGloss } = require("./clue-gloss");

function kpopShared() {
  const row = (id, _old, hangul, tier) => {
    const clue = kpopGloss[id];
    if (!clue) throw new Error(`Missing K-pop gloss for ${id}`);
    return tier ? [id, clue, hangul, tier] : [id, clue, hangul];
  };
  return [
    row("debut", "{name}’s first official release moment", "데뷔"),
    row("comeback", "A new {name} release cycle", "컴백"),
    row("album", "A {name} record, mini or full", "앨범"),
    row("title", "The promoted track on a {name} album", "타이틀"),
    row("mv", "Short for a {name} music video, in Hangul", "뮤비"),
    row("concert", "A {name} live show", "콘서트", 2),
    row("world-tour", "{name} on stages around the globe", "월드투어", 2),
    row("choreo", "The group dance {name} is known for", "안무"),
    row("stage", "Where {name} performs", "무대"),
    row("dance", "A {name} specialty on stage", "댄스"),
    row("vocal", "A {name} singing part", "보컬"),
    row("rapper", "A {name} rap part", "래퍼"),
    row("member", "Someone in {name}", "멤버"),
    row("leader", "The person who leads {name}", "리더"),
    row("maknae", "The youngest person in {name}", "막내"),
    row("center", "The front-and-center spot in a {name} formation", "센터"),
    row("fandom", "The official {name} fan community", "팬덤"),
    row("lightstick", "The glowing stick {name} fans wave", "응원봉"),
    row("variety", "{name} on a Korean entertainment show", "예능"),
    row("seoul", "City where {name} is based", "서울"),
    row("korea", "Country where {name} debuted", "한국"),
    row("fanmeeting", "A {name} event just for fans", "팬미팅", 2),
    row("showcase", "A {name} debut or comeback preview stage", "쇼케이스", 2),
    row("fanclub", "Official {name} fan club, in Hangul", "팬클럽", 2),
    row("visual", "The {name} member known for looks", "비주얼", 2),
    row("main-vocal", "The main singing role in {name}", "메인보컬", 2),
    row("main-dancer", "The main dance role in {name}", "메인댄서", 2),
    row("main-rapper", "The main rap role in {name}", "메인래퍼", 2),
    row("lead-vocal", "The lead singing role in {name}", "리드보컬", 2),
    row("producer", "Someone who makes a {name} track", "프로듀서", 3),
    row("lyrics", "Writing the words of a {name} song", "작사"),
    row("compose", "Writing the melody of a {name} song", "작곡"),
    row("single", "A standalone {name} release", "싱글"),
    row("chart", "Where {name} songs climb each week", "차트"),
    row("billboard", "The US chart {name} aims for", "빌보드", 2),
    row("melon", "A major Korean music chart {name} appears on", "멜론"),
    row("trainee", "What {name} members were before debut", "연습생", 2),
    row("audition", "How some {name} members were chosen", "오디션", 2),
    row("agency", "The company that manages {name}", "소속사", 2),
    row("idol", "{name} as a Korean pop star act", "아이돌"),
    row("singer", "What {name} members are", "가수"),
    row("music-show", "A Korean TV chart show {name} wins on", "음악방송", 2),
    row("first-place", "A music-show win for {name}", "일위"),
    row("popular", "How {name} feels on a comeback week", "인기"),
    row("live", "A {name} performance sung live", "라이브", 2),
    row("fancam", "A close-up {name} performance clip", "직캠"),
    row("goods", "Official {name} merch", "굿즈"),
    row("cheer", "The official {name} fan chant", "응원법", 2),
    row("pictorial", "A {name} magazine shoot", "화보"),
    row("interview", "A {name} press talk", "인터뷰", 2),
    row("ad", "A brand campaign starring {name}", "광고"),
    row("model", "A {name} member off-stage job", "모델"),
    row("arena", "A huge venue for a {name} concert", "경기장", 2),
    row("fans", "{name} supporters in the crowd", "팬들"),
    row("chant", "The roar when {name} appears", "함성"),
    row("chorus", "Fans singing a {name} hook together", "떼창"),
    row("challenge", "A {name} dance trend online", "챌린지", 2),
    row("youtube", "Where {name} MVs premiere", "유튜브", 2),
    row("mnet", "A music channel {name} often appears on", "엠넷"),
    row("inkigayo", "Sunday music show {name} might win", "인기가요", 2),
    row("music-core", "SBS music show {name} might win", "음악중심", 2),
    row("new-song", "A freshly released {name} track", "신곡"),
    row("hit", "A {name} song everyone knows", "히트곡", 2),
    row("signature", "{name}’s most representative song", "대표곡", 2),
    row("debut-song", "The first promoted {name} title", "데뷔곡", 2),
    row("practice", "The room where {name} learns choreography", "연습실", 2),
    row("schedule", "A packed {name} comeback calendar", "스케줄", 2),
    row("manager", "The staff guiding {name} day to day", "매니저", 2),
    row("style", "{name}’s fashion on a comeback", "스타일", 2),
    row("fashion", "What {name} wears on the red carpet", "패션"),
    row("camera", "What films a {name} music video", "카메라", 2),
    row("crowd", "The people watching {name} live", "관객"),
    row("harmony", "Voices blending in a {name} track", "하모니", 2),
    row("high-note", "A soaring {name} vocal moment", "고음"),
    row("rookie", "{name} in the first year after debut", "신인"),
    row("global", "{name} fans around the world", "글로벌", 2),
    row("domestic", "{name} promotions inside Korea", "국내"),
    row("overseas", "{name} promotions outside Korea", "해외"),
    row("activity", "A {name} promotion period", "활동"),
    row("mini-album", "A short {name} EP", "미니앨범", 2),
    row("full-album", "A full-length {name} LP", "정규앨범", 2),
    row("follow-up", "The second promoted {name} track", "후속곡", 2),
    row("fansign", "A {name} signing event", "팬사인회", 3),
    row("encore-stage", "An extra {name} music-show stage", "무대인사", 2),
    row("dance-film", "A {name} choreography video", "안무영상", 2),
    row("tone", "The color of a {name} singing voice", "음색"),
    row("company", "Another word for {name}’s label", "기획사", 2),
    row("streaming", "How fans play a {name} song online", "스트리밍", 3),
    row("album-sales", "Physical copies of a {name} record", "음반"),
    row("digital", "Online {name} track releases", "음원"),
    row("comeback-show", "A special {name} release broadcast", "컴백쇼", 2),
    row("teaser", "A short preview before a {name} MV", "티저"),
    row("concept", "The visual idea of a {name} era", "콘셉트", 2),
    row("styling", "Hair and clothes for a {name} era", "스타일링", 3),
    row("makeup", "Stage {name} beauty looks", "메이크업", 2),
    row("rehearsal", "A {name} practice before the show", "리허설", 2),
    row("encore", "An extra song at a {name} concert", "앙코르", 2),
    row("soundcheck", "The pre-show {name} audio test", "사운드체크", 3),
    row("fanchant", "The shouted {name} lyrics fans learn", "응원", 2),
    row("photocard", "A collectible {name} album card", "포토카드", 3),
    row("album-pack", "The boxed {name} physical release", "앨범팩", 2),
    row("stage-name", "The performing name a {name} member uses", "예명"),
    row("unit", "A smaller {name} line inside the act", "유닛"),
    row("solo-run", "A {name} member promoting alone", "솔로"),
    row("duet", "Two voices sharing a {name} track", "듀엣"),
    row("collab", "A {name} track made with another act", "콜라보", 2),
    row("featuring", "A guest verse on a {name} song", "피처링", 2),
    row("remix", "A remixed version of a {name} song", "리믹스", 2),
    row("repack", "A repackaged {name} album", "리팩"),
    row("pre-release", "A track dropped before the {name} album", "선공개", 2),
    row("first-week", "First-week sales of a {name} album", "초동"),
    row("million", "A million copies sold by {name}", "밀리언", 2),
    row("daesang", "The grand prize {name} dreams of", "대상"),
    row("bonsang", "A main prize {name} might take home", "본상"),
    row("rookie-award", "A first-year prize for {name}", "신인상", 2),
    row("album-award", "An album prize for {name}", "음반상", 2),
    row("digital-award", "A digital-song prize for {name}", "음원상", 2),
    row("m-countdown", "Mnet chart show {name} might win", "엠카"),
    row("the-show", "SBS MTV chart show {name} might win", "더쇼"),
    row("show-champion", "MBC M chart show {name} might win", "쇼챔"),
    row("music-bank", "KBS Friday show {name} might win", "뮤직뱅크", 2),
    row("song-festival", "A year-end stage for {name}", "가요제", 2),
    row("year-end-fest", "A big year-end music festival {name} plays", "가요대축제", 3),
    row("red-carpet", "The walk {name} takes at an awards night", "레드카펫", 2),
    row("press-con", "A {name} press conference", "기자회견", 2),
    row("press-talk", "A sit-down {name} press event", "기자간담회", 3),
    row("fan-con", "A {name} concert built for fans", "팬콘"),
    row("online", "A {name} event streamed on the internet", "온라인", 2),
    row("offline", "A {name} event held in person", "오프라인", 2),
    row("weverse", "The HYBE app where {name} fans gather", "위버스", 2),
    row("bubble", "A paid chat app some {name} members use", "버블"),
    row("fan-cafe", "The official {name} online cafe", "팬카페", 2),
    row("official-fandom", "The registered {name} fan community", "공식팬덤", 2),
    row("membership", "Paid {name} fan membership", "멤버십", 2),
    row("kit", "A {name} membership welcome kit", "키트"),
    row("poster", "A folded {name} album poster", "포스터", 2),
    row("postcard", "A small {name} album postcard", "엽서"),
    row("sticker", "A {name} sticker sheet in the album", "스티커", 2),
    row("booklet", "The lyric booklet in a {name} album", "북클릿", 2),
    row("digit", "A digital {name} photocard code", "디짓"),
    row("jacket", "The cover art of a {name} album", "앨범자켓", 2),
    row("performance", "A {name} stage performance", "퍼포먼스", 2),
    row("point-dance", "The signature move in a {name} song", "포인트안무", 3),
    row("group-dance", "Tight group dancing by {name}", "군무"),
    row("sharp-dance", "The razor-sharp {name} formation dance", "칼군무", 2),
    row("formation", "How {name} stands on stage", "포메이션", 2),
    row("ending-pose", "The last pose of a {name} stage", "엔딩포즈", 2),
    row("intro", "The opening of a {name} track", "인트로", 2),
    row("outro", "The closing of a {name} track", "아웃트로", 2),
    row("bridge", "The bridge section of a {name} song", "브릿지", 2),
    row("chorus-part", "The hook section of a {name} song", "후렴"),
    row("hook-song", "A {name} track built on one catchy hook", "훅송"),
    row("ballad", "A slow emotional {name} song", "발라드", 2),
    row("hiphop", "A rap-heavy {name} track", "힙합"),
    row("rnb", "An R&B-colored {name} song", "알앤비", 2),
    row("dance-track", "A dance title from {name}", "댄스곡", 2),
    row("title-track", "The lead single from a {name} album", "타이틀곡", 2),
    row("b-side", "A non-title track on a {name} album", "수록곡", 2),
    row("self-written", "A {name} song written in-house", "자작곡", 2),
    row("producing", "Making the track behind {name}", "프로듀싱", 3),
    row("arrange", "Arranging a {name} song", "편곡"),
    row("mixing", "Mixing a {name} recording", "믹싱"),
    row("mastering", "The final polish on a {name} track", "마스터링", 3),
    row("record", "Recording a {name} vocal", "녹음"),
    row("studio", "Where {name} records", "녹음실", 2),
    row("vocal-director", "The coach shaping a {name} vocal", "보컬디렉", 2),
    row("choreographer", "The person who builds {name} dances", "안무가", 2),
    row("stylist", "The person dressing {name}", "스타일리스트", 3),
    row("hair", "Stage hair for a {name} era", "헤어"),
    row("sound", "The live audio at a {name} show", "음향"),
    row("prop", "A handheld {name} stage prop", "소품"),
    row("costume", "An outfit {name} wears on stage", "의상"),
    row("stage-set", "The built set behind {name}", "무대장치", 2),
    row("concert-hall", "A hall built for a {name} show", "콘서트장", 2),
    row("stadium", "A stadium-sized {name} venue", "스타디움", 2),
    row("festival", "A multi-act bill {name} joins", "페스티벌", 2),
    row("lineup", "The poster list that includes {name}", "라인업", 2),
    row("headliner", "When {name} closes the festival", "헤드라이너", 3),
    row("opening-act", "The act that opens for {name}", "오프닝", 2),
    row("guest", "A surprise guest with {name}", "게스트", 2),
    row("special-stage", "A one-off {name} special stage", "스페셜스테이지", 3),
    row("encore-song", "An extra song {name} sings at the end", "앵콜곡", 2),
    row("medley", "A string of {name} hits in one go", "메들리", 2),
    row("cover", "A {name} cover of another song", "커버"),
    row("remake", "A remade classic sung by {name}", "리메이크", 2),
    row("original-song", "The first version of a {name} cover", "원곡"),
    row("vocal-skill", "The singing power of {name}", "가창력", 2),
    row("rap-part", "A rap section in a {name} song", "랩파트", 2),
    row("high-note-en", "A soaring note in a {name} live", "하이노트", 2),
    row("adlib", "An improvised {name} vocal run", "애드리브", 2),
    row("chorus-stack", "Stacked voices on a {name} hook", "코러스", 2),
    row("breath", "Breath control in a {name} vocal", "호흡"),
    row("voice-train", "How a {name} member trains the voice", "발성"),
    row("diction", "Clear {name} lyrics on a live stage", "딕션"),
    row("charisma", "The stage presence of {name}", "카리스마", 2),
    row("aura", "The vibe {name} gives off on camera", "아우라", 2),
    row("chemistry", "The on-stage bond inside {name}", "케미"),
    row("selfie", "A {name} member’s phone photo", "셀카"),
    row("selca-pic", "A fan-taken still of {name}", "직찍"),
    row("vlog", "A day-in-the-life {name} video", "브이로그", 2),
    row("reality", "A {name} variety reality series", "리얼리티", 2),
    row("documentary", "A long-form {name} documentary", "다큐"),
    row("variety-sense", "How funny {name} is on variety", "예능감", 2),
    row("bias-wreck", "Falling for {name} for the first time", "입덕"),
    row("bias", "A fan’s favorite {name} member", "최애"),
    row("second-bias", "A fan’s second-favorite in {name}", "차애"),
    row("ot-fan", "A fan who loves all of {name}", "올팬"),
    row("stan", "The hobby of following {name} closely", "덕질"),
    row("bias-song", "A fan’s favorite {name} track", "최애곡", 2),
    row("bias-mem", "A fan’s favorite person in {name}", "최애멤", 2),
    row("poca", "Short word for a {name} photocard", "포카"),
    row("unboxing", "Opening a new {name} album", "앨범언박싱", 3),
    row("open-pack", "Tearing the wrap on a {name} album", "개봉"),
    row("collect", "Keeping every {name} version", "소장"),
    row("limited", "A limited {name} album version", "한정판", 2),
    row("standard", "The regular {name} album version", "일반반", 2),
    row("platform-album", "A tiny {name} platform album", "플랫폼앨범", 3),
    row("digipack", "A {name} digipack edition", "디지팩", 2),
    row("kino", "A {name} kit-style album", "키노"),
    row("lp", "A vinyl {name} record", "엘피"),
    row("cd", "A compact disc of {name}", "시디"),
    row("dvd", "A {name} concert DVD", "디브이디", 2),
    row("bluray", "A {name} concert Blu-ray", "블루레이", 2),
    row("video-call", "A paid {name} video call event", "영상통화", 2),
    row("fan-call", "A {name} fansign on a video call", "팬콜"),
    row("yeongtong", "Korean slang for a {name} video call", "영통"),
    row("in-person", "Meeting {name} face to face", "대면"),
    row("remote", "A {name} event that is not in person", "비대면", 2),
    row("sign-event", "Another word for a {name} signing", "사인회", 2),
    row("mini-fanmeet", "A short {name} fan meeting", "미니팬미팅", 3),
    row("busking", "A street-style {name} live", "버스킹", 2),
    row("guerrilla", "A surprise {name} guerrilla stage", "게릴라", 2),
    row("surprise-show", "A pop-up {name} performance", "깜짝공연", 2),
    row("pre-record", "A {name} music-show pre-record", "사전녹화", 2),
    row("live-tv", "A {name} show aired live", "생방송", 2),
    row("taping", "A {name} show taped for later", "녹화"),
    row("waiting-room", "Where {name} waits before stage", "대기실", 2),
    row("dressing-room", "Where {name} gets ready", "분장실", 2),
    row("dance-practice", "A {name} choreography practice", "안무연습", 2),
    row("vocal-lesson", "A singing lesson for {name}", "보컬레슨", 2),
    row("foreign-lang", "A language {name} studies for tours", "외국어", 2),
    row("japanese", "A language {name} uses in Japan", "일본어", 2),
    row("english", "A language {name} uses overseas", "영어"),
    row("chinese", "A language {name} uses in China", "중국어", 2),
    row("japan-tour", "A {name} tour across Japan", "일본투어", 2),
    row("us-tour", "A {name} tour across the US", "미국투어", 2),
    row("europe-tour", "A {name} tour across Europe", "유럽투어", 2),
    row("asia-tour", "A {name} tour across Asia", "아시아투어", 3),
    row("world-star", "What global fans call {name}", "월드스타", 2),
    row("hallyu-star", "A Korean Wave star like {name}", "한류스타", 2),
    row("icon-act", "{name} as a pop-culture icon", "아이콘"),
    row("legend-act", "A legendary status for {name}", "레전드", 2),
    row("legend-kr", "The Korean word for a {name} legend", "전설"),
    row("sunbae", "An older act {name} looks up to", "선배"),
    row("hoobae", "A newer act looking up to {name}", "후배"),
    row("same-year", "Acts who debuted with {name}", "동기"),
    row("best-friend", "A close friend inside {name}", "절친"),
    row("teamwork", "How {name} works as one unit", "팀워크", 2),
    row("leadership", "How the {name} leader holds the team", "리더십", 2),
    row("all-rounder", "A {name} member who does it all", "올라운더", 2),
    row("all-talent", "A {name} member good at everything", "만능"),
    row("talent", "The raw talent inside {name}", "재능"),
    row("passion", "The drive behind {name}", "열정"),
    row("goal", "What {name} is aiming for next", "목표"),
    row("success", "The payoff after a {name} comeback", "성공"),
    row("glory", "The spotlight moment for {name}", "영광"),
    row("moved", "How a {name} stage can feel", "감동"),
    row("tears", "What fans cry at a {name} concert", "눈물"),
    row("happy", "The feeling after a {name} win", "행복"),
    row("love", "What {name} songs often talk about", "사랑"),
    row("cheer-song", "A song fans sing for {name}", "응원가", 2),
    row("slogan", "A printed {name} fan slogan", "슬로건", 2),
    row("cheer-tool", "Anything fans wave for {name}", "응원도구", 2),
    row("official-color", "The official color of {name}", "공식컬러", 2),
    row("fan-color", "The color {name} fans wear", "팬컬러", 2),
    row("lyrics-text", "The written words of a {name} song", "가사"),
    row("pronounce-guide", "A guide to saying {name} lyrics", "발음가이드", 3),
    row("hangul-script", "The Korean script {name} titles use", "한글"),
    row("korean-lang", "The language of a {name} title track", "한국어", 2),
    row("romanization", "English letters for a {name} name", "로마자", 2),
    row("sub-unit", "An official smaller {name} unit", "서브유닛", 2),
    row("group-act", "{name} as a full group", "그룹"),
    row("special-ver", "A special version of a {name} release", "스페셜", 2),
    row("double-title", "Two title tracks in one {name} era", "더블타이틀", 3),
    row("pre-order", "Ordering a {name} album early", "선주문", 2),
    row("golden-disc", "A major January awards stage for {name}", "골든디스크", 3),
    row("live-broadcast", "A live {name} online broadcast", "라이브방송", 2),
    row("universe-app", "An older fan app some {name} acts used", "유니버스", 2),
    row("rock", "A rock-leaning {name} track", "록음악", 2),
    row("dream", "The dream that started {name}", "꿈과희망", 2),
    row("dome", "A dome venue on a {name} tour", "돔구장", 2),
    row("live-clip", "A short live clip of {name}", "라이브클립", 3),
    row("weverse-con", "A Weverse concert featuring {name}", "위버스콘", 2),
    row("fan-light", "The sea of lights at a {name} show", "응원물결", 2),
    row("album-shop", "Where fans buy a {name} record", "음반가게", 2),
    row("music-store", "A shop rack holding {name} albums", "음반샵", 2),
    row("radio-show", "A {name} appearance on radio", "라디오", 2),
    row("late-night", "A late-night {name} TV appearance", "심야방송", 2),
    row("morning-show", "A morning {name} promo", "아침방송", 2),
    row("endorsement", "A product {name} endorses", "모델계약", 2),
    row("ambassador", "A brand-ambassador role for {name}", "홍보대사", 2),
    row("cf", "A Korean commercial starring {name}", "씨에프"),
    row("pictorial-set", "The set of a {name} magazine shoot", "화보촬영", 2),
    row("cover-mag", "A magazine cover starring {name}", "표지모델", 2),
    row("sns", "The social channels {name} posts on", "에스엔에스", 3),
    row("instagram", "Where {name} posts photos", "인스타", 2),
    row("tiktok", "Where a {name} challenge spreads", "틱톡"),
    row("weibo", "A Chinese platform {name} may use", "웨이보", 2),
    row("twitter", "The fan-news stream around {name}", "엑스"),
    row("fancam-ver", "Another word for a {name} fancam", "직캠영상", 2),
    row("relay-dance", "A {name} relay dance video", "릴레이댄스", 3),
    row("dance-challenge", "A short {name} challenge clip", "챌린지영상", 3),
    row("behind", "Behind-the-scenes of a {name} shoot", "비하인드", 2),
    row("making", "A making-of {name} music video", "메이킹", 2),
    row("jacket-shoot", "The {name} album jacket shoot", "자켓촬영", 2),
    row("mv-set", "The set of a {name} music video", "뮤비세트", 2),
    row("practice-wear", "What {name} wears to practice", "연습복", 2),
    row("in-ear", "The in-ear monitors {name} wears", "인이어", 2),
    row("click", "The click track {name} dances to", "클릭"),
    row("formation-change", "A {name} formation switch", "자리이동", 2),
    row("center-part", "The center part in a {name} song", "센터파트", 2),
    row("ending-fairy", "The ending-fairy shot of {name}", "엔딩요정", 2),
    row("first-win", "The first music-show win for {name}", "첫우승", 2),
    row("triple-crown", "Three music-show wins in a week for {name}", "트리플크라운", 3),
    row("grand-slam", "A clean sweep of shows for {name}", "그랜드슬램", 3),
    row("rookie-year", "The debut year of {name}", "데뷔년도", 2),
    row("anniversary", "A debut anniversary for {name}", "기념일", 2),
    row("debut-stage", "The first official {name} stage", "데뷔무대", 2),
    row("last-stage", "The goodbye stage of a {name} era", "마지막무대", 3),
    row("hiatus", "A pause in {name} group activity", "휴식기", 2),
    row("enlist", "When a {name} member starts service", "입대"),
    row("discharge", "When a {name} member finishes service", "전역"),
    row("military", "The service chapter in a {name} career", "군대"),
    row("comeback-date", "The day {name} returns", "컴백일", 2),
    row("release-date", "The day a {name} song drops", "발매일", 2),
    row("pre-save", "Saving a {name} track before release", "프리세이브", 3),
    row("streaming-party", "A fan party streaming {name}", "스트리밍파티", 3),
    row("chart-run", "How long a {name} song stays up", "차트인", 2),
    row("realtime", "Realtime Korean charts for {name}", "실시간차트", 3),
    row("unique-listen", "Unique listeners of a {name} track", "유니크", 2),
    row("like-count", "Hearts on a {name} music video", "좋아요", 2),
    row("view-count", "Views on a {name} music video", "조회수", 2),
    row("subscribe", "Subscribing to the {name} channel", "구독"),
    row("premiere-mv", "A {name} MV premiere countdown", "최초공개", 2),
    row("tracklist", "The list of songs on a {name} album", "트랙리스트", 3),
    row("credit", "The credits on a {name} song", "크레딧", 2),
    row("songwriter", "Someone who wrote a {name} song", "작곡가", 2),
    row("lyricist", "Someone who wrote {name} lyrics", "작사가", 2),
    row("beat", "The beat under a {name} rap", "비트"),
    row("sample", "A sample used in a {name} track", "샘플"),
    row("hook", "The catchiest bit of a {name} song", "훅라인"),
    row("key-change", "A key change in a {name} bridge", "전조"),
    row("tempo", "The speed of a {name} title track", "템포"),
    row("bpm", "The beat count of a {name} song", "비피엠", 2),
    row("live-band", "A live band behind {name}", "밴드"),
    row("mr-removed", "A {name} stage with the track pulled back", "엠알", 2),
    row("in-ear-mix", "The mix {name} hears on stage", "모니터", 2),
    row("sound-engineer", "The engineer on a {name} tour", "음향감독", 2),
    row("tour-md", "Official {name} tour merchandise", "투어굿즈", 2),
    row("light-ocean", "The ocean of {name} light sticks", "바다물결", 2),
    row("encore-ment", "Talk time in a {name} encore", "멘트"),
    row("ment", "Spoken {name} ment between songs", "콘서트멘트", 3),
    row("setlist", "The song order of a {name} concert", "셋리스트", 2),
    row("d-1", "The day before a {name} concert", "디데이", 2),
    row("ticket", "A seat for a {name} show", "티켓"),
    row("ticketing", "The race to buy a {name} ticket", "티켓팅", 2),
    row("waiting-line", "The line outside a {name} venue", "대기줄", 2),
    row("soundcheck-tix", "A soundcheck ticket for {name}", "사청권", 2),
    row("vip-seat", "A close seat at a {name} show", "브이아이피", 3),
    row("floor", "The standing floor at a {name} show", "스탠딩", 2),
    row("seat", "A numbered seat at a {name} show", "지정석", 2),
    row("slogan-event", "A fan-made {name} slogan event", "슬로건이벤트", 3),
    row("birthday-cafe", "A cafe event for a {name} birthday", "생카"),
    row("birthday", "A {name} member’s birthday", "생일"),
    row("debut-day", "The calendar day {name} debuted", "데뷔일", 2),
    row("group-name", "The official name of {name}", "그룹명", 2),
    row("official-logo", "The logo of {name}", "로고"),
    row("official-color-2", "Another word for {name}’s color", "대표색", 2),
    row("light-color", "The glow color of a {name} stick", "봉컬러", 2),
    row("fandom-color", "The color {name} fans wear together", "팬덤색", 2),
  ];
}

function dramaShared() {
  const row = (id, _old, hangul, tier) => {
    const clue = dramaGloss[id];
    if (!clue) throw new Error(`Missing K-drama gloss for ${id}`);
    return tier ? [id, clue, hangul, tier] : [id, clue, hangul];
  };
  return [
    row("love", "The feeling at the heart of {name}", "사랑"),
    row("family", "Relatives who shape the story of {name}", "가족"),
    row("secret", "A hidden truth in {name}", "비밀"),
    row("fate", "What seems to pull {name} characters together", "운명"),
    row("goodbye", "A painful parting in {name}", "이별"),
    row("reunion", "Meeting again later in {name}", "재회"),
    row("drama", "{name} as a Korean series", "드라마", 2),
    row("actor", "A man who stars in {name}", "배우"),
    row("actress", "A woman who stars in {name}", "여배우", 2),
    row("director", "The person who shaped {name}", "감독"),
    row("script", "The written story of {name}", "대본"),
    row("scene", "A memorable moment in {name}", "장면"),
    row("tears", "What fans shed watching {name}", "눈물"),
    row("confession", "Telling someone you love them in {name}", "고백"),
    row("first-love", "An early romance in {name}", "첫사랑", 2),
    row("memory", "What {name} characters cannot forget", "기억"),
    row("promise", "A vow made in {name}", "약속"),
    row("friendship", "The bond beside romance in {name}", "우정"),
    row("betrayal", "A broken trust in {name}", "배신"),
    row("revenge", "Payback that drives {name}", "복수"),
    row("romance", "The love-story genre of {name}", "로맨스", 2),
    row("melo", "A tearful love story like {name}", "멜로"),
    row("school", "A campus setting in {name}", "학교"),
    row("hospital", "A medical setting in {name}", "병원"),
    row("company", "An office setting in {name}", "회사"),
    row("seoul", "The city often seen in {name}", "서울"),
    row("korea", "The country that made {name}", "한국"),
    row("filming", "Shooting a scene of {name}", "촬영"),
    row("set", "Where {name} is filmed", "세트"),
    row("hero", "The lead of {name}", "주인공", 2),
    row("villain", "The antagonist in {name}", "악역"),
    row("support", "A supporting role in {name}", "조연"),
    row("cameo", "A surprise star popping into {name}", "카메오", 2),
    row("ending", "How {name} closes", "결말"),
    row("twist", "A shock turn in {name}", "반전"),
    row("conflict", "The clash that moves {name}", "갈등"),
    row("emotion", "What {name} wants you to feel", "감동"),
    row("ost", "The soundtrack of {name}", "오에스티", 2),
    row("theme", "The main song of {name}", "주제곡", 2),
    row("line", "A famous line from {name}", "명대사", 2),
    row("shot", "A famous image from {name}", "명장면", 2),
    row("rating", "How many people watched {name}", "시청률", 2),
    row("broadcast", "How {name} first aired", "방송"),
    row("netflix", "A platform that carried {name} worldwide", "넷플릭스", 2),
    row("hallyu", "The Korean Wave {name} rides", "한류"),
    row("syndrome", "A {name} craze among fans", "신드롬", 2),
    row("fans", "People who love {name}", "팬들"),
    row("award", "A prize {name} might win", "배우상", 2),
    row("ceremony", "Where {name} is honored", "시상식", 2),
    row("cannes", "A world film festival {name} might reach", "칸영화제", 3),
    row("oscar", "The Hollywood prize {name} fans talk about", "오스카", 2),
    row("hit-film", "A box-office smash like {name}", "흥행"),
    row("ten-million", "A huge Korean audience for {name}", "천만", 2),
    row("audience", "People watching {name} in theaters", "관객"),
    row("festival", "A film event showing {name}", "영화제", 2),
    row("screenplay", "The written {name} film script", "각본"),
    row("directing", "The visual craft of {name}", "연출"),
    row("location", "A real place used in {name}", "촬영지", 2),
    row("costume", "Clothes worn in {name}", "의상"),
    row("makeup", "Looks created for {name}", "분장"),
    row("light", "How {name} is lit on set", "조명"),
    row("camera", "What films {name}", "카메라", 2),
    row("village", "A small-town setting in {name}", "마을"),
    row("city", "An urban setting in {name}", "도시"),
    row("sea", "Water on the edge of a {name} scene", "바다"),
    row("mountain", "A highland setting in {name}", "산속"),
    row("winter", "A cold season in {name}", "겨울"),
    row("summer", "A hot season in {name}", "여름"),
    row("coffee", "A cafe drink in a {name} date", "커피"),
    row("letter", "A written message in {name}", "편지"),
    row("ring", "A token of a promise in {name}", "반지"),
    row("wedding", "A ceremony that may arrive in {name}", "결혼식", 2),
    row("police", "Investigators in {name}", "경찰"),
    row("prosecutor", "A courtroom fighter in {name}", "검사"),
    row("doctor", "A medical lead in {name}", "의사"),
    row("teacher", "A classroom figure in {name}", "선생님", 2),
    row("chaebol", "A wealthy heir in {name}", "재벌"),
    row("secretary", "An assistant role in {name}", "비서"),
    row("soldier", "A military role in {name}", "군인"),
    row("spy", "A secret-agent role in {name}", "스파이", 2),
    row("hope", "What {name} characters hold onto", "희망"),
    row("despair", "A low point in {name}", "절망"),
    row("courage", "What {name} heroes need", "용기"),
    row("wound", "An emotional injury in {name}", "상처"),
    row("heal", "Recovery after pain in {name}", "치유"),
    row("waiting", "What {name} lovers do across years", "기다림", 2),
    row("meeting", "The first encounter in {name}", "만남"),
    row("heart", "What {name} always aims at", "마음"),
    row("dream", "A wish a {name} character chases", "소원"),
    row("lie", "An untruth told in {name}", "거짓말", 2),
    row("truth", "What {name} finally reveals", "진실"),
    row("justice", "What {name} heroes fight for", "정의"),
    row("crime", "A wrongdoing in {name}", "범죄"),
    row("mystery", "A puzzle the {name} plot hides", "미스터리", 3),
    row("thriller", "A tense genre {name} can touch", "스릴러", 2),
    row("comedy", "Laughs inside {name}", "코미디", 2),
    row("tragedy", "Heartbreak inside {name}", "비극"),
    row("episode", "A weekly chapter of {name}", "회차"),
    row("season", "A later run of {name}", "시즌"),
    row("premiere", "The first airing of {name}", "첫방송", 2),
    row("finale", "The last episode of {name}", "마지막회", 3),
    row("ost-singer", "The voice on a {name} soundtrack", "가창"),
    row("original", "The first version of {name}", "원작"),
    row("pilot", "An early test episode of {name}", "파일럿", 2),
    row("special", "A special episode of {name}", "스페셜", 2),
    row("recap", "A recap episode of {name}", "요약"),
    row("preview", "A next-week preview of {name}", "예고"),
    row("teaser-cut", "A short teaser for {name}", "티저"),
    row("poster", "A key poster for {name}", "포스터", 2),
    row("still", "A still cut from {name}", "스틸컷", 2),
    row("bcut", "A behind cut from the {name} set", "비하인드", 2),
    row("making", "A making-of {name} video", "메이킹", 2),
    row("press", "A {name} press conference", "제작발표회", 3),
    row("interview", "A {name} cast interview", "인터뷰", 2),
    row("magazine", "A {name} pictorial in a magazine", "화보"),
    row("ost-album", "The collected songs of {name}", "사운드트랙", 3),
    row("part-one", "The first OST part for {name}", "파트원", 2),
    row("ballad-ost", "A ballad written for {name}", "발라드", 2),
    row("love-song", "A love song on the {name} OST", "연가"),
    row("insert-song", "A song placed inside a {name} scene", "삽입곡", 2),
    row("score", "The instrumental score of {name}", "스코어", 2),
    row("composer", "Someone who scored {name}", "작곡가", 2),
    row("writer", "The writer of {name}", "작가"),
    row("pd", "The PD who ran {name}", "피디"),
    row("crew", "The crew that made {name}", "스태프", 2),
    row("cast", "The full cast of {name}", "출연진", 2),
    row("lead-pair", "The main couple of {name}", "남녀주인공", 3),
    row("second-couple", "The second couple in {name}", "서브커플", 2),
    row("chemistry", "The on-screen spark in {name}", "케미"),
    row("eye-contact", "A long look in a {name} scene", "눈맞춤", 2),
    row("hand-hold", "A first touch in {name}", "손잡기", 2),
    row("hug", "An embrace in {name}", "포옹"),
    row("kiss", "A kiss scene in {name}", "키스"),
    row("date", "A date night in {name}", "데이트", 2),
    row("rain-scene", "A rainy confession in {name}", "빗속", 2),
    row("umbrella", "A shared umbrella in {name}", "우산"),
    row("night-walk", "A night walk in {name}", "밤산책", 2),
    row("rooftop", "A rooftop talk in {name}", "옥상"),
    row("han-river", "A Han River walk in {name}", "한강"),
    row("cafe", "A cafe date in {name}", "카페"),
    row("bookstore", "A quiet bookstore in {name}", "서점"),
    row("alley", "A narrow alley in {name}", "골목"),
    row("home", "A family house in {name}", "우리집"),
    row("apartment", "A Seoul apartment in {name}", "아파트", 2),
    row("mansion", "A rich house in {name}", "저택"),
    row("office-desk", "A desk in the {name} workplace", "책상"),
    row("meeting-room", "A glass meeting room in {name}", "회의실", 2),
    row("court", "A courtroom in {name}", "법정"),
    row("prison", "A cell in {name}", "감옥"),
    row("station", "A police station in {name}", "경찰서", 2),
    row("crime-scene", "A crime scene in {name}", "현장"),
    row("evidence", "A clue left in {name}", "증거"),
    row("suspect", "A suspect in {name}", "용의자", 2),
    row("alibi", "An alibi in {name}", "알리바이", 2),
    row("witness", "A witness in {name}", "증인"),
    row("trial", "A trial in {name}", "재판"),
    row("verdict", "The verdict in {name}", "판결"),
    row("investigation", "The investigation in {name}", "수사"),
    row("detective", "A detective in {name}", "형사"),
    row("profiler", "A profiler in {name}", "프로파일러", 3),
    row("journalist", "A reporter in {name}", "기자"),
    row("lawyer", "A lawyer in {name}", "변호사", 2),
    row("judge", "A judge in {name}", "판사"),
    row("nurse", "A nurse in {name}", "간호사", 2),
    row("surgeon", "A surgeon in {name}", "외과의사", 2),
    row("patient", "A patient in {name}", "환자"),
    row("student", "A student in {name}", "학생"),
    row("teacher-role", "A teacher in {name}", "교사"),
    row("principal", "A principal in {name}", "교장"),
    row("classmate", "A classmate in {name}", "동창"),
    row("senior", "A school senior in {name}", "선배"),
    row("junior", "A school junior in {name}", "후배"),
    row("uniform", "A school uniform in {name}", "교복"),
    row("exam", "An exam that matters in {name}", "시험"),
    row("college", "A university setting in {name}", "대학"),
    row("dorm", "A dorm room in {name}", "기숙사", 2),
    row("part-time", "A part-time job in {name}", "알바"),
    row("ceo", "A company boss in {name}", "대표"),
    row("chairman", "A chairman in {name}", "회장"),
    row("heir", "An heir in {name}", "후계자", 2),
    row("rival", "A rival in {name}", "라이벌", 2),
    row("enemy", "An enemy in {name}", "원수"),
    row("ally", "An ally in {name}", "동료"),
    row("mentor", "A mentor in {name}", "멘토"),
    row("mother", "A mother in {name}", "어머니", 2),
    row("father", "A father in {name}", "아버지", 2),
    row("daughter", "A daughter in {name}", "딸아이"),
    row("son", "A son in {name}", "아들"),
    row("sister", "A sister in {name}", "언니"),
    row("brother", "A brother in {name}", "형님"),
    row("grandmother", "A grandmother in {name}", "할머니", 2),
    row("grandfather", "A grandfather in {name}", "할아버지", 3),
    row("in-law", "In-laws who complicate {name}", "시댁"),
    row("marriage", "A marriage plot in {name}", "결혼"),
    row("divorce", "A divorce plot in {name}", "이혼"),
    row("contract", "A contract relationship in {name}", "계약"),
    row("fake-dating", "A fake couple in {name}", "가짜연애", 2),
    row("breakup", "A breakup in {name}", "헤어짐", 2),
    row("jealousy", "Jealousy in {name}", "질투"),
    row("misunderstanding", "A misunderstanding in {name}", "오해"),
    row("apology", "An apology in {name}", "사과"),
    row("forgiveness", "Forgiveness in {name}", "용서"),
    row("trust", "Trust rebuilt in {name}", "신뢰"),
    row("loyalty", "Loyalty tested in {name}", "의리"),
    row("sacrifice", "A sacrifice in {name}", "희생"),
    row("guilt", "Guilt that follows a {name} lead", "죄책감", 2),
    row("trauma", "A past wound in {name}", "트라우마", 2),
    row("therapy", "Healing talk in {name}", "상담"),
    row("diary", "A diary that matters in {name}", "일기"),
    row("photo", "A photo that unlocks {name}", "사진"),
    row("phone", "A phone call that changes {name}", "전화"),
    row("message", "A text that changes {name}", "문자"),
    row("email", "An email in {name}", "메일"),
    row("key", "A key that opens a {name} secret", "열쇠"),
    row("box", "A box of memories in {name}", "상자"),
    row("gift", "A gift exchanged in {name}", "선물"),
    row("flower", "Flowers sent in {name}", "꽃다발", 2),
    row("rose", "A rose in a {name} confession", "장미"),
    row("necklace", "A necklace in {name}", "목걸이", 2),
    row("watch", "A watch gifted in {name}", "시계"),
    row("scarf", "A scarf left behind in {name}", "목도리", 2),
    row("book", "A book that matters in {name}", "책한권"),
    row("music-box", "A music box in {name}", "오르골", 2),
    row("piano", "A piano scene in {name}", "피아노", 2),
    row("guitar", "A guitar serenade in {name}", "기타"),
    row("song", "A song performed inside {name}", "노래"),
    row("dance", "A dance scene in {name}", "춤사위"),
    row("food", "A shared meal in {name}", "음식"),
    row("ramyeon", "Late-night ramyeon in {name}", "라면"),
    row("soju", "A soju night in {name}", "소주"),
    row("chicken", "Chicken and beer in {name}", "치킨"),
    row("gimbap", "Packed gimbap in {name}", "김밥"),
    row("tteokbokki", "Street tteokbokki in {name}", "떡볶이", 2),
    row("hotpot", "A steaming pot in {name}", "전골"),
    row("birthday-cake", "A birthday cake in {name}", "케이크", 2),
    row("first-snow", "First snow in {name}", "첫눈"),
    row("spring", "A spring chapter in {name}", "봄날"),
    row("autumn", "An autumn chapter in {name}", "가을"),
    row("night", "A long night in {name}", "밤하늘"),
    row("dawn", "A dawn goodbye in {name}", "새벽"),
    row("sunset", "A sunset in {name}", "노을"),
    row("star", "Stars over a {name} scene", "별빛"),
    row("moon", "The moon in a {name} night", "달빛"),
    row("rain", "Rain that soaks a {name} scene", "빗물"),
    row("snow", "Snow falling in {name}", "눈꽃"),
    row("wind", "Wind on a {name} rooftop", "바람"),
    row("island", "An island setting in {name}", "섬마을"),
    row("harbor", "A harbor in {name}", "항구"),
    row("market", "A market street in {name}", "시장"),
    row("palace", "A palace in {name}", "왕궁"),
    row("hanbok", "Hanbok worn in {name}", "한복"),
    row("sword", "A sword in {name}", "칼날"),
    row("king", "A king in {name}", "임금"),
    row("queen", "A queen in {name}", "왕비"),
    row("prince", "A prince in {name}", "왕자"),
    row("princess", "A princess in {name}", "공주"),
    row("servant", "A servant in {name}", "시녀"),
    row("eunuch", "A court official in {name}", "내관"),
    row("rebellion", "A rebellion in {name}", "반란"),
    row("throne", "The throne everyone wants in {name}", "왕좌"),
    row("war", "A war that frames {name}", "전쟁"),
    row("peace", "Peace after the storm in {name}", "평화"),
    row("escape", "An escape in {name}", "탈출"),
    row("chase", "A chase in {name}", "추격"),
    row("fight", "A fight scene in {name}", "싸움"),
    row("gun", "A gun in {name}", "권총"),
    row("car", "A car chase in {name}", "자동차", 2),
    row("train", "A train in {name}", "기차"),
    row("plane", "A plane in {name}", "비행기", 2),
    row("ship", "A ship in {name}", "선박"),
    row("border", "A border crossed in {name}", "국경"),
    row("north", "The North in {name}", "북한"),
    row("south", "The South in {name}", "남한"),
    row("abroad", "An overseas chapter of {name}", "해외"),
    row("hometown", "A hometown return in {name}", "고향"),
    row("busan", "Busan streets in {name}", "부산"),
    row("incheon", "Incheon in {name}", "인천"),
    row("jeju", "Jeju in {name}", "제주"),
    row("gangnam", "Gangnam in {name}", "강남"),
    row("itaewon", "Itaewon in {name}", "이태원", 2),
    row("hongdae", "Hongdae in {name}", "홍대"),
    row("myeongdong", "Myeongdong in {name}", "명동"),
    row("tvn", "A channel that often airs stories like {name}", "티빙"),
    row("sbs", "A Saturday-Sunday home for {name}", "에스비에스", 3),
    row("kbs", "A public broadcaster of {name}", "케이비에스", 3),
    row("mbc", "A broadcaster of {name}", "엠비씨", 2),
    row("jtbc", "A cable home for {name}", "제이티비씨", 3),
    row("tvn-ch", "A cable romance home for {name}", "티브이엔", 2),
    row("disney", "A streamer that carried {name}", "디즈니", 2),
    row("amazon", "A streamer that carried {name}", "아마존", 2),
    row("box-office", "Ticket sales for {name}", "박스오피스", 3),
    row("opening-week", "The opening week of {name}", "개봉주", 2),
    row("premiere-film", "The premiere night of {name}", "시사회", 2),
    row("critic", "A critic watching {name}", "평론"),
    row("review", "A review of {name}", "리뷰"),
    row("rating-star", "Star ratings for {name}", "별점"),
    row("subtitle", "Subtitles that carried {name} abroad", "자막"),
    row("dubbing", "A dubbed version of {name}", "더빙"),
    row("remake-of", "A remake based on {name}", "리메이크", 2),
    row("webtoon-src", "A webtoon behind {name}", "웹툰"),
    row("novel-src", "A novel behind {name}", "소설"),
    row("true-story", "A true story behind {name}", "실화"),
    row("period", "A period setting in {name}", "시대극", 2),
    row("sageuk", "A historical {name} story", "사극"),
    row("modern", "A modern-day {name} story", "현대극", 2),
    row("fantasy", "Fantasy inside {name}", "판타지", 2),
    row("horror", "Horror inside {name}", "공포"),
    row("action", "Action inside {name}", "액션"),
    row("sf", "Science fiction inside {name}", "공상과학", 2),
    row("zombie", "The undead threat in {name}", "좀비"),
    row("ghost", "A ghost in {name}", "귀신"),
    row("monster", "A monster in {name}", "괴물"),
    row("magic", "Magic in {name}", "마법"),
    row("time-slip", "A time slip in {name}", "타임슬립", 3),
    row("reincarnation", "A second life in {name}", "환생"),
    row("dream-seq", "A dream sequence in {name}", "꿈속"),
    row("flashback", "A flashback in {name}", "회상"),
    row("montage", "A montage in {name}", "몽타주", 2),
    row("cliffhanger", "A cliffhanger ending in {name}", "클리프행어", 3),
    row("open-ending", "An open ending in {name}", "열린결말", 2),
    row("happy-end", "A happy ending in {name}", "해피엔딩", 2),
    row("sad-end", "A sad ending in {name}", "새드엔딩", 2),
    row("mid-point", "The midpoint turn of {name}", "중반"),
    row("climax", "The climax of {name}", "클라이맥스", 3),
    row("epilogue", "An epilogue after {name}", "에필로그", 2),
    row("prologue", "A prologue before {name}", "프롤로그", 2),
    row("title-card", "The title card of {name}", "타이틀", 2),
    row("opening-title", "The opening titles of {name}", "오프닝", 2),
    row("ending-credit", "The ending credits of {name}", "엔딩크레딧", 3),
    row("cameo-star", "A star cameo in {name}", "특별출연", 2),
    row("extra-role", "An extra in a {name} crowd", "엑스트라", 2),
    row("stand-in", "A stand-in on the {name} set", "대역"),
    row("stunt", "A stunt in {name}", "스턴트", 2),
    row("cgi", "Digital effects in {name}", "씨지아이", 3),
    row("vfx", "Visual effects in {name}", "특수효과", 2),
    row("sound-fx", "Sound design in {name}", "음향"),
    row("color-grade", "The color look of {name}", "색보정", 2),
    row("edit", "The edit of {name}", "편집"),
    row("cut", "A cut of a {name} scene", "컷편집"),
    row("take", "Another take of a {name} scene", "테이크", 2),
    row("ng", "A blooper from the {name} set", "엔지"),
    row("ad-lib", "An ad-lib in {name}", "애드립", 2),
    row("line-read", "A line reading in {name}", "대사"),
    row("voice", "A voice that carries {name}", "목소리", 2),
    row("look", "A look that defines {name}", "눈빛"),
    row("smile", "A smile that sells {name}", "미소"),
    row("cry-act", "A crying scene in {name}", "울음"),
    row("laugh", "A laugh in {name}", "웃음"),
    row("silence", "A silence that hurts in {name}", "침묵"),
    row("theme-color", "A color motif in {name}", "색감"),
    row("symbol", "A repeating symbol in {name}", "상징"),
    row("motif", "A visual motif in {name}", "모티프", 2),
    row("foreshadow", "Foreshadowing in {name}", "복선"),
    row("payoff", "A payoff planted earlier in {name}", "회수"),
    row("macguffin", "An object everyone chases in {name}", "맥거핀", 2),
    row("macguffin-kr", "A plot object in {name}", "물건"),
    row("map", "A map that guides {name}", "지도"),
    row("letter-seal", "A sealed letter in {name}", "봉인"),
    row("password", "A password in {name}", "암호"),
    row("code", "A code hidden in {name}", "코드"),
    row("clock", "A clock counting down in {name}", "시계태엽", 2),
    row("deadline", "A deadline in {name}", "시한"),
    row("countdown", "A countdown in {name}", "카운트다운", 3),
    row("last-chance", "A last chance in {name}", "마지막기회", 3),
    row("second-chance", "A second chance in {name}", "두번째기회", 3),
    row("new-life", "A new life after {name}’s storm", "새출발", 2),
    row("homecoming", "A homecoming in {name}", "귀향"),
    row("farewell", "A farewell in {name}", "작별"),
    row("see-you", "A see-you-again in {name}", "또만나", 2),
    row("credits-ost", "The song over {name} credits", "엔딩곡", 2),
    row("hit-line", "A line everyone quoted from {name}", "유행어", 2),
    row("meme", "A meme born from {name}", "인터넷밈"),
    row("fandom", "The fan community around {name}", "팬덤"),
    row("binge", "Watching all of {name} in one night", "정주행", 2),
    row("rewatch", "Watching {name} again", "재시청", 2),
    row("spoiler", "A spoiler for {name}", "스포일러", 3),
    row("theory", "A fan theory about {name}", "추리"),
    row("forum", "Where fans debate {name}", "게시판", 2),
    row("clip", "A short clip from {name}", "클립"),
    row("gif", "A looping {name} moment", "움짤"),
    row("ost-chart", "Charts a {name} OST climbs", "음원차트", 2),
    row("award-best", "A best-drama prize for {name}", "대상"),
    row("popularity", "Popularity votes for {name}", "인기"),
    row("global-hit", "A worldwide run for {name}", "세계적", 2),
    row("export", "How {name} traveled abroad", "수출"),
    row("wave", "The Korean Wave lifting {name}", "열풍"),
    row("craze", "The craze around {name}", "열기"),
    row("record-rating", "A record rating for {name}", "최고시청률", 3),
    row("timeslot", "The timeslot {name} owned", "시간대", 2),
    row("weekend", "A weekend airing of {name}", "주말드라마", 3),
    row("weeknight", "A weeknight airing of {name}", "평일", 2),
    row("miniseries", "A short run of {name}", "미니시리즈", 3),
    row("feature", "A feature-length {name}", "장편"),
    row("short-film", "A short version of a {name} story", "단편"),
    row("sequel", "A sequel to {name}", "속편"),
    row("prequel", "A prequel to {name}", "프리퀄", 2),
    row("spinoff", "A spin-off from {name}", "스핀오프", 2),
    row("universe", "A shared universe around {name}", "세계관", 2),
    row("franchise", "A franchise grown from {name}", "프랜차이즈", 3),
    row("reboot", "A reboot of {name}", "리부트", 2),
    row("original-ip", "The original IP behind {name}", "지식재산", 2),
    row("rights", "The rights to remake {name}", "판권"),
    row("budget", "The budget behind {name}", "제작비", 2),
    row("investor", "Money behind {name}", "투자"),
    row("studio-co", "The studio that made {name}", "제작사", 2),
    row("distributor", "The distributor of {name}", "배급사", 2),
    row("screen", "A theater screen showing {name}", "스크린", 2),
    row("imax", "A giant screen for {name}", "아이맥스", 2),
    row("ticket-sold", "A ticket sold for {name}", "입장권"),
    row("sold-out", "A sold-out {name} screening", "매진"),
    row("encore-run", "An encore run of {name}", "재개봉", 2),
    row("director-cut", "A director’s cut of {name}", "감독판", 2),
    row("unrated", "An unrated cut of {name}", "무삭제", 2),
    row("age-rate", "The age rating of {name}", "등급"),
    row("all-ages", "A family-friendly {name}", "전체관람가", 3),
    row("fifteen", "A 15 rating for {name}", "십오세", 2),
    row("nineteen", "A 19 rating for {name}", "청불"),
    row("warning", "A content warning on {name}", "경고"),
    row("violence", "Violence in {name}", "폭력"),
    row("romance-plot", "The romance plot of {name}", "연애"),
    row("bromance", "A bromance in {name}", "브로맨스", 2),
    row("found-family", "A found family in {name}", "의가족", 2),
    row("team", "A team that holds {name} together", "한팀"),
    row("leader", "A leader inside {name}", "리더"),
    row("rookie", "A rookie in {name}", "신인"),
    row("veteran", "A veteran in {name}", "베테랑", 2),
    row("genius", "A genius in {name}", "천재"),
    row("underdog", "An underdog in {name}", "약자"),
    row("heroine", "The heroine of {name}", "여주"),
    row("hero-male", "The hero of {name}", "남주"),
    row("antihero", "An antihero in {name}", "안티히어로", 3),
    row("mastermind", "A mastermind in {name}", "흑막"),
    row("twist-id", "A hidden identity in {name}", "정체"),
    row("mask", "A mask worn in {name}", "가면"),
    row("disguise", "A disguise in {name}", "변장"),
    row("undercover", "An undercover life in {name}", "잠입"),
    row("double-life", "A double life in {name}", "이중생활", 2),
    row("amnesia", "Lost memory in {name}", "기억상실", 2),
    row("coma", "A coma in {name}", "혼수"),
    row("illness", "An illness in {name}", "병마"),
    row("hospital-room", "A hospital room in {name}", "병실"),
    row("operation", "An operation in {name}", "수술"),
    row("medicine", "Medicine in {name}", "약봉지"),
    row("life", "A life on the line in {name}", "목숨"),
    row("death", "A death that changes {name}", "죽음"),
    row("funeral", "A funeral in {name}", "장례"),
    row("grave", "A grave in {name}", "묘지"),
    row("afterlife", "The afterlife in {name}", "저승"),
    row("soul", "A soul in {name}", "영혼"),
    row("fate-red", "The red thread of fate in {name}", "붉은실", 2),
    row("destiny-meet", "A destined meeting in {name}", "숙명"),
    row("coincidence", "A coincidence that starts {name}", "우연"),
    row("miracle", "A miracle in {name}", "기적"),
    row("luck", "Luck in {name}", "행운"),
    row("curse", "A curse in {name}", "저주"),
    row("blessing", "A blessing in {name}", "축복"),
    row("prayer", "A prayer in {name}", "기도"),
    row("temple", "A temple in {name}", "산사"),
    row("church", "A church in {name}", "교회"),
    row("school-gate", "The school gate in {name}", "교문"),
    row("classroom", "A classroom in {name}", "교실"),
    row("rooftop-school", "The school rooftop in {name}", "옥상교실", 2),
    row("bus-stop", "A bus stop goodbye in {name}", "정류장", 2),
    row("crosswalk", "A crosswalk meeting in {name}", "횡단보도", 2),
    row("convenience", "A convenience store in {name}", "편의점", 2),
    row("pocha", "A pocha night in {name}", "포차"),
    row("nopo", "A late-night stall in {name}", "노점"),
    row("high-rise", "A high-rise in {name}", "고층"),
    row("basement", "A basement in {name}", "지하"),
    row("rooftop-bar", "A rooftop bar in {name}", "루프탑", 2),
    row("hotel", "A hotel in {name}", "호텔"),
    row("airport", "An airport goodbye in {name}", "공항"),
    row("platform", "A station platform in {name}", "승강장", 2),
    row("ticket-gate", "A ticket gate in {name}", "개찰구", 2),
  ];
}

module.exports = { kpopShared, dramaShared };
